# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calc.ui'
#
# Created: Fri Jan  9 10:57:18 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgCalc(object):
    def setupUi(self, dlgCalc):
        dlgCalc.setObjectName(_fromUtf8("dlgCalc"))
        dlgCalc.resize(800, 510)
        dlgCalc.setMinimumSize(QtCore.QSize(800, 510))
        dlgCalc.setMaximumSize(QtCore.QSize(800, 510))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qm_calc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgCalc.setWindowIcon(icon)
        self.line_3 = QtGui.QFrame(dlgCalc)
        self.line_3.setGeometry(QtCore.QRect(0, 370, 801, 21))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.frCalcEdit = QtGui.QFrame(dlgCalc)
        self.frCalcEdit.setEnabled(True)
        self.frCalcEdit.setGeometry(QtCore.QRect(0, 10, 801, 361))
        self.frCalcEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frCalcEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frCalcEdit.setObjectName(_fromUtf8("frCalcEdit"))
        self.line_6 = QtGui.QFrame(self.frCalcEdit)
        self.line_6.setGeometry(QtCore.QRect(10, 80, 281, 21))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 281, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlMeasureType = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlMeasureType.setMargin(0)
        self.vlMeasureType.setObjectName(_fromUtf8("vlMeasureType"))
        self.lblCalcType = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCalcType.setObjectName(_fromUtf8("lblCalcType"))
        self.vlMeasureType.addWidget(self.lblCalcType)
        self.hlMeasureType = QtGui.QHBoxLayout()
        self.hlMeasureType.setObjectName(_fromUtf8("hlMeasureType"))
        self.rdoPoint = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoPoint.setChecked(True)
        self.rdoPoint.setObjectName(_fromUtf8("rdoPoint"))
        self.hlMeasureType.addWidget(self.rdoPoint)
        self.rdoLine = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoLine.setObjectName(_fromUtf8("rdoLine"))
        self.hlMeasureType.addWidget(self.rdoLine)
        self.rdoArea = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoArea.setObjectName(_fromUtf8("rdoArea"))
        self.hlMeasureType.addWidget(self.rdoArea)
        self.rdoRaster = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rdoRaster.setObjectName(_fromUtf8("rdoRaster"))
        self.hlMeasureType.addWidget(self.rdoRaster)
        self.vlMeasureType.addLayout(self.hlMeasureType)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 281, 131))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlMeasureLayer = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlMeasureLayer.setMargin(0)
        self.vlMeasureLayer.setObjectName(_fromUtf8("vlMeasureLayer"))
        self.lblLayer = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblLayer.setObjectName(_fromUtf8("lblLayer"))
        self.vlMeasureLayer.addWidget(self.lblLayer)
        self.cbMeasureLayer = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cbMeasureLayer.setObjectName(_fromUtf8("cbMeasureLayer"))
        self.vlMeasureLayer.addWidget(self.cbMeasureLayer)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSingleMultiple = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSingleMultiple.setObjectName(_fromUtf8("lblSingleMultiple"))
        self.verticalLayout_2.addWidget(self.lblSingleMultiple)
        self.hlCalculation_3 = QtGui.QHBoxLayout()
        self.hlCalculation_3.setObjectName(_fromUtf8("hlCalculation_3"))
        self.rdoCalcSingle = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rdoCalcSingle.setChecked(True)
        self.rdoCalcSingle.setObjectName(_fromUtf8("rdoCalcSingle"))
        self.hlCalculation_3.addWidget(self.rdoCalcSingle)
        self.rdoCalcMulti = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rdoCalcMulti.setChecked(False)
        self.rdoCalcMulti.setObjectName(_fromUtf8("rdoCalcMulti"))
        self.hlCalculation_3.addWidget(self.rdoCalcMulti)
        self.verticalLayout_2.addLayout(self.hlCalculation_3)
        self.vlMeasureLayer.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.frCalcEdit)
        self.line.setGeometry(QtCore.QRect(293, 10, 16, 301))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget_3 = QtGui.QWidget(self.frCalcEdit)
        self.layoutWidget_3.setGeometry(QtCore.QRect(310, 10, 481, 121))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.vlCalc = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.vlCalc.setMargin(0)
        self.vlCalc.setObjectName(_fromUtf8("vlCalc"))
        self.lblMeasureOrCalc = QtGui.QLabel(self.layoutWidget_3)
        self.lblMeasureOrCalc.setObjectName(_fromUtf8("lblMeasureOrCalc"))
        self.vlCalc.addWidget(self.lblMeasureOrCalc)
        self.hlCalculation = QtGui.QHBoxLayout()
        self.hlCalculation.setObjectName(_fromUtf8("hlCalculation"))
        self.rdoMeasure = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoMeasure.setChecked(True)
        self.rdoMeasure.setObjectName(_fromUtf8("rdoMeasure"))
        self.hlCalculation.addWidget(self.rdoMeasure)
        self.rdoCalculate = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoCalculate.setObjectName(_fromUtf8("rdoCalculate"))
        self.hlCalculation.addWidget(self.rdoCalculate)
        self.rdoValue = QtGui.QRadioButton(self.layoutWidget_3)
        self.rdoValue.setChecked(False)
        self.rdoValue.setObjectName(_fromUtf8("rdoValue"))
        self.hlCalculation.addWidget(self.rdoValue)
        self.vlCalc.addLayout(self.hlCalculation)
        self.lblCalcField = QtGui.QLabel(self.layoutWidget_3)
        self.lblCalcField.setEnabled(False)
        self.lblCalcField.setObjectName(_fromUtf8("lblCalcField"))
        self.vlCalc.addWidget(self.lblCalcField)
        self.cbCalcField = QtGui.QComboBox(self.layoutWidget_3)
        self.cbCalcField.setEnabled(False)
        self.cbCalcField.setObjectName(_fromUtf8("cbCalcField"))
        self.vlCalc.addWidget(self.cbCalcField)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frCalcEdit)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(310, 150, 481, 57))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblMultipleAction = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblMultipleAction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblMultipleAction.setObjectName(_fromUtf8("lblMultipleAction"))
        self.verticalLayout.addWidget(self.lblMultipleAction)
        self.hlCalculation_2 = QtGui.QHBoxLayout()
        self.hlCalculation_2.setObjectName(_fromUtf8("hlCalculation_2"))
        self.rdoSum = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoSum.setChecked(True)
        self.rdoSum.setObjectName(_fromUtf8("rdoSum"))
        self.hlCalculation_2.addWidget(self.rdoSum)
        self.rdoMean = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMean.setChecked(False)
        self.rdoMean.setObjectName(_fromUtf8("rdoMean"))
        self.hlCalculation_2.addWidget(self.rdoMean)
        self.rdoMax = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMax.setObjectName(_fromUtf8("rdoMax"))
        self.hlCalculation_2.addWidget(self.rdoMax)
        self.rdoMin = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoMin.setObjectName(_fromUtf8("rdoMin"))
        self.hlCalculation_2.addWidget(self.rdoMin)
        self.rdoCount = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoCount.setObjectName(_fromUtf8("rdoCount"))
        self.hlCalculation_2.addWidget(self.rdoCount)
        self.rdoPresence = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.rdoPresence.setObjectName(_fromUtf8("rdoPresence"))
        self.hlCalculation_2.addWidget(self.rdoPresence)
        self.verticalLayout.addLayout(self.hlCalculation_2)
        self.line_5 = QtGui.QFrame(self.frCalcEdit)
        self.line_5.setGeometry(QtCore.QRect(310, 200, 481, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_7 = QtGui.QFrame(self.frCalcEdit)
        self.line_7.setGeometry(QtCore.QRect(10, 160, 281, 21))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 71))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblPlanningGrid = QtGui.QLabel(self.gridLayoutWidget)
        self.lblPlanningGrid.setObjectName(_fromUtf8("lblPlanningGrid"))
        self.gridLayout.addWidget(self.lblPlanningGrid, 0, 0, 1, 1)
        self.lblPuId = QtGui.QLabel(self.gridLayoutWidget)
        self.lblPuId.setObjectName(_fromUtf8("lblPuId"))
        self.gridLayout.addWidget(self.lblPuId, 0, 1, 1, 1)
        self.cbPuId = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbPuId.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbPuId.setObjectName(_fromUtf8("cbPuId"))
        self.gridLayout.addWidget(self.cbPuId, 1, 1, 1, 1)
        self.cbPlanningGrid = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbPlanningGrid.setObjectName(_fromUtf8("cbPlanningGrid"))
        self.gridLayout.addWidget(self.cbPlanningGrid, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.frCalcEdit)
        self.line_2.setGeometry(QtCore.QRect(310, 130, 479, 19))
        self.line_2.setMinimumSize(QtCore.QSize(0, 19))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_8 = QtGui.QFrame(self.frCalcEdit)
        self.line_8.setGeometry(QtCore.QRect(10, 310, 781, 21))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.layoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 220, 479, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblWriteLabel = QtGui.QLabel(self.layoutWidget)
        self.lblWriteLabel.setEnabled(True)
        self.lblWriteLabel.setObjectName(_fromUtf8("lblWriteLabel"))
        self.horizontalLayout_6.addWidget(self.lblWriteLabel)
        self.rdoWriteLyr = QtGui.QRadioButton(self.layoutWidget)
        self.rdoWriteLyr.setChecked(True)
        self.rdoWriteLyr.setObjectName(_fromUtf8("rdoWriteLyr"))
        self.horizontalLayout_6.addWidget(self.rdoWriteLyr)
        self.rdoWriteFile = QtGui.QRadioButton(self.layoutWidget)
        self.rdoWriteFile.setObjectName(_fromUtf8("rdoWriteFile"))
        self.horizontalLayout_6.addWidget(self.rdoWriteFile)
        self.layoutWidget1 = QtGui.QWidget(self.frCalcEdit)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 250, 479, 64))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.vlOutput = QtGui.QVBoxLayout()
        self.vlOutput.setObjectName(_fromUtf8("vlOutput"))
        self.lblSelectField = QtGui.QLabel(self.layoutWidget1)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.vlOutput.addWidget(self.lblSelectField)
        self.cbOutputField = QtGui.QComboBox(self.layoutWidget1)
        self.cbOutputField.setObjectName(_fromUtf8("cbOutputField"))
        self.vlOutput.addWidget(self.cbOutputField)
        self.horizontalLayout.addLayout(self.vlOutput)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblNewField = QtGui.QLabel(self.layoutWidget1)
        self.lblNewField.setEnabled(True)
        self.lblNewField.setObjectName(_fromUtf8("lblNewField"))
        self.verticalLayout_3.addWidget(self.lblNewField)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.leOutput = QtGui.QLineEdit(self.layoutWidget1)
        self.leOutput.setEnabled(True)
        self.leOutput.setMaxLength(10)
        self.leOutput.setReadOnly(False)
        self.leOutput.setObjectName(_fromUtf8("leOutput"))
        self.horizontalLayout_5.addWidget(self.leOutput)
        self.tbDestFile = QtGui.QToolButton(self.layoutWidget1)
        self.tbDestFile.setObjectName(_fromUtf8("tbDestFile"))
        self.horizontalLayout_5.addWidget(self.tbDestFile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget = QtGui.QWidget(self.frCalcEdit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(15, 330, 771, 33))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chbxRasterize = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chbxRasterize.setObjectName(_fromUtf8("chbxRasterize"))
        self.horizontalLayout_2.addWidget(self.chbxRasterize)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblPixelSize = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblPixelSize.setEnabled(False)
        self.lblPixelSize.setObjectName(_fromUtf8("lblPixelSize"))
        self.horizontalLayout_2.addWidget(self.lblPixelSize)
        self.spbxPixelSize = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spbxPixelSize.setEnabled(False)
        self.spbxPixelSize.setMinimumSize(QtCore.QSize(150, 0))
        self.spbxPixelSize.setMinimum(1)
        self.spbxPixelSize.setMaximum(1000000)
        self.spbxPixelSize.setSingleStep(10)
        self.spbxPixelSize.setProperty("value", 100)
        self.spbxPixelSize.setObjectName(_fromUtf8("spbxPixelSize"))
        self.horizontalLayout_2.addWidget(self.spbxPixelSize)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.layoutWidget2 = QtGui.QWidget(dlgCalc)
        self.layoutWidget2.setGeometry(QtCore.QRect(220, 470, 366, 33))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.hlActions = QtGui.QHBoxLayout(self.layoutWidget2)
        self.hlActions.setSpacing(8)
        self.hlActions.setMargin(0)
        self.hlActions.setObjectName(_fromUtf8("hlActions"))
        self.pbRun = QtGui.QPushButton(self.layoutWidget2)
        self.pbRun.setEnabled(False)
        self.pbRun.setObjectName(_fromUtf8("pbRun"))
        self.hlActions.addWidget(self.pbRun)
        self.pbCancel = QtGui.QPushButton(self.layoutWidget2)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.hlActions.addWidget(self.pbCancel)
        self.pbClose = QtGui.QPushButton(self.layoutWidget2)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlActions.addWidget(self.pbClose)
        self.line_4 = QtGui.QFrame(dlgCalc)
        self.line_4.setGeometry(QtCore.QRect(0, 450, 801, 21))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(dlgCalc)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 390, 781, 61))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblCalcProcess = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.lblCalcProcess.setObjectName(_fromUtf8("lblCalcProcess"))
        self.verticalLayout_5.addWidget(self.lblCalcProcess)
        self.pbCalcProgress = QtGui.QProgressBar(self.horizontalLayoutWidget_2)
        self.pbCalcProgress.setProperty("value", 0)
        self.pbCalcProgress.setObjectName(_fromUtf8("pbCalcProgress"))
        self.verticalLayout_5.addWidget(self.pbCalcProgress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblCalcStep = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.lblCalcStep.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lblCalcStep.setObjectName(_fromUtf8("lblCalcStep"))
        self.verticalLayout_4.addWidget(self.lblCalcStep)
        self.pbStepProgress = QtGui.QProgressBar(self.horizontalLayoutWidget_2)
        self.pbStepProgress.setProperty("value", 0)
        self.pbStepProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStepProgress.setTextVisible(True)
        self.pbStepProgress.setObjectName(_fromUtf8("pbStepProgress"))
        self.verticalLayout_4.addWidget(self.pbStepProgress)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)

        self.retranslateUi(dlgCalc)
        QtCore.QObject.connect(self.pbClose, QtCore.SIGNAL(_fromUtf8("clicked()")), dlgCalc.close)
        QtCore.QMetaObject.connectSlotsByName(dlgCalc)
        dlgCalc.setTabOrder(self.cbPlanningGrid, self.cbPuId)
        dlgCalc.setTabOrder(self.cbPuId, self.rdoPoint)
        dlgCalc.setTabOrder(self.rdoPoint, self.rdoLine)
        dlgCalc.setTabOrder(self.rdoLine, self.rdoArea)
        dlgCalc.setTabOrder(self.rdoArea, self.rdoRaster)
        dlgCalc.setTabOrder(self.rdoRaster, self.cbMeasureLayer)
        dlgCalc.setTabOrder(self.cbMeasureLayer, self.rdoCalcSingle)
        dlgCalc.setTabOrder(self.rdoCalcSingle, self.rdoCalcMulti)
        dlgCalc.setTabOrder(self.rdoCalcMulti, self.rdoMeasure)
        dlgCalc.setTabOrder(self.rdoMeasure, self.rdoCalculate)
        dlgCalc.setTabOrder(self.rdoCalculate, self.rdoValue)
        dlgCalc.setTabOrder(self.rdoValue, self.cbCalcField)
        dlgCalc.setTabOrder(self.cbCalcField, self.rdoSum)
        dlgCalc.setTabOrder(self.rdoSum, self.rdoMean)
        dlgCalc.setTabOrder(self.rdoMean, self.rdoMax)
        dlgCalc.setTabOrder(self.rdoMax, self.rdoMin)
        dlgCalc.setTabOrder(self.rdoMin, self.rdoCount)
        dlgCalc.setTabOrder(self.rdoCount, self.rdoWriteLyr)
        dlgCalc.setTabOrder(self.rdoWriteLyr, self.rdoWriteFile)
        dlgCalc.setTabOrder(self.rdoWriteFile, self.cbOutputField)
        dlgCalc.setTabOrder(self.cbOutputField, self.leOutput)
        dlgCalc.setTabOrder(self.leOutput, self.tbDestFile)
        dlgCalc.setTabOrder(self.tbDestFile, self.chbxRasterize)
        dlgCalc.setTabOrder(self.chbxRasterize, self.spbxPixelSize)
        dlgCalc.setTabOrder(self.spbxPixelSize, self.pbRun)
        dlgCalc.setTabOrder(self.pbRun, self.pbCancel)
        dlgCalc.setTabOrder(self.pbCancel, self.pbClose)

    def retranslateUi(self, dlgCalc):
        dlgCalc.setWindowTitle(QtGui.QApplication.translate("dlgCalc", "Calculate Planning Unit Values", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcType.setText(QtGui.QApplication.translate("dlgCalc", "Select input layer type", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPoint.setText(QtGui.QApplication.translate("dlgCalc", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoLine.setText(QtGui.QApplication.translate("dlgCalc", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoArea.setText(QtGui.QApplication.translate("dlgCalc", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoRaster.setText(QtGui.QApplication.translate("dlgCalc", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayer.setText(QtGui.QApplication.translate("dlgCalc", "Select layer to measure", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSingleMultiple.setText(QtGui.QApplication.translate("dlgCalc", "On intersection assign value to", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalcSingle.setText(QtGui.QApplication.translate("dlgCalc", "Single Field", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalcMulti.setText(QtGui.QApplication.translate("dlgCalc", "Multiple Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMeasureOrCalc.setText(QtGui.QApplication.translate("dlgCalc", "On intersection use the following value", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMeasure.setText(QtGui.QApplication.translate("dlgCalc", "Measure (count,length,area)", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCalculate.setText(QtGui.QApplication.translate("dlgCalc", "Measure x Value", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoValue.setText(QtGui.QApplication.translate("dlgCalc", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcField.setText(QtGui.QApplication.translate("dlgCalc", "Select Field for Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMultipleAction.setText(QtGui.QApplication.translate("dlgCalc", "On multiple intersections use", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSum.setText(QtGui.QApplication.translate("dlgCalc", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMean.setText(QtGui.QApplication.translate("dlgCalc", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMax.setText(QtGui.QApplication.translate("dlgCalc", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoMin.setText(QtGui.QApplication.translate("dlgCalc", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoCount.setText(QtGui.QApplication.translate("dlgCalc", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoPresence.setText(QtGui.QApplication.translate("dlgCalc", "Presence", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlanningGrid.setText(QtGui.QApplication.translate("dlgCalc", "Planning Unit Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPuId.setText(QtGui.QApplication.translate("dlgCalc", "ID Field", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWriteLabel.setText(QtGui.QApplication.translate("dlgCalc", "Write results to:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoWriteLyr.setText(QtGui.QApplication.translate("dlgCalc", "PU Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoWriteFile.setText(QtGui.QApplication.translate("dlgCalc", "CSV File(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectField.setText(QtGui.QApplication.translate("dlgCalc", "Select output field name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNewField.setText(QtGui.QApplication.translate("dlgCalc", "Enter new field name", None, QtGui.QApplication.UnicodeUTF8))
        self.tbDestFile.setText(QtGui.QApplication.translate("dlgCalc", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxRasterize.setText(QtGui.QApplication.translate("dlgCalc", "Use raster estimation for areas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPixelSize.setText(QtGui.QApplication.translate("dlgCalc", "Pixel Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRun.setText(QtGui.QApplication.translate("dlgCalc", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("dlgCalc", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("dlgCalc", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcProcess.setText(QtGui.QApplication.translate("dlgCalc", "Calculation Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCalcStep.setText(QtGui.QApplication.translate("dlgCalc", "Current Step:", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
