# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_configure_run.ui'
#
# Created: Wed Mar 25 16:09:14 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlgConfigureRun(object):
    def setupUi(self, dlgConfigureRun):
        dlgConfigureRun.setObjectName(_fromUtf8("dlgConfigureRun"))
        dlgConfigureRun.setEnabled(True)
        dlgConfigureRun.resize(800, 675)
        dlgConfigureRun.setMinimumSize(QtCore.QSize(800, 675))
        self.gridLayout_3 = QtGui.QGridLayout(dlgConfigureRun)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hzSettingsGISButtons = QtGui.QHBoxLayout()
        self.hzSettingsGISButtons.setObjectName(_fromUtf8("hzSettingsGISButtons"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hzSettingsGISButtons.addItem(spacerItem)
        self.pbClose = QtGui.QPushButton(dlgConfigureRun)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hzSettingsGISButtons.addWidget(self.pbClose)
        self.gridLayout_3.addLayout(self.hzSettingsGISButtons, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblWorkingProject = QtGui.QLabel(dlgConfigureRun)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWorkingProject.sizePolicy().hasHeightForWidth())
        self.lblWorkingProject.setSizePolicy(sizePolicy)
        self.lblWorkingProject.setMaximumSize(QtCore.QSize(250, 100))
        self.lblWorkingProject.setObjectName(_fromUtf8("lblWorkingProject"))
        self.horizontalLayout_2.addWidget(self.lblWorkingProject)
        self.cbWorkingProject = QtGui.QComboBox(dlgConfigureRun)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbWorkingProject.sizePolicy().hasHeightForWidth())
        self.cbWorkingProject.setSizePolicy(sizePolicy)
        self.cbWorkingProject.setObjectName(_fromUtf8("cbWorkingProject"))
        self.horizontalLayout_2.addWidget(self.cbWorkingProject)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.twInputs = QtGui.QTabWidget(dlgConfigureRun)
        self.twInputs.setEnabled(True)
        self.twInputs.setObjectName(_fromUtf8("twInputs"))
        self.tbGeneral = QtGui.QWidget()
        self.tbGeneral.setObjectName(_fromUtf8("tbGeneral"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tbGeneral)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.frZonesGeneral = QtGui.QFrame(self.tbGeneral)
        self.frZonesGeneral.setEnabled(True)
        self.frZonesGeneral.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZonesGeneral.setFrameShadow(QtGui.QFrame.Plain)
        self.frZonesGeneral.setObjectName(_fromUtf8("frZonesGeneral"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frZonesGeneral)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.flZonesGeneralParameters = QtGui.QFormLayout()
        self.flZonesGeneralParameters.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flZonesGeneralParameters.setObjectName(_fromUtf8("flZonesGeneralParameters"))
        self.lblAvailableZone = QtGui.QLabel(self.frZonesGeneral)
        self.lblAvailableZone.setEnabled(True)
        self.lblAvailableZone.setMinimumSize(QtCore.QSize(478, 0))
        self.lblAvailableZone.setObjectName(_fromUtf8("lblAvailableZone"))
        self.flZonesGeneralParameters.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblAvailableZone)
        self.cbAvailableZone = QtGui.QComboBox(self.frZonesGeneral)
        self.cbAvailableZone.setEnabled(True)
        self.cbAvailableZone.setObjectName(_fromUtf8("cbAvailableZone"))
        self.flZonesGeneralParameters.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbAvailableZone)
        self.gridLayout_4.addLayout(self.flZonesGeneralParameters, 1, 0, 1, 1)
        self.lblZonesParameters = QtGui.QLabel(self.frZonesGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZonesParameters.sizePolicy().hasHeightForWidth())
        self.lblZonesParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblZonesParameters.setFont(font)
        self.lblZonesParameters.setObjectName(_fromUtf8("lblZonesParameters"))
        self.gridLayout_4.addWidget(self.lblZonesParameters, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frZonesGeneral, 2, 0, 1, 1)
        self.frGeneralAll = QtGui.QFrame(self.tbGeneral)
        self.frGeneralAll.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frGeneralAll.sizePolicy().hasHeightForWidth())
        self.frGeneralAll.setSizePolicy(sizePolicy)
        self.frGeneralAll.setFrameShape(QtGui.QFrame.NoFrame)
        self.frGeneralAll.setFrameShadow(QtGui.QFrame.Plain)
        self.frGeneralAll.setObjectName(_fromUtf8("frGeneralAll"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frGeneralAll)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblGeneralParameters = QtGui.QLabel(self.frGeneralAll)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGeneralParameters.sizePolicy().hasHeightForWidth())
        self.lblGeneralParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGeneralParameters.setFont(font)
        self.lblGeneralParameters.setObjectName(_fromUtf8("lblGeneralParameters"))
        self.gridLayout_5.addWidget(self.lblGeneralParameters, 0, 0, 1, 1)
        self.flGeneralParameters = QtGui.QFormLayout()
        self.flGeneralParameters.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flGeneralParameters.setObjectName(_fromUtf8("flGeneralParameters"))
        self.lblBLM = QtGui.QLabel(self.frGeneralAll)
        self.lblBLM.setEnabled(True)
        self.lblBLM.setObjectName(_fromUtf8("lblBLM"))
        self.flGeneralParameters.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblBLM)
        self.spbxBLM = QtGui.QDoubleSpinBox(self.frGeneralAll)
        self.spbxBLM.setEnabled(True)
        self.spbxBLM.setDecimals(2)
        self.spbxBLM.setMinimum(0.0)
        self.spbxBLM.setMaximum(1000000000.0)
        self.spbxBLM.setSingleStep(1e-06)
        self.spbxBLM.setProperty("value", 1.0)
        self.spbxBLM.setObjectName(_fromUtf8("spbxBLM"))
        self.flGeneralParameters.setWidget(1, QtGui.QFormLayout.FieldRole, self.spbxBLM)
        self.lblNumReps = QtGui.QLabel(self.frGeneralAll)
        self.lblNumReps.setEnabled(True)
        self.lblNumReps.setObjectName(_fromUtf8("lblNumReps"))
        self.flGeneralParameters.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblNumReps)
        self.spbxNumReps = QtGui.QDoubleSpinBox(self.frGeneralAll)
        self.spbxNumReps.setEnabled(True)
        self.spbxNumReps.setDecimals(0)
        self.spbxNumReps.setMinimum(1.0)
        self.spbxNumReps.setMaximum(1000000000.0)
        self.spbxNumReps.setSingleStep(10.0)
        self.spbxNumReps.setProperty("value", 100.0)
        self.spbxNumReps.setObjectName(_fromUtf8("spbxNumReps"))
        self.flGeneralParameters.setWidget(3, QtGui.QFormLayout.FieldRole, self.spbxNumReps)
        self.lblNumItns = QtGui.QLabel(self.frGeneralAll)
        self.lblNumItns.setEnabled(True)
        self.lblNumItns.setObjectName(_fromUtf8("lblNumItns"))
        self.flGeneralParameters.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblNumItns)
        self.spbxNumItns = QtGui.QDoubleSpinBox(self.frGeneralAll)
        self.spbxNumItns.setEnabled(True)
        self.spbxNumItns.setDecimals(0)
        self.spbxNumItns.setMinimum(1.0)
        self.spbxNumItns.setMaximum(1000000000.0)
        self.spbxNumItns.setSingleStep(100000.0)
        self.spbxNumItns.setProperty("value", 1000000.0)
        self.spbxNumItns.setObjectName(_fromUtf8("spbxNumItns"))
        self.flGeneralParameters.setWidget(4, QtGui.QFormLayout.FieldRole, self.spbxNumItns)
        self.lblProp = QtGui.QLabel(self.frGeneralAll)
        self.lblProp.setEnabled(True)
        self.lblProp.setObjectName(_fromUtf8("lblProp"))
        self.flGeneralParameters.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblProp)
        self.spbxProp = QtGui.QDoubleSpinBox(self.frGeneralAll)
        self.spbxProp.setEnabled(True)
        self.spbxProp.setDecimals(2)
        self.spbxProp.setMinimum(0.0)
        self.spbxProp.setMaximum(1.0)
        self.spbxProp.setSingleStep(0.05)
        self.spbxProp.setProperty("value", 0.5)
        self.spbxProp.setObjectName(_fromUtf8("spbxProp"))
        self.flGeneralParameters.setWidget(0, QtGui.QFormLayout.FieldRole, self.spbxProp)
        self.lblMissLevel = QtGui.QLabel(self.frGeneralAll)
        self.lblMissLevel.setEnabled(True)
        self.lblMissLevel.setObjectName(_fromUtf8("lblMissLevel"))
        self.flGeneralParameters.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblMissLevel)
        self.spbxMissLevel = QtGui.QDoubleSpinBox(self.frGeneralAll)
        self.spbxMissLevel.setEnabled(True)
        self.spbxMissLevel.setMaximum(1.0)
        self.spbxMissLevel.setSingleStep(0.05)
        self.spbxMissLevel.setProperty("value", 0.95)
        self.spbxMissLevel.setObjectName(_fromUtf8("spbxMissLevel"))
        self.flGeneralParameters.setWidget(2, QtGui.QFormLayout.FieldRole, self.spbxMissLevel)
        self.lblVerbosity = QtGui.QLabel(self.frGeneralAll)
        self.lblVerbosity.setEnabled(True)
        self.lblVerbosity.setObjectName(_fromUtf8("lblVerbosity"))
        self.flGeneralParameters.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblVerbosity)
        self.cbVerbosity = QtGui.QComboBox(self.frGeneralAll)
        self.cbVerbosity.setEnabled(True)
        self.cbVerbosity.setObjectName(_fromUtf8("cbVerbosity"))
        self.cbVerbosity.addItem(_fromUtf8(""))
        self.cbVerbosity.addItem(_fromUtf8(""))
        self.flGeneralParameters.setWidget(5, QtGui.QFormLayout.FieldRole, self.cbVerbosity)
        self.gridLayout_5.addLayout(self.flGeneralParameters, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frGeneralAll, 0, 0, 1, 1)
        self.hlGeneralButtons = QtGui.QHBoxLayout()
        self.hlGeneralButtons.setObjectName(_fromUtf8("hlGeneralButtons"))
        self.pbEditGeneral = QtGui.QPushButton(self.tbGeneral)
        self.pbEditGeneral.setObjectName(_fromUtf8("pbEditGeneral"))
        self.hlGeneralButtons.addWidget(self.pbEditGeneral)
        self.pbSaveGeneral = QtGui.QPushButton(self.tbGeneral)
        self.pbSaveGeneral.setEnabled(False)
        self.pbSaveGeneral.setObjectName(_fromUtf8("pbSaveGeneral"))
        self.hlGeneralButtons.addWidget(self.pbSaveGeneral)
        self.pbCancelGeneral = QtGui.QPushButton(self.tbGeneral)
        self.pbCancelGeneral.setEnabled(False)
        self.pbCancelGeneral.setObjectName(_fromUtf8("pbCancelGeneral"))
        self.hlGeneralButtons.addWidget(self.pbCancelGeneral)
        self.gridLayout_15.addLayout(self.hlGeneralButtons, 4, 0, 1, 1)
        self.frMarxanCalibration = QtGui.QFrame(self.tbGeneral)
        self.frMarxanCalibration.setEnabled(True)
        self.frMarxanCalibration.setFrameShape(QtGui.QFrame.NoFrame)
        self.frMarxanCalibration.setFrameShadow(QtGui.QFrame.Plain)
        self.frMarxanCalibration.setObjectName(_fromUtf8("frMarxanCalibration"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frMarxanCalibration)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lblMarxanCalibration = QtGui.QLabel(self.frMarxanCalibration)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMarxanCalibration.setFont(font)
        self.lblMarxanCalibration.setObjectName(_fromUtf8("lblMarxanCalibration"))
        self.gridLayout_12.addWidget(self.lblMarxanCalibration, 0, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.lblSPFMethod = QtGui.QLabel(self.frMarxanCalibration)
        self.lblSPFMethod.setMinimumSize(QtCore.QSize(200, 0))
        self.lblSPFMethod.setObjectName(_fromUtf8("lblSPFMethod"))
        self.gridLayout_16.addWidget(self.lblSPFMethod, 0, 1, 1, 1)
        self.lblSPFStep = QtGui.QLabel(self.frMarxanCalibration)
        self.lblSPFStep.setObjectName(_fromUtf8("lblSPFStep"))
        self.gridLayout_16.addWidget(self.lblSPFStep, 0, 3, 1, 1)
        self.spbxSPFStep = QtGui.QDoubleSpinBox(self.frMarxanCalibration)
        self.spbxSPFStep.setMaximum(10000.0)
        self.spbxSPFStep.setSingleStep(0.5)
        self.spbxSPFStep.setProperty("value", 0.5)
        self.spbxSPFStep.setObjectName(_fromUtf8("spbxSPFStep"))
        self.gridLayout_16.addWidget(self.spbxSPFStep, 0, 4, 1, 1)
        self.cbSPFMethod = QtGui.QComboBox(self.frMarxanCalibration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSPFMethod.sizePolicy().hasHeightForWidth())
        self.cbSPFMethod.setSizePolicy(sizePolicy)
        self.cbSPFMethod.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSPFMethod.setObjectName(_fromUtf8("cbSPFMethod"))
        self.cbSPFMethod.addItem(_fromUtf8(""))
        self.cbSPFMethod.addItem(_fromUtf8(""))
        self.cbSPFMethod.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.cbSPFMethod, 0, 2, 1, 1)
        self.lblSolutionTarget = QtGui.QLabel(self.frMarxanCalibration)
        self.lblSolutionTarget.setObjectName(_fromUtf8("lblSolutionTarget"))
        self.gridLayout_16.addWidget(self.lblSolutionTarget, 2, 1, 1, 1)
        self.spbxSolutionTarget = QtGui.QSpinBox(self.frMarxanCalibration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbxSolutionTarget.sizePolicy().hasHeightForWidth())
        self.spbxSolutionTarget.setSizePolicy(sizePolicy)
        self.spbxSolutionTarget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.spbxSolutionTarget.setMaximum(100)
        self.spbxSolutionTarget.setSingleStep(10)
        self.spbxSolutionTarget.setProperty("value", 90)
        self.spbxSolutionTarget.setObjectName(_fromUtf8("spbxSolutionTarget"))
        self.gridLayout_16.addWidget(self.spbxSolutionTarget, 2, 2, 1, 1)
        self.lblIterationList = QtGui.QLabel(self.frMarxanCalibration)
        self.lblIterationList.setObjectName(_fromUtf8("lblIterationList"))
        self.gridLayout_16.addWidget(self.lblIterationList, 2, 3, 1, 1)
        self.leIterationList = QtGui.QLineEdit(self.frMarxanCalibration)
        self.leIterationList.setObjectName(_fromUtf8("leIterationList"))
        self.gridLayout_16.addWidget(self.leIterationList, 2, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frMarxanCalibration, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem1, 3, 0, 1, 1)
        self.twInputs.addTab(self.tbGeneral, _fromUtf8(""))
        self.tbBoundary = QtGui.QWidget()
        self.tbBoundary.setObjectName(_fromUtf8("tbBoundary"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tbBoundary)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.frBoundarySettings = QtGui.QFrame(self.tbBoundary)
        self.frBoundarySettings.setEnabled(True)
        self.frBoundarySettings.setFrameShape(QtGui.QFrame.NoFrame)
        self.frBoundarySettings.setFrameShadow(QtGui.QFrame.Plain)
        self.frBoundarySettings.setObjectName(_fromUtf8("frBoundarySettings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frBoundarySettings)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.flPlanningUnits = QtGui.QFormLayout()
        self.flPlanningUnits.setObjectName(_fromUtf8("flPlanningUnits"))
        self.lblPUStatus = QtGui.QLabel(self.frBoundarySettings)
        self.lblPUStatus.setMinimumSize(QtCore.QSize(279, 0))
        self.lblPUStatus.setObjectName(_fromUtf8("lblPUStatus"))
        self.flPlanningUnits.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblPUStatus)
        self.cbPUStatusField = QtGui.QComboBox(self.frBoundarySettings)
        self.cbPUStatusField.setObjectName(_fromUtf8("cbPUStatusField"))
        self.flPlanningUnits.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbPUStatusField)
        self.gridLayout_2.addLayout(self.flPlanningUnits, 2, 0, 1, 1)
        self.lblPlanningUnitParameters = QtGui.QLabel(self.frBoundarySettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlanningUnitParameters.setFont(font)
        self.lblPlanningUnitParameters.setObjectName(_fromUtf8("lblPlanningUnitParameters"))
        self.gridLayout_2.addWidget(self.lblPlanningUnitParameters, 1, 0, 1, 1)
        self.flPUBoundary = QtGui.QFormLayout()
        self.flPUBoundary.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flPUBoundary.setObjectName(_fromUtf8("flPUBoundary"))
        self.lblBoundaryMethod = QtGui.QLabel(self.frBoundarySettings)
        self.lblBoundaryMethod.setEnabled(True)
        self.lblBoundaryMethod.setObjectName(_fromUtf8("lblBoundaryMethod"))
        self.flPUBoundary.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblBoundaryMethod)
        self.cbBoundaryMethod = QtGui.QComboBox(self.frBoundarySettings)
        self.cbBoundaryMethod.setEnabled(True)
        self.cbBoundaryMethod.setObjectName(_fromUtf8("cbBoundaryMethod"))
        self.cbBoundaryMethod.addItem(_fromUtf8(""))
        self.cbBoundaryMethod.addItem(_fromUtf8(""))
        self.cbBoundaryMethod.addItem(_fromUtf8(""))
        self.flPUBoundary.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbBoundaryMethod)
        self.lblBoundaryField = QtGui.QLabel(self.frBoundarySettings)
        self.lblBoundaryField.setEnabled(True)
        self.lblBoundaryField.setObjectName(_fromUtf8("lblBoundaryField"))
        self.flPUBoundary.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblBoundaryField)
        self.cbBoundaryField = QtGui.QComboBox(self.frBoundarySettings)
        self.cbBoundaryField.setEnabled(True)
        self.cbBoundaryField.setObjectName(_fromUtf8("cbBoundaryField"))
        self.flPUBoundary.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbBoundaryField)
        self.lblBoundaryDiffs = QtGui.QLabel(self.frBoundarySettings)
        self.lblBoundaryDiffs.setEnabled(True)
        self.lblBoundaryDiffs.setObjectName(_fromUtf8("lblBoundaryDiffs"))
        self.flPUBoundary.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblBoundaryDiffs)
        self.cbBoundaryDiffs = QtGui.QComboBox(self.frBoundarySettings)
        self.cbBoundaryDiffs.setEnabled(True)
        self.cbBoundaryDiffs.setObjectName(_fromUtf8("cbBoundaryDiffs"))
        self.cbBoundaryDiffs.addItem(_fromUtf8(""))
        self.cbBoundaryDiffs.addItem(_fromUtf8(""))
        self.cbBoundaryDiffs.addItem(_fromUtf8(""))
        self.flPUBoundary.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbBoundaryDiffs)
        self.lblBoundaryEdge = QtGui.QLabel(self.frBoundarySettings)
        self.lblBoundaryEdge.setEnabled(True)
        self.lblBoundaryEdge.setObjectName(_fromUtf8("lblBoundaryEdge"))
        self.flPUBoundary.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblBoundaryEdge)
        self.cbBoundaryEdge = QtGui.QComboBox(self.frBoundarySettings)
        self.cbBoundaryEdge.setEnabled(True)
        self.cbBoundaryEdge.setObjectName(_fromUtf8("cbBoundaryEdge"))
        self.cbBoundaryEdge.addItem(_fromUtf8(""))
        self.cbBoundaryEdge.addItem(_fromUtf8(""))
        self.cbBoundaryEdge.addItem(_fromUtf8(""))
        self.flPUBoundary.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbBoundaryEdge)
        self.lblExportPrecision = QtGui.QLabel(self.frBoundarySettings)
        self.lblExportPrecision.setObjectName(_fromUtf8("lblExportPrecision"))
        self.flPUBoundary.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblExportPrecision)
        self.cbBoundaryExportPrecision = QtGui.QComboBox(self.frBoundarySettings)
        self.cbBoundaryExportPrecision.setObjectName(_fromUtf8("cbBoundaryExportPrecision"))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.cbBoundaryExportPrecision.addItem(_fromUtf8(""))
        self.flPUBoundary.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbBoundaryExportPrecision)
        self.gridLayout_2.addLayout(self.flPUBoundary, 4, 0, 1, 1)
        self.lblCommonBoundaryParameters = QtGui.QLabel(self.frBoundarySettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCommonBoundaryParameters.sizePolicy().hasHeightForWidth())
        self.lblCommonBoundaryParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCommonBoundaryParameters.setFont(font)
        self.lblCommonBoundaryParameters.setObjectName(_fromUtf8("lblCommonBoundaryParameters"))
        self.gridLayout_2.addWidget(self.lblCommonBoundaryParameters, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frBoundarySettings, 0, 0, 1, 1)
        self.frZonesBoundarySettings = QtGui.QFrame(self.tbBoundary)
        self.frZonesBoundarySettings.setEnabled(True)
        self.frZonesBoundarySettings.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZonesBoundarySettings.setFrameShadow(QtGui.QFrame.Plain)
        self.frZonesBoundarySettings.setObjectName(_fromUtf8("frZonesBoundarySettings"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frZonesBoundarySettings)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lblZoneBoundaryParameters = QtGui.QLabel(self.frZonesBoundarySettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZoneBoundaryParameters.sizePolicy().hasHeightForWidth())
        self.lblZoneBoundaryParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblZoneBoundaryParameters.setFont(font)
        self.lblZoneBoundaryParameters.setObjectName(_fromUtf8("lblZoneBoundaryParameters"))
        self.gridLayout_14.addWidget(self.lblZoneBoundaryParameters, 0, 0, 1, 1)
        self.flBoundaryZonesSettings = QtGui.QFormLayout()
        self.flBoundaryZonesSettings.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flBoundaryZonesSettings.setObjectName(_fromUtf8("flBoundaryZonesSettings"))
        self.lblPUZones = QtGui.QLabel(self.frZonesBoundarySettings)
        self.lblPUZones.setEnabled(True)
        self.lblPUZones.setObjectName(_fromUtf8("lblPUZones"))
        self.flBoundaryZonesSettings.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblPUZones)
        self.cbPUZones = QtGui.QComboBox(self.frZonesBoundarySettings)
        self.cbPUZones.setEnabled(True)
        self.cbPUZones.setObjectName(_fromUtf8("cbPUZones"))
        self.cbPUZones.addItem(_fromUtf8(""))
        self.flBoundaryZonesSettings.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbPUZones)
        self.lblPULocks = QtGui.QLabel(self.frZonesBoundarySettings)
        self.lblPULocks.setEnabled(True)
        self.lblPULocks.setObjectName(_fromUtf8("lblPULocks"))
        self.flBoundaryZonesSettings.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblPULocks)
        self.cbPULocks = QtGui.QComboBox(self.frZonesBoundarySettings)
        self.cbPULocks.setEnabled(True)
        self.cbPULocks.setObjectName(_fromUtf8("cbPULocks"))
        self.cbPULocks.addItem(_fromUtf8(""))
        self.flBoundaryZonesSettings.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbPULocks)
        self.gridLayout_14.addLayout(self.flBoundaryZonesSettings, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frZonesBoundarySettings, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 2, 0, 1, 1)
        self.hlBoundary = QtGui.QHBoxLayout()
        self.hlBoundary.setObjectName(_fromUtf8("hlBoundary"))
        self.pbEditBoundary = QtGui.QPushButton(self.tbBoundary)
        self.pbEditBoundary.setEnabled(True)
        self.pbEditBoundary.setObjectName(_fromUtf8("pbEditBoundary"))
        self.hlBoundary.addWidget(self.pbEditBoundary)
        self.pbSaveBoundary = QtGui.QPushButton(self.tbBoundary)
        self.pbSaveBoundary.setEnabled(False)
        self.pbSaveBoundary.setObjectName(_fromUtf8("pbSaveBoundary"))
        self.hlBoundary.addWidget(self.pbSaveBoundary)
        self.pbCancelBoundary = QtGui.QPushButton(self.tbBoundary)
        self.pbCancelBoundary.setEnabled(False)
        self.pbCancelBoundary.setObjectName(_fromUtf8("pbCancelBoundary"))
        self.hlBoundary.addWidget(self.pbCancelBoundary)
        self.gridLayout_10.addLayout(self.hlBoundary, 3, 0, 1, 1)
        self.twInputs.addTab(self.tbBoundary, _fromUtf8(""))
        self.tbOther = QtGui.QWidget()
        self.tbOther.setObjectName(_fromUtf8("tbOther"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tbOther)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.hlOtherButtons = QtGui.QHBoxLayout()
        self.hlOtherButtons.setObjectName(_fromUtf8("hlOtherButtons"))
        self.pbEditOther = QtGui.QPushButton(self.tbOther)
        self.pbEditOther.setObjectName(_fromUtf8("pbEditOther"))
        self.hlOtherButtons.addWidget(self.pbEditOther)
        self.pbSaveOther = QtGui.QPushButton(self.tbOther)
        self.pbSaveOther.setEnabled(False)
        self.pbSaveOther.setObjectName(_fromUtf8("pbSaveOther"))
        self.hlOtherButtons.addWidget(self.pbSaveOther)
        self.pbCancelOther = QtGui.QPushButton(self.tbOther)
        self.pbCancelOther.setEnabled(False)
        self.pbCancelOther.setObjectName(_fromUtf8("pbCancelOther"))
        self.hlOtherButtons.addWidget(self.pbCancelOther)
        self.gridLayout_6.addLayout(self.hlOtherButtons, 2, 0, 1, 1)
        self.frOther = QtGui.QFrame(self.tbOther)
        self.frOther.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frOther.sizePolicy().hasHeightForWidth())
        self.frOther.setSizePolicy(sizePolicy)
        self.frOther.setFrameShape(QtGui.QFrame.NoFrame)
        self.frOther.setFrameShadow(QtGui.QFrame.Plain)
        self.frOther.setObjectName(_fromUtf8("frOther"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frOther)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.vlProgramControlAnnealing = QtGui.QVBoxLayout()
        self.vlProgramControlAnnealing.setObjectName(_fromUtf8("vlProgramControlAnnealing"))
        self.lblProgramControlParameters = QtGui.QLabel(self.frOther)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProgramControlParameters.sizePolicy().hasHeightForWidth())
        self.lblProgramControlParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProgramControlParameters.setFont(font)
        self.lblProgramControlParameters.setObjectName(_fromUtf8("lblProgramControlParameters"))
        self.vlProgramControlAnnealing.addWidget(self.lblProgramControlParameters)
        self.flProgramControl = QtGui.QFormLayout()
        self.flProgramControl.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flProgramControl.setObjectName(_fromUtf8("flProgramControl"))
        self.lblRunMode = QtGui.QLabel(self.frOther)
        self.lblRunMode.setObjectName(_fromUtf8("lblRunMode"))
        self.flProgramControl.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblRunMode)
        self.cbRunMode = QtGui.QComboBox(self.frOther)
        self.cbRunMode.setObjectName(_fromUtf8("cbRunMode"))
        self.cbRunMode.addItem(_fromUtf8(""))
        self.cbRunMode.addItem(_fromUtf8(""))
        self.cbRunMode.addItem(_fromUtf8(""))
        self.cbRunMode.addItem(_fromUtf8(""))
        self.flProgramControl.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbRunMode)
        self.lblItImpType = QtGui.QLabel(self.frOther)
        self.lblItImpType.setObjectName(_fromUtf8("lblItImpType"))
        self.flProgramControl.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblItImpType)
        self.cbItImpType = QtGui.QComboBox(self.frOther)
        self.cbItImpType.setObjectName(_fromUtf8("cbItImpType"))
        self.cbItImpType.addItem(_fromUtf8(""))
        self.cbItImpType.addItem(_fromUtf8(""))
        self.cbItImpType.addItem(_fromUtf8(""))
        self.cbItImpType.addItem(_fromUtf8(""))
        self.cbItImpType.addItem(_fromUtf8(""))
        self.flProgramControl.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbItImpType)
        self.lblRandSeed = QtGui.QLabel(self.frOther)
        self.lblRandSeed.setObjectName(_fromUtf8("lblRandSeed"))
        self.flProgramControl.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblRandSeed)
        self.spbxRandSeed = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxRandSeed.setEnabled(True)
        self.spbxRandSeed.setDecimals(0)
        self.spbxRandSeed.setMinimum(-1.0)
        self.spbxRandSeed.setMaximum(1000000000.0)
        self.spbxRandSeed.setSingleStep(1.0)
        self.spbxRandSeed.setProperty("value", -1.0)
        self.spbxRandSeed.setObjectName(_fromUtf8("spbxRandSeed"))
        self.flProgramControl.setWidget(2, QtGui.QFormLayout.FieldRole, self.spbxRandSeed)
        self.vlProgramControlAnnealing.addLayout(self.flProgramControl)
        self.hlBelowProgramControl = QtGui.QFrame(self.frOther)
        self.hlBelowProgramControl.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowProgramControl.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowProgramControl.setObjectName(_fromUtf8("hlBelowProgramControl"))
        self.vlProgramControlAnnealing.addWidget(self.hlBelowProgramControl)
        self.lblAnnealingParameters = QtGui.QLabel(self.frOther)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAnnealingParameters.sizePolicy().hasHeightForWidth())
        self.lblAnnealingParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAnnealingParameters.setFont(font)
        self.lblAnnealingParameters.setObjectName(_fromUtf8("lblAnnealingParameters"))
        self.vlProgramControlAnnealing.addWidget(self.lblAnnealingParameters)
        self.flAnnealingParameters = QtGui.QFormLayout()
        self.flAnnealingParameters.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flAnnealingParameters.setObjectName(_fromUtf8("flAnnealingParameters"))
        self.lblStartTemp = QtGui.QLabel(self.frOther)
        self.lblStartTemp.setEnabled(True)
        self.lblStartTemp.setMinimumSize(QtCore.QSize(432, 0))
        self.lblStartTemp.setObjectName(_fromUtf8("lblStartTemp"))
        self.flAnnealingParameters.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblStartTemp)
        self.spbxStartTemp = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxStartTemp.setEnabled(True)
        self.spbxStartTemp.setDecimals(0)
        self.spbxStartTemp.setMinimum(-1.0)
        self.spbxStartTemp.setMaximum(1000000000.0)
        self.spbxStartTemp.setSingleStep(1.0)
        self.spbxStartTemp.setProperty("value", -1.0)
        self.spbxStartTemp.setObjectName(_fromUtf8("spbxStartTemp"))
        self.flAnnealingParameters.setWidget(0, QtGui.QFormLayout.FieldRole, self.spbxStartTemp)
        self.lblCoolFac = QtGui.QLabel(self.frOther)
        self.lblCoolFac.setEnabled(True)
        self.lblCoolFac.setObjectName(_fromUtf8("lblCoolFac"))
        self.flAnnealingParameters.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCoolFac)
        self.spbxCoolFac = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxCoolFac.setEnabled(True)
        self.spbxCoolFac.setMinimum(-1.0)
        self.spbxCoolFac.setMaximum(1.0)
        self.spbxCoolFac.setSingleStep(0.05)
        self.spbxCoolFac.setProperty("value", -1.0)
        self.spbxCoolFac.setObjectName(_fromUtf8("spbxCoolFac"))
        self.flAnnealingParameters.setWidget(1, QtGui.QFormLayout.FieldRole, self.spbxCoolFac)
        self.lblNumTemp = QtGui.QLabel(self.frOther)
        self.lblNumTemp.setObjectName(_fromUtf8("lblNumTemp"))
        self.flAnnealingParameters.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblNumTemp)
        self.spbxNumTemp = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxNumTemp.setEnabled(True)
        self.spbxNumTemp.setDecimals(0)
        self.spbxNumTemp.setMinimum(1.0)
        self.spbxNumTemp.setMaximum(1000000000.0)
        self.spbxNumTemp.setSingleStep(1000.0)
        self.spbxNumTemp.setProperty("value", 10000.0)
        self.spbxNumTemp.setObjectName(_fromUtf8("spbxNumTemp"))
        self.flAnnealingParameters.setWidget(2, QtGui.QFormLayout.FieldRole, self.spbxNumTemp)
        self.vlProgramControlAnnealing.addLayout(self.flAnnealingParameters)
        self.hlGeneralCostThreshold = QtGui.QFrame(self.frOther)
        self.hlGeneralCostThreshold.setFrameShape(QtGui.QFrame.HLine)
        self.hlGeneralCostThreshold.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlGeneralCostThreshold.setObjectName(_fromUtf8("hlGeneralCostThreshold"))
        self.vlProgramControlAnnealing.addWidget(self.hlGeneralCostThreshold)
        self.lblCostThresholdParameters = QtGui.QLabel(self.frOther)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCostThresholdParameters.sizePolicy().hasHeightForWidth())
        self.lblCostThresholdParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCostThresholdParameters.setFont(font)
        self.lblCostThresholdParameters.setObjectName(_fromUtf8("lblCostThresholdParameters"))
        self.vlProgramControlAnnealing.addWidget(self.lblCostThresholdParameters)
        self.flCostThresholdParameters = QtGui.QFormLayout()
        self.flCostThresholdParameters.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flCostThresholdParameters.setObjectName(_fromUtf8("flCostThresholdParameters"))
        self.lblCostThreshold = QtGui.QLabel(self.frOther)
        self.lblCostThreshold.setMinimumSize(QtCore.QSize(432, 0))
        self.lblCostThreshold.setObjectName(_fromUtf8("lblCostThreshold"))
        self.flCostThresholdParameters.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblCostThreshold)
        self.spbxCostThreshold = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxCostThreshold.setEnabled(True)
        self.spbxCostThreshold.setDecimals(2)
        self.spbxCostThreshold.setMinimum(0.0)
        self.spbxCostThreshold.setMaximum(1.0)
        self.spbxCostThreshold.setSingleStep(1e-06)
        self.spbxCostThreshold.setProperty("value", 0.0)
        self.spbxCostThreshold.setObjectName(_fromUtf8("spbxCostThreshold"))
        self.flCostThresholdParameters.setWidget(0, QtGui.QFormLayout.FieldRole, self.spbxCostThreshold)
        self.lblThreshPen1 = QtGui.QLabel(self.frOther)
        self.lblThreshPen1.setObjectName(_fromUtf8("lblThreshPen1"))
        self.flCostThresholdParameters.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblThreshPen1)
        self.spbxThreshPen1 = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxThreshPen1.setEnabled(True)
        self.spbxThreshPen1.setDecimals(2)
        self.spbxThreshPen1.setMinimum(0.0)
        self.spbxThreshPen1.setMaximum(1.0)
        self.spbxThreshPen1.setSingleStep(1e-06)
        self.spbxThreshPen1.setProperty("value", 0.0)
        self.spbxThreshPen1.setObjectName(_fromUtf8("spbxThreshPen1"))
        self.flCostThresholdParameters.setWidget(1, QtGui.QFormLayout.FieldRole, self.spbxThreshPen1)
        self.lblThreshPen2 = QtGui.QLabel(self.frOther)
        self.lblThreshPen2.setObjectName(_fromUtf8("lblThreshPen2"))
        self.flCostThresholdParameters.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblThreshPen2)
        self.spbxThreshPen2 = QtGui.QDoubleSpinBox(self.frOther)
        self.spbxThreshPen2.setEnabled(True)
        self.spbxThreshPen2.setDecimals(2)
        self.spbxThreshPen2.setMinimum(0.0)
        self.spbxThreshPen2.setMaximum(1.0)
        self.spbxThreshPen2.setSingleStep(1e-06)
        self.spbxThreshPen2.setProperty("value", 0.0)
        self.spbxThreshPen2.setObjectName(_fromUtf8("spbxThreshPen2"))
        self.flCostThresholdParameters.setWidget(2, QtGui.QFormLayout.FieldRole, self.spbxThreshPen2)
        self.vlProgramControlAnnealing.addLayout(self.flCostThresholdParameters)
        self.gridLayout_7.addLayout(self.vlProgramControlAnnealing, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frOther, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.twInputs.addTab(self.tbOther, _fromUtf8(""))
        self.tbOutput = QtGui.QWidget()
        self.tbOutput.setObjectName(_fromUtf8("tbOutput"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tbOutput)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.hlOutputButtons = QtGui.QHBoxLayout()
        self.hlOutputButtons.setObjectName(_fromUtf8("hlOutputButtons"))
        self.pbEditOutput = QtGui.QPushButton(self.tbOutput)
        self.pbEditOutput.setObjectName(_fromUtf8("pbEditOutput"))
        self.hlOutputButtons.addWidget(self.pbEditOutput)
        self.pbSaveOutput = QtGui.QPushButton(self.tbOutput)
        self.pbSaveOutput.setEnabled(False)
        self.pbSaveOutput.setObjectName(_fromUtf8("pbSaveOutput"))
        self.hlOutputButtons.addWidget(self.pbSaveOutput)
        self.pbCancelOutput = QtGui.QPushButton(self.tbOutput)
        self.pbCancelOutput.setEnabled(False)
        self.pbCancelOutput.setObjectName(_fromUtf8("pbCancelOutput"))
        self.hlOutputButtons.addWidget(self.pbCancelOutput)
        self.gridLayout_11.addLayout(self.hlOutputButtons, 4, 0, 1, 1)
        self.frOutputAll = QtGui.QFrame(self.tbOutput)
        self.frOutputAll.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frOutputAll.sizePolicy().hasHeightForWidth())
        self.frOutputAll.setSizePolicy(sizePolicy)
        self.frOutputAll.setFrameShape(QtGui.QFrame.NoFrame)
        self.frOutputAll.setFrameShadow(QtGui.QFrame.Plain)
        self.frOutputAll.setObjectName(_fromUtf8("frOutputAll"))
        self.gridLayout = QtGui.QGridLayout(self.frOutputAll)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblCommonOutput = QtGui.QLabel(self.frOutputAll)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCommonOutput.sizePolicy().hasHeightForWidth())
        self.lblCommonOutput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCommonOutput.setFont(font)
        self.lblCommonOutput.setObjectName(_fromUtf8("lblCommonOutput"))
        self.gridLayout.addWidget(self.lblCommonOutput, 0, 0, 1, 1)
        self.glOutputAll = QtGui.QGridLayout()
        self.glOutputAll.setObjectName(_fromUtf8("glOutputAll"))
        self.cbSaveScen = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveScen.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveScen.setObjectName(_fromUtf8("cbSaveScen"))
        self.cbSaveScen.addItem(_fromUtf8(""))
        self.cbSaveScen.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveScen, 2, 4, 1, 1)
        self.lblSaveScen = QtGui.QLabel(self.frOutputAll)
        self.lblSaveScen.setObjectName(_fromUtf8("lblSaveScen"))
        self.glOutputAll.addWidget(self.lblSaveScen, 2, 3, 1, 1)
        self.cbSaveLog = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveLog.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveLog.setObjectName(_fromUtf8("cbSaveLog"))
        self.cbSaveLog.addItem(_fromUtf8(""))
        self.cbSaveLog.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveLog, 1, 4, 1, 1)
        self.cbSaveBest = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveBest.setObjectName(_fromUtf8("cbSaveBest"))
        self.cbSaveBest.addItem(_fromUtf8(""))
        self.cbSaveBest.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveBest, 1, 2, 1, 1)
        self.lblSaveBest = QtGui.QLabel(self.frOutputAll)
        self.lblSaveBest.setObjectName(_fromUtf8("lblSaveBest"))
        self.glOutputAll.addWidget(self.lblSaveBest, 1, 0, 1, 1)
        self.lblSaveSumSoln = QtGui.QLabel(self.frOutputAll)
        self.lblSaveSumSoln.setObjectName(_fromUtf8("lblSaveSumSoln"))
        self.glOutputAll.addWidget(self.lblSaveSumSoln, 3, 0, 1, 1)
        self.cbSaveTargMet = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveTargMet.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveTargMet.setObjectName(_fromUtf8("cbSaveTargMet"))
        self.cbSaveTargMet.addItem(_fromUtf8(""))
        self.cbSaveTargMet.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveTargMet, 0, 4, 1, 1)
        self.cbSaveRun = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveRun.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbSaveRun.setMinimumContentsLength(1)
        self.cbSaveRun.setObjectName(_fromUtf8("cbSaveRun"))
        self.cbSaveRun.addItem(_fromUtf8(""))
        self.cbSaveRun.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveRun, 0, 2, 1, 1)
        self.lblSaveSum = QtGui.QLabel(self.frOutputAll)
        self.lblSaveSum.setObjectName(_fromUtf8("lblSaveSum"))
        self.glOutputAll.addWidget(self.lblSaveSum, 2, 0, 1, 1)
        self.cbSaveSumSoln = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveSumSoln.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveSumSoln.setObjectName(_fromUtf8("cbSaveSumSoln"))
        self.cbSaveSumSoln.addItem(_fromUtf8(""))
        self.cbSaveSumSoln.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveSumSoln, 3, 2, 1, 1)
        self.lblSaveTargMet = QtGui.QLabel(self.frOutputAll)
        self.lblSaveTargMet.setObjectName(_fromUtf8("lblSaveTargMet"))
        self.glOutputAll.addWidget(self.lblSaveTargMet, 0, 3, 1, 1)
        self.lblSaveRun = QtGui.QLabel(self.frOutputAll)
        self.lblSaveRun.setObjectName(_fromUtf8("lblSaveRun"))
        self.glOutputAll.addWidget(self.lblSaveRun, 0, 0, 1, 1)
        self.cbSaveSum = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveSum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveSum.setObjectName(_fromUtf8("cbSaveSum"))
        self.cbSaveSum.addItem(_fromUtf8(""))
        self.cbSaveSum.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveSum, 2, 2, 1, 1)
        self.lblSaveSolutionsMatrix = QtGui.QLabel(self.frOutputAll)
        self.lblSaveSolutionsMatrix.setObjectName(_fromUtf8("lblSaveSolutionsMatrix"))
        self.glOutputAll.addWidget(self.lblSaveSolutionsMatrix, 3, 3, 1, 1)
        self.lblSaveLog = QtGui.QLabel(self.frOutputAll)
        self.lblSaveLog.setObjectName(_fromUtf8("lblSaveLog"))
        self.glOutputAll.addWidget(self.lblSaveLog, 1, 3, 1, 1)
        self.cbSaveSolutionsMatrix = QtGui.QComboBox(self.frOutputAll)
        self.cbSaveSolutionsMatrix.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveSolutionsMatrix.setObjectName(_fromUtf8("cbSaveSolutionsMatrix"))
        self.cbSaveSolutionsMatrix.addItem(_fromUtf8(""))
        self.cbSaveSolutionsMatrix.addItem(_fromUtf8(""))
        self.glOutputAll.addWidget(self.cbSaveSolutionsMatrix, 3, 4, 1, 1)
        self.gridLayout.addLayout(self.glOutputAll, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frOutputAll, 0, 0, 1, 1)
        self.frMarxanOutput = QtGui.QFrame(self.tbOutput)
        self.frMarxanOutput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frMarxanOutput.sizePolicy().hasHeightForWidth())
        self.frMarxanOutput.setSizePolicy(sizePolicy)
        self.frMarxanOutput.setFrameShape(QtGui.QFrame.NoFrame)
        self.frMarxanOutput.setFrameShadow(QtGui.QFrame.Plain)
        self.frMarxanOutput.setObjectName(_fromUtf8("frMarxanOutput"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frMarxanOutput)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblMarxanOutputs = QtGui.QLabel(self.frMarxanOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMarxanOutputs.sizePolicy().hasHeightForWidth())
        self.lblMarxanOutputs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMarxanOutputs.setFont(font)
        self.lblMarxanOutputs.setObjectName(_fromUtf8("lblMarxanOutputs"))
        self.gridLayout_8.addWidget(self.lblMarxanOutputs, 0, 0, 1, 1)
        self.glOutputMarxan = QtGui.QGridLayout()
        self.glOutputMarxan.setObjectName(_fromUtf8("glOutputMarxan"))
        self.spbxSaveSnapFrequency = QtGui.QSpinBox(self.frMarxanOutput)
        self.spbxSaveSnapFrequency.setObjectName(_fromUtf8("spbxSaveSnapFrequency"))
        self.glOutputMarxan.addWidget(self.spbxSaveSnapFrequency, 2, 2, 1, 1)
        self.spbxSaveSnapSteps = QtGui.QSpinBox(self.frMarxanOutput)
        self.spbxSaveSnapSteps.setMaximum(1000000000)
        self.spbxSaveSnapSteps.setSingleStep(100)
        self.spbxSaveSnapSteps.setObjectName(_fromUtf8("spbxSaveSnapSteps"))
        self.glOutputMarxan.addWidget(self.spbxSaveSnapSteps, 0, 2, 1, 1)
        self.lblSaveSnapFrequency = QtGui.QLabel(self.frMarxanOutput)
        self.lblSaveSnapFrequency.setObjectName(_fromUtf8("lblSaveSnapFrequency"))
        self.glOutputMarxan.addWidget(self.lblSaveSnapFrequency, 2, 0, 1, 1)
        self.lblSaveSnapSteps = QtGui.QLabel(self.frMarxanOutput)
        self.lblSaveSnapSteps.setObjectName(_fromUtf8("lblSaveSnapSteps"))
        self.glOutputMarxan.addWidget(self.lblSaveSnapSteps, 0, 0, 1, 1)
        self.lblSaveSnapChanges = QtGui.QLabel(self.frMarxanOutput)
        self.lblSaveSnapChanges.setObjectName(_fromUtf8("lblSaveSnapChanges"))
        self.glOutputMarxan.addWidget(self.lblSaveSnapChanges, 1, 0, 1, 1)
        self.spbxSaveSnapChanges = QtGui.QSpinBox(self.frMarxanOutput)
        self.spbxSaveSnapChanges.setMaximum(1000000000)
        self.spbxSaveSnapChanges.setSingleStep(100)
        self.spbxSaveSnapChanges.setObjectName(_fromUtf8("spbxSaveSnapChanges"))
        self.glOutputMarxan.addWidget(self.spbxSaveSnapChanges, 1, 2, 1, 1)
        self.gridLayout_8.addLayout(self.glOutputMarxan, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frMarxanOutput, 1, 0, 1, 1)
        self.frZonesOutput = QtGui.QFrame(self.tbOutput)
        self.frZonesOutput.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frZonesOutput.sizePolicy().hasHeightForWidth())
        self.frZonesOutput.setSizePolicy(sizePolicy)
        self.frZonesOutput.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZonesOutput.setFrameShadow(QtGui.QFrame.Plain)
        self.frZonesOutput.setObjectName(_fromUtf8("frZonesOutput"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frZonesOutput)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblZonesOutput = QtGui.QLabel(self.frZonesOutput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZonesOutput.sizePolicy().hasHeightForWidth())
        self.lblZonesOutput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblZonesOutput.setFont(font)
        self.lblZonesOutput.setObjectName(_fromUtf8("lblZonesOutput"))
        self.gridLayout_9.addWidget(self.lblZonesOutput, 0, 0, 1, 1)
        self.glZonesOutput = QtGui.QGridLayout()
        self.glZonesOutput.setObjectName(_fromUtf8("glZonesOutput"))
        self.lblSaveAnnealTrace = QtGui.QLabel(self.frZonesOutput)
        self.lblSaveAnnealTrace.setObjectName(_fromUtf8("lblSaveAnnealTrace"))
        self.glZonesOutput.addWidget(self.lblSaveAnnealTrace, 0, 0, 1, 1)
        self.cbSaveItImpTrace = QtGui.QComboBox(self.frZonesOutput)
        self.cbSaveItImpTrace.setMaximumSize(QtCore.QSize(151, 16777215))
        self.cbSaveItImpTrace.setObjectName(_fromUtf8("cbSaveItImpTrace"))
        self.cbSaveItImpTrace.addItem(_fromUtf8(""))
        self.cbSaveItImpTrace.addItem(_fromUtf8(""))
        self.glZonesOutput.addWidget(self.cbSaveItImpTrace, 1, 1, 1, 1)
        self.lblTraceRows = QtGui.QLabel(self.frZonesOutput)
        self.lblTraceRows.setObjectName(_fromUtf8("lblTraceRows"))
        self.glZonesOutput.addWidget(self.lblTraceRows, 0, 2, 1, 1)
        self.cbSaveZoneConnectivitySum = QtGui.QComboBox(self.frZonesOutput)
        self.cbSaveZoneConnectivitySum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveZoneConnectivitySum.setObjectName(_fromUtf8("cbSaveZoneConnectivitySum"))
        self.cbSaveZoneConnectivitySum.addItem(_fromUtf8(""))
        self.cbSaveZoneConnectivitySum.addItem(_fromUtf8(""))
        self.glZonesOutput.addWidget(self.cbSaveZoneConnectivitySum, 1, 3, 1, 1)
        self.spbxTraceRows = QtGui.QSpinBox(self.frZonesOutput)
        self.spbxTraceRows.setMaximumSize(QtCore.QSize(150, 16777215))
        self.spbxTraceRows.setMaximum(1000000000)
        self.spbxTraceRows.setProperty("value", 1000)
        self.spbxTraceRows.setObjectName(_fromUtf8("spbxTraceRows"))
        self.glZonesOutput.addWidget(self.spbxTraceRows, 0, 3, 1, 1)
        self.lblSaveItImpTrace = QtGui.QLabel(self.frZonesOutput)
        self.lblSaveItImpTrace.setObjectName(_fromUtf8("lblSaveItImpTrace"))
        self.glZonesOutput.addWidget(self.lblSaveItImpTrace, 1, 0, 1, 1)
        self.cbSaveAnnealTrace = QtGui.QComboBox(self.frZonesOutput)
        self.cbSaveAnnealTrace.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveAnnealTrace.setObjectName(_fromUtf8("cbSaveAnnealTrace"))
        self.cbSaveAnnealTrace.addItem(_fromUtf8(""))
        self.cbSaveAnnealTrace.addItem(_fromUtf8(""))
        self.glZonesOutput.addWidget(self.cbSaveAnnealTrace, 0, 1, 1, 1)
        self.lblSaveZoneConnectivitySum = QtGui.QLabel(self.frZonesOutput)
        self.lblSaveZoneConnectivitySum.setObjectName(_fromUtf8("lblSaveZoneConnectivitySum"))
        self.glZonesOutput.addWidget(self.lblSaveZoneConnectivitySum, 1, 2, 1, 1)
        self.lblSavePenalty = QtGui.QLabel(self.frZonesOutput)
        self.lblSavePenalty.setObjectName(_fromUtf8("lblSavePenalty"))
        self.glZonesOutput.addWidget(self.lblSavePenalty, 2, 0, 1, 1)
        self.cbSavePenalty = QtGui.QComboBox(self.frZonesOutput)
        self.cbSavePenalty.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSavePenalty.setObjectName(_fromUtf8("cbSavePenalty"))
        self.cbSavePenalty.addItem(_fromUtf8(""))
        self.cbSavePenalty.addItem(_fromUtf8(""))
        self.glZonesOutput.addWidget(self.cbSavePenalty, 2, 1, 1, 1)
        self.lblSolutionsMatrixHeaders = QtGui.QLabel(self.frZonesOutput)
        self.lblSolutionsMatrixHeaders.setObjectName(_fromUtf8("lblSolutionsMatrixHeaders"))
        self.glZonesOutput.addWidget(self.lblSolutionsMatrixHeaders, 2, 2, 1, 1)
        self.cbSaveSolutionsMatrixHeaders = QtGui.QComboBox(self.frZonesOutput)
        self.cbSaveSolutionsMatrixHeaders.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbSaveSolutionsMatrixHeaders.setObjectName(_fromUtf8("cbSaveSolutionsMatrixHeaders"))
        self.cbSaveSolutionsMatrixHeaders.addItem(_fromUtf8(""))
        self.cbSaveSolutionsMatrixHeaders.addItem(_fromUtf8(""))
        self.glZonesOutput.addWidget(self.cbSaveSolutionsMatrixHeaders, 2, 3, 1, 1)
        self.gridLayout_9.addLayout(self.glZonesOutput, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frZonesOutput, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 3, 0, 1, 1)
        self.twInputs.addTab(self.tbOutput, _fromUtf8(""))
        self.tbExport = QtGui.QWidget()
        self.tbExport.setObjectName(_fromUtf8("tbExport"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tbExport)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.vlOperation = QtGui.QVBoxLayout()
        self.vlOperation.setSpacing(0)
        self.vlOperation.setObjectName(_fromUtf8("vlOperation"))
        self.lblInstructions = QtGui.QLabel(self.tbExport)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblInstructions.setFont(font)
        self.lblInstructions.setWordWrap(True)
        self.lblInstructions.setObjectName(_fromUtf8("lblInstructions"))
        self.vlOperation.addWidget(self.lblInstructions)
        self.lblActionsReport = QtGui.QLabel(self.tbExport)
        self.lblActionsReport.setObjectName(_fromUtf8("lblActionsReport"))
        self.vlOperation.addWidget(self.lblActionsReport)
        self.pteActionsReport = QtGui.QPlainTextEdit(self.tbExport)
        self.pteActionsReport.setReadOnly(True)
        self.pteActionsReport.setObjectName(_fromUtf8("pteActionsReport"))
        self.vlOperation.addWidget(self.pteActionsReport)
        self.hlProcess = QtGui.QHBoxLayout()
        self.hlProcess.setObjectName(_fromUtf8("hlProcess"))
        self.lblActions = QtGui.QLabel(self.tbExport)
        self.lblActions.setMinimumSize(QtCore.QSize(200, 0))
        self.lblActions.setObjectName(_fromUtf8("lblActions"))
        self.hlProcess.addWidget(self.lblActions)
        self.cbActions = QtGui.QComboBox(self.tbExport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbActions.sizePolicy().hasHeightForWidth())
        self.cbActions.setSizePolicy(sizePolicy)
        self.cbActions.setObjectName(_fromUtf8("cbActions"))
        self.hlProcess.addWidget(self.cbActions)
        self.vlOperation.addLayout(self.hlProcess)
        self.hlBelowProcess = QtGui.QFrame(self.tbExport)
        self.hlBelowProcess.setMinimumSize(QtCore.QSize(0, 10))
        self.hlBelowProcess.setFrameShape(QtGui.QFrame.HLine)
        self.hlBelowProcess.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlBelowProcess.setObjectName(_fromUtf8("hlBelowProcess"))
        self.vlOperation.addWidget(self.hlBelowProcess)
        self.lblActionParameters = QtGui.QLabel(self.tbExport)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblActionParameters.setFont(font)
        self.lblActionParameters.setObjectName(_fromUtf8("lblActionParameters"))
        self.vlOperation.addWidget(self.lblActionParameters)
        self.frImport = QtGui.QFrame(self.tbExport)
        self.frImport.setFrameShape(QtGui.QFrame.NoFrame)
        self.frImport.setFrameShadow(QtGui.QFrame.Plain)
        self.frImport.setObjectName(_fromUtf8("frImport"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frImport)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.cbImportField = QtGui.QComboBox(self.frImport)
        self.cbImportField.setMinimumSize(QtCore.QSize(175, 0))
        self.cbImportField.setObjectName(_fromUtf8("cbImportField"))
        self.gridLayout_17.addWidget(self.cbImportField, 6, 1, 1, 1)
        self.lblTextFile = QtGui.QLabel(self.frImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTextFile.sizePolicy().hasHeightForWidth())
        self.lblTextFile.setSizePolicy(sizePolicy)
        self.lblTextFile.setObjectName(_fromUtf8("lblTextFile"))
        self.gridLayout_17.addWidget(self.lblTextFile, 0, 0, 1, 1)
        self.lblNewField = QtGui.QLabel(self.frImport)
        self.lblNewField.setEnabled(True)
        self.lblNewField.setObjectName(_fromUtf8("lblNewField"))
        self.gridLayout_17.addWidget(self.lblNewField, 6, 2, 1, 1)
        self.leNewField = QtGui.QLineEdit(self.frImport)
        self.leNewField.setEnabled(True)
        self.leNewField.setMaxLength(10)
        self.leNewField.setReadOnly(False)
        self.leNewField.setObjectName(_fromUtf8("leNewField"))
        self.gridLayout_17.addWidget(self.leNewField, 6, 3, 1, 1)
        self.lblImportField = QtGui.QLabel(self.frImport)
        self.lblImportField.setObjectName(_fromUtf8("lblImportField"))
        self.gridLayout_17.addWidget(self.lblImportField, 6, 0, 1, 1)
        self.hlQGISProjectSelector = QtGui.QHBoxLayout()
        self.hlQGISProjectSelector.setSpacing(2)
        self.hlQGISProjectSelector.setObjectName(_fromUtf8("hlQGISProjectSelector"))
        self.leTextFile = QtGui.QLineEdit(self.frImport)
        self.leTextFile.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTextFile.sizePolicy().hasHeightForWidth())
        self.leTextFile.setSizePolicy(sizePolicy)
        self.leTextFile.setMinimumSize(QtCore.QSize(175, 0))
        self.leTextFile.setMaximumSize(QtCore.QSize(16777215, 100))
        self.leTextFile.setObjectName(_fromUtf8("leTextFile"))
        self.hlQGISProjectSelector.addWidget(self.leTextFile)
        self.tbGetTextFile = QtGui.QToolButton(self.frImport)
        self.tbGetTextFile.setEnabled(True)
        self.tbGetTextFile.setObjectName(_fromUtf8("tbGetTextFile"))
        self.hlQGISProjectSelector.addWidget(self.tbGetTextFile)
        self.gridLayout_17.addLayout(self.hlQGISProjectSelector, 0, 1, 1, 1)
        self.lblTextField = QtGui.QLabel(self.frImport)
        self.lblTextField.setEnabled(True)
        self.lblTextField.setObjectName(_fromUtf8("lblTextField"))
        self.gridLayout_17.addWidget(self.lblTextField, 0, 2, 1, 1)
        self.cbTextField = QtGui.QComboBox(self.frImport)
        self.cbTextField.setEnabled(True)
        self.cbTextField.setObjectName(_fromUtf8("cbTextField"))
        self.gridLayout_17.addWidget(self.cbTextField, 0, 3, 1, 1)
        self.vlOperation.addWidget(self.frImport)
        self.lnActionParameters = QtGui.QFrame(self.tbExport)
        self.lnActionParameters.setMinimumSize(QtCore.QSize(0, 10))
        self.lnActionParameters.setFrameShape(QtGui.QFrame.HLine)
        self.lnActionParameters.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnActionParameters.setObjectName(_fromUtf8("lnActionParameters"))
        self.vlOperation.addWidget(self.lnActionParameters)
        self.lblAllProgress = QtGui.QLabel(self.tbExport)
        self.lblAllProgress.setObjectName(_fromUtf8("lblAllProgress"))
        self.vlOperation.addWidget(self.lblAllProgress)
        self.pbAllProgress = QtGui.QProgressBar(self.tbExport)
        self.pbAllProgress.setProperty("value", 0)
        self.pbAllProgress.setObjectName(_fromUtf8("pbAllProgress"))
        self.vlOperation.addWidget(self.pbAllProgress)
        self.lblCurrentProgress = QtGui.QLabel(self.tbExport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCurrentProgress.sizePolicy().hasHeightForWidth())
        self.lblCurrentProgress.setSizePolicy(sizePolicy)
        self.lblCurrentProgress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblCurrentProgress.setObjectName(_fromUtf8("lblCurrentProgress"))
        self.vlOperation.addWidget(self.lblCurrentProgress)
        self.pbCurrentProgress = QtGui.QProgressBar(self.tbExport)
        self.pbCurrentProgress.setProperty("value", 0)
        self.pbCurrentProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbCurrentProgress.setTextVisible(True)
        self.pbCurrentProgress.setObjectName(_fromUtf8("pbCurrentProgress"))
        self.vlOperation.addWidget(self.pbCurrentProgress)
        self.lblStepProgress = QtGui.QLabel(self.tbExport)
        self.lblStepProgress.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lblStepProgress.setObjectName(_fromUtf8("lblStepProgress"))
        self.vlOperation.addWidget(self.lblStepProgress)
        self.pbStepProgress = QtGui.QProgressBar(self.tbExport)
        self.pbStepProgress.setProperty("value", 0)
        self.pbStepProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStepProgress.setTextVisible(True)
        self.pbStepProgress.setObjectName(_fromUtf8("pbStepProgress"))
        self.vlOperation.addWidget(self.pbStepProgress)
        self.gridLayout_13.addLayout(self.vlOperation, 0, 0, 1, 1)
        self.hlCalculationButtons = QtGui.QHBoxLayout()
        self.hlCalculationButtons.setObjectName(_fromUtf8("hlCalculationButtons"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlCalculationButtons.addItem(spacerItem5)
        self.pbActionReport = QtGui.QPushButton(self.tbExport)
        self.pbActionReport.setEnabled(True)
        self.pbActionReport.setObjectName(_fromUtf8("pbActionReport"))
        self.hlCalculationButtons.addWidget(self.pbActionReport)
        self.pbDoAction = QtGui.QPushButton(self.tbExport)
        self.pbDoAction.setEnabled(False)
        self.pbDoAction.setObjectName(_fromUtf8("pbDoAction"))
        self.hlCalculationButtons.addWidget(self.pbDoAction)
        self.pbCancelActions = QtGui.QPushButton(self.tbExport)
        self.pbCancelActions.setEnabled(False)
        self.pbCancelActions.setObjectName(_fromUtf8("pbCancelActions"))
        self.hlCalculationButtons.addWidget(self.pbCancelActions)
        self.gridLayout_13.addLayout(self.hlCalculationButtons, 1, 0, 1, 1)
        self.twInputs.addTab(self.tbExport, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.twInputs, 1, 0, 1, 2)

        self.retranslateUi(dlgConfigureRun)
        self.twInputs.setCurrentIndex(0)
        self.cbVerbosity.setCurrentIndex(0)
        self.cbBoundaryExportPrecision.setCurrentIndex(2)
        self.cbRunMode.setCurrentIndex(1)
        self.cbItImpType.setCurrentIndex(1)
        self.cbSaveScen.setCurrentIndex(1)
        self.cbSaveLog.setCurrentIndex(1)
        self.cbSaveBest.setCurrentIndex(1)
        self.cbSaveTargMet.setCurrentIndex(1)
        self.cbSaveRun.setCurrentIndex(1)
        self.cbSaveSumSoln.setCurrentIndex(1)
        self.cbSaveSum.setCurrentIndex(1)
        self.cbSaveSolutionsMatrix.setCurrentIndex(1)
        self.cbSaveItImpTrace.setCurrentIndex(1)
        self.cbSaveZoneConnectivitySum.setCurrentIndex(1)
        self.cbSaveAnnealTrace.setCurrentIndex(1)
        self.cbSavePenalty.setCurrentIndex(1)
        self.cbSaveSolutionsMatrixHeaders.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dlgConfigureRun)

    def retranslateUi(self, dlgConfigureRun):
        dlgConfigureRun.setWindowTitle(_translate("dlgConfigureRun", "QMZ Configure and Run. Current Project:", None))
        self.pbClose.setText(_translate("dlgConfigureRun", "Close", None))
        self.lblWorkingProject.setText(_translate("dlgConfigureRun", "Current Working Project:", None))
        self.lblAvailableZone.setText(_translate("dlgConfigureRun", "Available Zone", None))
        self.lblZonesParameters.setText(_translate("dlgConfigureRun", "Marxan with Zones Specific Parameters", None))
        self.lblGeneralParameters.setText(_translate("dlgConfigureRun", "Common Parameters", None))
        self.lblBLM.setText(_translate("dlgConfigureRun", "BLM: Boundary Layer Modifier", None))
        self.lblNumReps.setText(_translate("dlgConfigureRun", "NUMREPS: Number of times this scenario will be run", None))
        self.lblNumItns.setText(_translate("dlgConfigureRun", "NUMITNS: Number of simulated annealing interations in each run", None))
        self.lblProp.setText(_translate("dlgConfigureRun", "PROP: proportion of planning units randomly selected as \"in\" to start run", None))
        self.lblMissLevel.setText(_translate("dlgConfigureRun", "MISSLEVEL: Threshold for species (feature) targets to marked \"met\"", None))
        self.lblVerbosity.setText(_translate("dlgConfigureRun", "VERBOSITY: Set output verbosity", None))
        self.cbVerbosity.setItemText(0, _translate("dlgConfigureRun", "2-Intermediate", None))
        self.cbVerbosity.setItemText(1, _translate("dlgConfigureRun", "3-Verbose", None))
        self.pbEditGeneral.setText(_translate("dlgConfigureRun", "Edit", None))
        self.pbSaveGeneral.setText(_translate("dlgConfigureRun", "Save", None))
        self.pbCancelGeneral.setText(_translate("dlgConfigureRun", "Cancel", None))
        self.lblMarxanCalibration.setText(_translate("dlgConfigureRun", "Marxan Calibration Parameters", None))
        self.lblSPFMethod.setText(_translate("dlgConfigureRun", "SPF Method:", None))
        self.lblSPFStep.setText(_translate("dlgConfigureRun", "SPF Increment:", None))
        self.cbSPFMethod.setItemText(0, _translate("dlgConfigureRun", "Group Increment", None))
        self.cbSPFMethod.setItemText(1, _translate("dlgConfigureRun", "Individual Increment", None))
        self.cbSPFMethod.setItemText(2, _translate("dlgConfigureRun", "Increment All", None))
        self.lblSolutionTarget.setText(_translate("dlgConfigureRun", "Solution Target:", None))
        self.lblIterationList.setText(_translate("dlgConfigureRun", "Iterations:", None))
        self.leIterationList.setText(_translate("dlgConfigureRun", "1000000,5000000,10000000", None))
        self.twInputs.setTabText(self.twInputs.indexOf(self.tbGeneral), _translate("dlgConfigureRun", "General Parameters", None))
        self.lblPUStatus.setText(_translate("dlgConfigureRun", "Planning Unit Status Field:", None))
        self.lblPlanningUnitParameters.setText(_translate("dlgConfigureRun", "Planning Unit File Parameters", None))
        self.lblBoundaryMethod.setText(_translate("dlgConfigureRun", "Set boundary length using:", None))
        self.cbBoundaryMethod.setItemText(0, _translate("dlgConfigureRun", "Measure", None))
        self.cbBoundaryMethod.setItemText(1, _translate("dlgConfigureRun", "Measure x Field", None))
        self.cbBoundaryMethod.setItemText(2, _translate("dlgConfigureRun", "Field", None))
        self.lblBoundaryField.setText(_translate("dlgConfigureRun", "Boundary Length Field:", None))
        self.lblBoundaryDiffs.setText(_translate("dlgConfigureRun", "When boundary lengths differ use:", None))
        self.cbBoundaryDiffs.setItemText(0, _translate("dlgConfigureRun", "Mean", None))
        self.cbBoundaryDiffs.setItemText(1, _translate("dlgConfigureRun", "Maximum", None))
        self.cbBoundaryDiffs.setItemText(2, _translate("dlgConfigureRun", "Minimum", None))
        self.lblBoundaryEdge.setText(_translate("dlgConfigureRun", "Boundary of edge planning units should be:", None))
        self.cbBoundaryEdge.setItemText(0, _translate("dlgConfigureRun", "Full Value", None))
        self.cbBoundaryEdge.setItemText(1, _translate("dlgConfigureRun", "Half Value", None))
        self.cbBoundaryEdge.setItemText(2, _translate("dlgConfigureRun", "Zero", None))
        self.lblExportPrecision.setText(_translate("dlgConfigureRun", "Boundary file export precision:", None))
        self.cbBoundaryExportPrecision.setItemText(0, _translate("dlgConfigureRun", "Round to nearest 100 map units", None))
        self.cbBoundaryExportPrecision.setItemText(1, _translate("dlgConfigureRun", "Round to nearest 10 map units", None))
        self.cbBoundaryExportPrecision.setItemText(2, _translate("dlgConfigureRun", "Round to nearest 1 map unit", None))
        self.cbBoundaryExportPrecision.setItemText(3, _translate("dlgConfigureRun", "Round to nearest 0.1 of a map unit", None))
        self.cbBoundaryExportPrecision.setItemText(4, _translate("dlgConfigureRun", "Round to nearest 0.01 of a map unit", None))
        self.cbBoundaryExportPrecision.setItemText(5, _translate("dlgConfigureRun", "Round to nearest 0.001 of a map unit", None))
        self.cbBoundaryExportPrecision.setItemText(6, _translate("dlgConfigureRun", "Round to nearest 0.0001 of a map unit", None))
        self.cbBoundaryExportPrecision.setItemText(7, _translate("dlgConfigureRun", "Round to nearest 0.00001 of a map unit", None))
        self.lblCommonBoundaryParameters.setText(_translate("dlgConfigureRun", "Boundary File Parameters", None))
        self.lblZoneBoundaryParameters.setText(_translate("dlgConfigureRun", "Marxan with Zones Specific Boundary Parameters", None))
        self.lblPUZones.setText(_translate("dlgConfigureRun", "<html><head/><body><p>Planning Unit Zone Field (restrict some PUs to 2 or more zones):</p></body></html>", None))
        self.cbPUZones.setItemText(0, _translate("dlgConfigureRun", "Not Selected", None))
        self.lblPULocks.setText(_translate("dlgConfigureRun", "<html><head/><body><p>Planning Unit Lock Field (restrict some PUs to one zone):</p></body></html>", None))
        self.cbPULocks.setItemText(0, _translate("dlgConfigureRun", "Not Selected", None))
        self.pbEditBoundary.setText(_translate("dlgConfigureRun", "Edit", None))
        self.pbSaveBoundary.setText(_translate("dlgConfigureRun", "Save", None))
        self.pbCancelBoundary.setText(_translate("dlgConfigureRun", "Cancel", None))
        self.twInputs.setTabText(self.twInputs.indexOf(self.tbBoundary), _translate("dlgConfigureRun", "Planning Unit && Boundary Parameters", None))
        self.pbEditOther.setText(_translate("dlgConfigureRun", "Edit", None))
        self.pbSaveOther.setText(_translate("dlgConfigureRun", "Save", None))
        self.pbCancelOther.setText(_translate("dlgConfigureRun", "Cancel", None))
        self.lblProgramControlParameters.setText(_translate("dlgConfigureRun", "Program Control Parameters", None))
        self.lblRunMode.setText(_translate("dlgConfigureRun", "RUNMODE: Run mode", None))
        self.cbRunMode.setItemText(0, _translate("dlgConfigureRun", "-1-No methods", None))
        self.cbRunMode.setItemText(1, _translate("dlgConfigureRun", "1-Annealing & Iterative Improvement", None))
        self.cbRunMode.setItemText(2, _translate("dlgConfigureRun", "4-Iterative Improvement Only", None))
        self.cbRunMode.setItemText(3, _translate("dlgConfigureRun", "6-Annealing Only", None))
        self.lblItImpType.setText(_translate("dlgConfigureRun", "ITIMPTYPE: Iterative improvement type", None))
        self.cbItImpType.setItemText(0, _translate("dlgConfigureRun", "-1-Don\'t use", None))
        self.cbItImpType.setItemText(1, _translate("dlgConfigureRun", "0-Normal", None))
        self.cbItImpType.setItemText(2, _translate("dlgConfigureRun", "1-Two Step", None))
        self.cbItImpType.setItemText(3, _translate("dlgConfigureRun", "2-Swap", None))
        self.cbItImpType.setItemText(4, _translate("dlgConfigureRun", "3-Normal& Two Step", None))
        self.lblRandSeed.setText(_translate("dlgConfigureRun", "RANDSEED: Seed for random number generation (-1 to use clock)", None))
        self.lblAnnealingParameters.setText(_translate("dlgConfigureRun", "Annealing Parameters", None))
        self.lblStartTemp.setText(_translate("dlgConfigureRun", "STARTTEMP: Starting temperature (-1 for adaptive annealing)", None))
        self.lblCoolFac.setText(_translate("dlgConfigureRun", "COOLFAC: Cooling factor for annealing", None))
        self.lblNumTemp.setText(_translate("dlgConfigureRun", "NUMTEMP: Number of temperature decreases", None))
        self.lblCostThresholdParameters.setText(_translate("dlgConfigureRun", "Cost Threshold Parameters", None))
        self.lblCostThreshold.setText(_translate("dlgConfigureRun", "COSTTHRESH: Cost threshold", None))
        self.lblThreshPen1.setText(_translate("dlgConfigureRun", "THRESHPEN1: Threshold Penalty A", None))
        self.lblThreshPen2.setText(_translate("dlgConfigureRun", "THRESHPEN2: Threshold Penalty B", None))
        self.twInputs.setTabText(self.twInputs.indexOf(self.tbOther), _translate("dlgConfigureRun", "Other Parameters", None))
        self.pbEditOutput.setText(_translate("dlgConfigureRun", "Edit", None))
        self.pbSaveOutput.setText(_translate("dlgConfigureRun", "Save", None))
        self.pbCancelOutput.setText(_translate("dlgConfigureRun", "Cancel", None))
        self.lblCommonOutput.setText(_translate("dlgConfigureRun", "Common Outputs", None))
        self.cbSaveScen.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveScen.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveScen.setText(_translate("dlgConfigureRun", "SAVESCEN:\n"
"Save scenario info", None))
        self.cbSaveLog.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveLog.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.cbSaveBest.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveBest.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveBest.setText(_translate("dlgConfigureRun", "SAVEBEST:\n"
"Save best run?", None))
        self.lblSaveSumSoln.setText(_translate("dlgConfigureRun", "SAVESUMSOLN:\n"
"Save frequency info", None))
        self.cbSaveTargMet.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveTargMet.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.cbSaveRun.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveRun.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveSum.setText(_translate("dlgConfigureRun", "SAVESUM:\n"
"Save summary info", None))
        self.cbSaveSumSoln.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveSumSoln.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveTargMet.setText(_translate("dlgConfigureRun", "SAVETARGMET:\n"
"Save targets met info", None))
        self.lblSaveRun.setText(_translate("dlgConfigureRun", "SAVERUN: \n"
"Save each run?", None))
        self.cbSaveSum.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveSum.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveSolutionsMatrix.setText(_translate("dlgConfigureRun", "SAVESOLUTIONSMATRIX:\n"
"Create output_solutionsmatrix.csv", None))
        self.lblSaveLog.setText(_translate("dlgConfigureRun", "SAVELOG:\n"
"Save log file", None))
        self.cbSaveSolutionsMatrix.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveSolutionsMatrix.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblMarxanOutputs.setText(_translate("dlgConfigureRun", "Standard Marxan Outputs", None))
        self.lblSaveSnapFrequency.setText(_translate("dlgConfigureRun", "SAVESNAPFREQUENCY: Frequency of snapshots", None))
        self.lblSaveSnapSteps.setText(_translate("dlgConfigureRun", "SAVESNAPSTEPS: Save snapshots each n steps", None))
        self.lblSaveSnapChanges.setText(_translate("dlgConfigureRun", "SAVESNAPCHANGES: Save snapshot each n changes", None))
        self.lblZonesOutput.setText(_translate("dlgConfigureRun", "Marxan with Zones Outputs", None))
        self.lblSaveAnnealTrace.setText(_translate("dlgConfigureRun", "SAVEANNEALINGTRACE:\n"
"Report on annealing", None))
        self.cbSaveItImpTrace.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveItImpTrace.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblTraceRows.setText(_translate("dlgConfigureRun", "Trace Rows:\n"
"Number of rows to report", None))
        self.cbSaveZoneConnectivitySum.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveZoneConnectivitySum.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveItImpTrace.setText(_translate("dlgConfigureRun", "SAVEITIMPTRACE:\n"
"Report on interative improvement", None))
        self.cbSaveAnnealTrace.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSaveAnnealTrace.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSaveZoneConnectivitySum.setText(_translate("dlgConfigureRun", "SAVEZONECONNECTIVITYSUM:\n"
"Zone connectivity sum", None))
        self.lblSavePenalty.setText(_translate("dlgConfigureRun", "SAVEPENALTY:\n"
"Save computed feature penaties", None))
        self.cbSavePenalty.setItemText(0, _translate("dlgConfigureRun", "2-dat file", None))
        self.cbSavePenalty.setItemText(1, _translate("dlgConfigureRun", "3-CSV", None))
        self.lblSolutionsMatrixHeaders.setText(_translate("dlgConfigureRun", "SOLUTIONSMATRIXHEADERS:\n"
"Include header row", None))
        self.cbSaveSolutionsMatrixHeaders.setItemText(0, _translate("dlgConfigureRun", "0-No", None))
        self.cbSaveSolutionsMatrixHeaders.setItemText(1, _translate("dlgConfigureRun", "1-Yes", None))
        self.twInputs.setTabText(self.twInputs.indexOf(self.tbOutput), _translate("dlgConfigureRun", "Analysis Outputs", None))
        self.lblInstructions.setText(_translate("dlgConfigureRun", "<html><head/><body><p>Run report to learn what can and needs to be done</p></body></html>", None))
        self.lblActionsReport.setText(_translate("dlgConfigureRun", "Required and Possible Actions:", None))
        self.lblActions.setText(_translate("dlgConfigureRun", "Select Action:", None))
        self.lblActionParameters.setText(_translate("dlgConfigureRun", "Action Parameters", None))
        self.lblTextFile.setText(_translate("dlgConfigureRun", "Source Text File:", None))
        self.lblNewField.setText(_translate("dlgConfigureRun", "New Field Name:", None))
        self.lblImportField.setText(_translate("dlgConfigureRun", "Import Into Field:", None))
        self.tbGetTextFile.setText(_translate("dlgConfigureRun", "...", None))
        self.lblTextField.setText(_translate("dlgConfigureRun", "Text Id Field:", None))
        self.lblAllProgress.setText(_translate("dlgConfigureRun", "Overall Progress:", None))
        self.lblCurrentProgress.setText(_translate("dlgConfigureRun", "Current Process:", None))
        self.lblStepProgress.setText(_translate("dlgConfigureRun", "Current Step:", None))
        self.pbActionReport.setText(_translate("dlgConfigureRun", "Report", None))
        self.pbDoAction.setText(_translate("dlgConfigureRun", "Perform Action", None))
        self.pbCancelActions.setText(_translate("dlgConfigureRun", "Cancel", None))
        self.twInputs.setTabText(self.twInputs.indexOf(self.tbExport), _translate("dlgConfigureRun", "Export and Run", None))

