# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mkgrid.ui'
#
# Created: Sun Oct 26 08:50:29 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgMakeGrid(object):
    def setupUi(self, dlgMakeGrid):
        dlgMakeGrid.setObjectName(_fromUtf8("dlgMakeGrid"))
        dlgMakeGrid.setWindowModality(QtCore.Qt.NonModal)
        dlgMakeGrid.resize(725, 470)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgMakeGrid.sizePolicy().hasHeightForWidth())
        dlgMakeGrid.setSizePolicy(sizePolicy)
        dlgMakeGrid.setMinimumSize(QtCore.QSize(725, 470))
        dlgMakeGrid.setMaximumSize(QtCore.QSize(725, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/qmz_mkgrid.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgMakeGrid.setWindowIcon(icon)
        dlgMakeGrid.setSizeGripEnabled(False)
        self.gridLayout_2 = QtGui.QGridLayout(dlgMakeGrid)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblGridExtent = QtGui.QLabel(dlgMakeGrid)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGridExtent.setFont(font)
        self.lblGridExtent.setObjectName(_fromUtf8("lblGridExtent"))
        self.verticalLayout_2.addWidget(self.lblGridExtent)
        self.cbLayer = QtGui.QComboBox(dlgMakeGrid)
        self.cbLayer.setObjectName(_fromUtf8("cbLayer"))
        self.verticalLayout_2.addWidget(self.cbLayer)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tbLayerExtents = QtGui.QToolButton(dlgMakeGrid)
        self.tbLayerExtents.setMinimumSize(QtCore.QSize(0, 30))
        self.tbLayerExtents.setObjectName(_fromUtf8("tbLayerExtents"))
        self.horizontalLayout.addWidget(self.tbLayerExtents)
        self.tbCanvasExtents = QtGui.QToolButton(dlgMakeGrid)
        self.tbCanvasExtents.setMinimumSize(QtCore.QSize(0, 30))
        self.tbCanvasExtents.setObjectName(_fromUtf8("tbCanvasExtents"))
        self.horizontalLayout.addWidget(self.tbCanvasExtents)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblXMax = QtGui.QLabel(dlgMakeGrid)
        self.lblXMax.setEnabled(True)
        self.lblXMax.setObjectName(_fromUtf8("lblXMax"))
        self.gridLayout.addWidget(self.lblXMax, 1, 0, 1, 1)
        self.spnXMin = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnXMin.setMinimum(-1000000000.0)
        self.spnXMin.setMaximum(1000000000.0)
        self.spnXMin.setObjectName(_fromUtf8("spnXMin"))
        self.gridLayout.addWidget(self.spnXMin, 0, 1, 1, 1)
        self.lblXMin = QtGui.QLabel(dlgMakeGrid)
        self.lblXMin.setEnabled(True)
        self.lblXMin.setObjectName(_fromUtf8("lblXMin"))
        self.gridLayout.addWidget(self.lblXMin, 0, 0, 1, 1)
        self.spnXMax = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnXMax.setMinimum(-1000000000.0)
        self.spnXMax.setMaximum(1000000000.0)
        self.spnXMax.setObjectName(_fromUtf8("spnXMax"))
        self.gridLayout.addWidget(self.spnXMax, 1, 1, 1, 1)
        self.lblYMin = QtGui.QLabel(dlgMakeGrid)
        self.lblYMin.setEnabled(True)
        self.lblYMin.setObjectName(_fromUtf8("lblYMin"))
        self.gridLayout.addWidget(self.lblYMin, 0, 2, 1, 1)
        self.spnYMin = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnYMin.setMinimum(-1000000000.0)
        self.spnYMin.setMaximum(1000000000.0)
        self.spnYMin.setObjectName(_fromUtf8("spnYMin"))
        self.gridLayout.addWidget(self.spnYMin, 0, 3, 1, 1)
        self.lblYMax = QtGui.QLabel(dlgMakeGrid)
        self.lblYMax.setEnabled(True)
        self.lblYMax.setObjectName(_fromUtf8("lblYMax"))
        self.gridLayout.addWidget(self.lblYMax, 1, 2, 1, 1)
        self.spnYMax = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnYMax.setMinimum(-1000000000.0)
        self.spnYMax.setMaximum(1000000000.0)
        self.spnYMax.setObjectName(_fromUtf8("spnYMax"))
        self.gridLayout.addWidget(self.spnYMax, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(dlgMakeGrid)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 0, 1, 1, 1)
        self.vlPUShapeAndFile = QtGui.QVBoxLayout()
        self.vlPUShapeAndFile.setObjectName(_fromUtf8("vlPUShapeAndFile"))
        self.lblPUShape = QtGui.QLabel(dlgMakeGrid)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPUShape.setFont(font)
        self.lblPUShape.setObjectName(_fromUtf8("lblPUShape"))
        self.vlPUShapeAndFile.addWidget(self.lblPUShape)
        self.grpBoxShape = QtGui.QGroupBox(dlgMakeGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBoxShape.sizePolicy().hasHeightForWidth())
        self.grpBoxShape.setSizePolicy(sizePolicy)
        self.grpBoxShape.setTitle(_fromUtf8(""))
        self.grpBoxShape.setObjectName(_fromUtf8("grpBoxShape"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.grpBoxShape)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 295, 28))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rdoHexagon = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.rdoHexagon.setChecked(True)
        self.rdoHexagon.setObjectName(_fromUtf8("rdoHexagon"))
        self.horizontalLayout_3.addWidget(self.rdoHexagon)
        self.rdoSquare = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.rdoSquare.setCheckable(True)
        self.rdoSquare.setChecked(False)
        self.rdoSquare.setObjectName(_fromUtf8("rdoSquare"))
        self.horizontalLayout_3.addWidget(self.rdoSquare)
        self.vlPUShapeAndFile.addWidget(self.grpBoxShape)
        self.grpBoxSize = QtGui.QGroupBox(dlgMakeGrid)
        self.grpBoxSize.setTitle(_fromUtf8(""))
        self.grpBoxSize.setObjectName(_fromUtf8("grpBoxSize"))
        self.layoutWidget = QtGui.QWidget(self.grpBoxSize)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 295, 34))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rdoArea = QtGui.QRadioButton(self.layoutWidget)
        self.rdoArea.setChecked(True)
        self.rdoArea.setObjectName(_fromUtf8("rdoArea"))
        self.horizontalLayout_2.addWidget(self.rdoArea)
        self.rdoSideLength = QtGui.QRadioButton(self.layoutWidget)
        self.rdoSideLength.setChecked(False)
        self.rdoSideLength.setObjectName(_fromUtf8("rdoSideLength"))
        self.horizontalLayout_2.addWidget(self.rdoSideLength)
        self.vlPUShapeAndFile.addWidget(self.grpBoxSize)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblArea = QtGui.QLabel(dlgMakeGrid)
        self.lblArea.setEnabled(True)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.horizontalLayout_4.addWidget(self.lblArea)
        self.spnUnitArea = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnUnitArea.setEnabled(True)
        self.spnUnitArea.setDecimals(4)
        self.spnUnitArea.setMinimum(0.0001)
        self.spnUnitArea.setMaximum(1000000000.0)
        self.spnUnitArea.setSingleStep(100.0)
        self.spnUnitArea.setProperty("value", 1000.0)
        self.spnUnitArea.setObjectName(_fromUtf8("spnUnitArea"))
        self.horizontalLayout_4.addWidget(self.spnUnitArea)
        self.vlPUShapeAndFile.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblLength = QtGui.QLabel(dlgMakeGrid)
        self.lblLength.setEnabled(False)
        self.lblLength.setObjectName(_fromUtf8("lblLength"))
        self.horizontalLayout_5.addWidget(self.lblLength)
        self.spnSideLength = QtGui.QDoubleSpinBox(dlgMakeGrid)
        self.spnSideLength.setEnabled(False)
        self.spnSideLength.setDecimals(4)
        self.spnSideLength.setMinimum(0.0001)
        self.spnSideLength.setMaximum(1000000000.0)
        self.spnSideLength.setSingleStep(10.0)
        self.spnSideLength.setProperty("value", 100.0)
        self.spnSideLength.setObjectName(_fromUtf8("spnSideLength"))
        self.horizontalLayout_5.addWidget(self.spnSideLength)
        self.vlPUShapeAndFile.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.vlPUShapeAndFile, 0, 2, 1, 1)
        self.line_3 = QtGui.QFrame(dlgMakeGrid)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 1, 3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hlPUNumber = QtGui.QHBoxLayout()
        self.hlPUNumber.setObjectName(_fromUtf8("hlPUNumber"))
        self.chbxLimitGrid = QtGui.QCheckBox(dlgMakeGrid)
        self.chbxLimitGrid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbxLimitGrid.setObjectName(_fromUtf8("chbxLimitGrid"))
        self.hlPUNumber.addWidget(self.chbxLimitGrid)
        self.chbxRasterClip = QtGui.QCheckBox(dlgMakeGrid)
        self.chbxRasterClip.setObjectName(_fromUtf8("chbxRasterClip"))
        self.hlPUNumber.addWidget(self.chbxRasterClip)
        self.line_2 = QtGui.QFrame(dlgMakeGrid)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.hlPUNumber.addWidget(self.line_2)
        self.lblPUNumber = QtGui.QLabel(dlgMakeGrid)
        self.lblPUNumber.setObjectName(_fromUtf8("lblPUNumber"))
        self.hlPUNumber.addWidget(self.lblPUNumber)
        self.lePUNumber = QtGui.QLineEdit(dlgMakeGrid)
        self.lePUNumber.setEnabled(False)
        self.lePUNumber.setAcceptDrops(True)
        self.lePUNumber.setReadOnly(True)
        self.lePUNumber.setObjectName(_fromUtf8("lePUNumber"))
        self.hlPUNumber.addWidget(self.lePUNumber)
        self.verticalLayout.addLayout(self.hlPUNumber)
        self.lblFileName = QtGui.QLabel(dlgMakeGrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFileName.sizePolicy().hasHeightForWidth())
        self.lblFileName.setSizePolicy(sizePolicy)
        self.lblFileName.setObjectName(_fromUtf8("lblFileName"))
        self.verticalLayout.addWidget(self.lblFileName)
        self.hlFile = QtGui.QHBoxLayout()
        self.hlFile.setObjectName(_fromUtf8("hlFile"))
        self.leFile = QtGui.QLineEdit(dlgMakeGrid)
        self.leFile.setReadOnly(True)
        self.leFile.setObjectName(_fromUtf8("leFile"))
        self.hlFile.addWidget(self.leFile)
        self.tbOutputFile = QtGui.QToolButton(dlgMakeGrid)
        self.tbOutputFile.setObjectName(_fromUtf8("tbOutputFile"))
        self.hlFile.addWidget(self.tbOutputFile)
        self.verticalLayout.addLayout(self.hlFile)
        self.line = QtGui.QFrame(dlgMakeGrid)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.lblProgress = QtGui.QLabel(dlgMakeGrid)
        self.lblProgress.setObjectName(_fromUtf8("lblProgress"))
        self.verticalLayout.addWidget(self.lblProgress)
        self.pbCreationProgress = QtGui.QProgressBar(dlgMakeGrid)
        self.pbCreationProgress.setProperty("value", 0)
        self.pbCreationProgress.setObjectName(_fromUtf8("pbCreationProgress"))
        self.verticalLayout.addWidget(self.pbCreationProgress)
        self.pbStepProgress = QtGui.QProgressBar(dlgMakeGrid)
        self.pbStepProgress.setProperty("value", 0)
        self.pbStepProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStepProgress.setTextVisible(True)
        self.pbStepProgress.setObjectName(_fromUtf8("pbStepProgress"))
        self.verticalLayout.addWidget(self.pbStepProgress)
        self.hlControls = QtGui.QHBoxLayout()
        self.hlControls.setObjectName(_fromUtf8("hlControls"))
        self.pbCreateGrid = QtGui.QPushButton(dlgMakeGrid)
        self.pbCreateGrid.setEnabled(False)
        self.pbCreateGrid.setObjectName(_fromUtf8("pbCreateGrid"))
        self.hlControls.addWidget(self.pbCreateGrid)
        self.pbCancel = QtGui.QPushButton(dlgMakeGrid)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.hlControls.addWidget(self.pbCancel)
        self.pbClose = QtGui.QPushButton(dlgMakeGrid)
        self.pbClose.setEnabled(True)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hlControls.addWidget(self.pbClose)
        self.verticalLayout.addLayout(self.hlControls)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 3)

        self.retranslateUi(dlgMakeGrid)
        QtCore.QObject.connect(self.pbClose, QtCore.SIGNAL(_fromUtf8("clicked()")), dlgMakeGrid.close)
        QtCore.QMetaObject.connectSlotsByName(dlgMakeGrid)
        dlgMakeGrid.setTabOrder(self.cbLayer, self.tbLayerExtents)
        dlgMakeGrid.setTabOrder(self.tbLayerExtents, self.tbCanvasExtents)
        dlgMakeGrid.setTabOrder(self.tbCanvasExtents, self.spnXMin)
        dlgMakeGrid.setTabOrder(self.spnXMin, self.spnXMax)
        dlgMakeGrid.setTabOrder(self.spnXMax, self.spnYMin)
        dlgMakeGrid.setTabOrder(self.spnYMin, self.spnYMax)
        dlgMakeGrid.setTabOrder(self.spnYMax, self.rdoHexagon)
        dlgMakeGrid.setTabOrder(self.rdoHexagon, self.rdoSquare)
        dlgMakeGrid.setTabOrder(self.rdoSquare, self.rdoArea)
        dlgMakeGrid.setTabOrder(self.rdoArea, self.rdoSideLength)
        dlgMakeGrid.setTabOrder(self.rdoSideLength, self.spnUnitArea)
        dlgMakeGrid.setTabOrder(self.spnUnitArea, self.spnSideLength)
        dlgMakeGrid.setTabOrder(self.spnSideLength, self.chbxLimitGrid)
        dlgMakeGrid.setTabOrder(self.chbxLimitGrid, self.chbxRasterClip)
        dlgMakeGrid.setTabOrder(self.chbxRasterClip, self.lePUNumber)
        dlgMakeGrid.setTabOrder(self.lePUNumber, self.leFile)
        dlgMakeGrid.setTabOrder(self.leFile, self.tbOutputFile)
        dlgMakeGrid.setTabOrder(self.tbOutputFile, self.pbCreateGrid)
        dlgMakeGrid.setTabOrder(self.pbCreateGrid, self.pbCancel)
        dlgMakeGrid.setTabOrder(self.pbCancel, self.pbClose)

    def retranslateUi(self, dlgMakeGrid):
        dlgMakeGrid.setWindowTitle(QtGui.QApplication.translate("dlgMakeGrid", "Generate Planning Unit Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGridExtent.setText(QtGui.QApplication.translate("dlgMakeGrid", "Planning Unit Grid Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLayerExtents.setText(QtGui.QApplication.translate("dlgMakeGrid", "Set extents from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCanvasExtents.setText(QtGui.QApplication.translate("dlgMakeGrid", "Set extents from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblXMax.setText(QtGui.QApplication.translate("dlgMakeGrid", "X Max", None, QtGui.QApplication.UnicodeUTF8))
        self.lblXMin.setText(QtGui.QApplication.translate("dlgMakeGrid", "X Min", None, QtGui.QApplication.UnicodeUTF8))
        self.lblYMin.setText(QtGui.QApplication.translate("dlgMakeGrid", "Y Min", None, QtGui.QApplication.UnicodeUTF8))
        self.lblYMax.setText(QtGui.QApplication.translate("dlgMakeGrid", "Y Max", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPUShape.setText(QtGui.QApplication.translate("dlgMakeGrid", "Planning Unit Size & Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoHexagon.setText(QtGui.QApplication.translate("dlgMakeGrid", "Hexagons", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSquare.setText(QtGui.QApplication.translate("dlgMakeGrid", "Squares", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoArea.setText(QtGui.QApplication.translate("dlgMakeGrid", "Unit Area", None, QtGui.QApplication.UnicodeUTF8))
        self.rdoSideLength.setText(QtGui.QApplication.translate("dlgMakeGrid", "Side Length", None, QtGui.QApplication.UnicodeUTF8))
        self.lblArea.setText(QtGui.QApplication.translate("dlgMakeGrid", "Unit Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLength.setText(QtGui.QApplication.translate("dlgMakeGrid", "Side Length", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxLimitGrid.setText(QtGui.QApplication.translate("dlgMakeGrid", "Limit to extents layer intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxRasterClip.setText(QtGui.QApplication.translate("dlgMakeGrid", "Use raster estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPUNumber.setText(QtGui.QApplication.translate("dlgMakeGrid", "Cell Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFileName.setText(QtGui.QApplication.translate("dlgMakeGrid", "Output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOutputFile.setText(QtGui.QApplication.translate("dlgMakeGrid", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProgress.setText(QtGui.QApplication.translate("dlgMakeGrid", "Creation Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCreateGrid.setText(QtGui.QApplication.translate("dlgMakeGrid", "Create Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("dlgMakeGrid", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("dlgMakeGrid", "Close", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
