# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_problem_definition.ui'
#
# Created: Fri Jan 30 19:42:42 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgProblemDefinition(object):
    def setupUi(self, dlgProblemDefinition):
        dlgProblemDefinition.setObjectName(_fromUtf8("dlgProblemDefinition"))
        dlgProblemDefinition.resize(860, 650)
        dlgProblemDefinition.setMinimumSize(QtCore.QSize(860, 650))
        self.gridLayout_8 = QtGui.QGridLayout(dlgProblemDefinition)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.twProblemDefinition = QtGui.QTabWidget(dlgProblemDefinition)
        self.twProblemDefinition.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.twProblemDefinition.setFont(font)
        self.twProblemDefinition.setTabPosition(QtGui.QTabWidget.North)
        self.twProblemDefinition.setElideMode(QtCore.Qt.ElideLeft)
        self.twProblemDefinition.setTabsClosable(False)
        self.twProblemDefinition.setObjectName(_fromUtf8("twProblemDefinition"))
        self.tbFeatures = QtGui.QWidget()
        self.tbFeatures.setObjectName(_fromUtf8("tbFeatures"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tbFeatures)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.frFeatureEdit = QtGui.QFrame(self.tbFeatures)
        self.frFeatureEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frFeatureEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frFeatureEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frFeatureEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frFeatureEdit.setObjectName(_fromUtf8("frFeatureEdit"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frFeatureEdit)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frFeatureWidgets1 = QtGui.QFrame(self.frFeatureEdit)
        self.frFeatureWidgets1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frFeatureWidgets1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frFeatureWidgets1.setFrameShadow(QtGui.QFrame.Plain)
        self.frFeatureWidgets1.setObjectName(_fromUtf8("frFeatureWidgets1"))
        self.gridLayout = QtGui.QGridLayout(self.frFeatureWidgets1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblTarget = QtGui.QLabel(self.frFeatureWidgets1)
        self.lblTarget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTarget.sizePolicy().hasHeightForWidth())
        self.lblTarget.setSizePolicy(sizePolicy)
        self.lblTarget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblTarget.setObjectName(_fromUtf8("lblTarget"))
        self.gridLayout.addWidget(self.lblTarget, 2, 0, 1, 1)
        self.spbxTarget = QtGui.QDoubleSpinBox(self.frFeatureWidgets1)
        self.spbxTarget.setEnabled(True)
        self.spbxTarget.setMinimumSize(QtCore.QSize(190, 0))
        self.spbxTarget.setMaximumSize(QtCore.QSize(190, 16777215))
        self.spbxTarget.setDecimals(3)
        self.spbxTarget.setMaximum(999999999.0)
        self.spbxTarget.setObjectName(_fromUtf8("spbxTarget"))
        self.gridLayout.addWidget(self.spbxTarget, 2, 1, 1, 1)
        self.cbTargetType = QtGui.QComboBox(self.frFeatureWidgets1)
        self.cbTargetType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTargetType.sizePolicy().hasHeightForWidth())
        self.cbTargetType.setSizePolicy(sizePolicy)
        self.cbTargetType.setMinimumSize(QtCore.QSize(190, 0))
        self.cbTargetType.setMaximumSize(QtCore.QSize(190, 16777215))
        self.cbTargetType.setObjectName(_fromUtf8("cbTargetType"))
        self.cbTargetType.addItem(_fromUtf8(""))
        self.cbTargetType.addItem(_fromUtf8(""))
        self.cbTargetType.addItem(_fromUtf8(""))
        self.cbTargetType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbTargetType, 1, 1, 1, 1)
        self.lblPenatly = QtGui.QLabel(self.frFeatureWidgets1)
        self.lblPenatly.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPenatly.sizePolicy().hasHeightForWidth())
        self.lblPenatly.setSizePolicy(sizePolicy)
        self.lblPenatly.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblPenatly.setObjectName(_fromUtf8("lblPenatly"))
        self.gridLayout.addWidget(self.lblPenatly, 3, 0, 1, 1)
        self.spbxPenalty = QtGui.QDoubleSpinBox(self.frFeatureWidgets1)
        self.spbxPenalty.setEnabled(True)
        self.spbxPenalty.setMinimumSize(QtCore.QSize(190, 0))
        self.spbxPenalty.setMaximumSize(QtCore.QSize(190, 16777215))
        self.spbxPenalty.setDecimals(3)
        self.spbxPenalty.setMaximum(1000000000.0)
        self.spbxPenalty.setSingleStep(0.5)
        self.spbxPenalty.setProperty("value", 1.0)
        self.spbxPenalty.setObjectName(_fromUtf8("spbxPenalty"))
        self.gridLayout.addWidget(self.spbxPenalty, 3, 1, 1, 1)
        self.lblTargetType = QtGui.QLabel(self.frFeatureWidgets1)
        self.lblTargetType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTargetType.sizePolicy().hasHeightForWidth())
        self.lblTargetType.setSizePolicy(sizePolicy)
        self.lblTargetType.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblTargetType.setObjectName(_fromUtf8("lblTargetType"))
        self.gridLayout.addWidget(self.lblTargetType, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frFeatureWidgets1)
        self.frFeatureWidgets2 = QtGui.QFrame(self.frFeatureEdit)
        self.frFeatureWidgets2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frFeatureWidgets2.setFrameShadow(QtGui.QFrame.Plain)
        self.frFeatureWidgets2.setObjectName(_fromUtf8("frFeatureWidgets2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frFeatureWidgets2)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.pteFeatureDescription = QtGui.QPlainTextEdit(self.frFeatureWidgets2)
        self.pteFeatureDescription.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteFeatureDescription.sizePolicy().hasHeightForWidth())
        self.pteFeatureDescription.setSizePolicy(sizePolicy)
        self.pteFeatureDescription.setMinimumSize(QtCore.QSize(190, 0))
        self.pteFeatureDescription.setMaximumSize(QtCore.QSize(190, 200))
        self.pteFeatureDescription.setReadOnly(True)
        self.pteFeatureDescription.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pteFeatureDescription.setObjectName(_fromUtf8("pteFeatureDescription"))
        self.gridLayout_18.addWidget(self.pteFeatureDescription, 1, 1, 1, 1)
        self.leFeatureName = QtGui.QLineEdit(self.frFeatureWidgets2)
        self.leFeatureName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFeatureName.sizePolicy().hasHeightForWidth())
        self.leFeatureName.setSizePolicy(sizePolicy)
        self.leFeatureName.setMinimumSize(QtCore.QSize(190, 0))
        self.leFeatureName.setMaximumSize(QtCore.QSize(190, 16777215))
        self.leFeatureName.setObjectName(_fromUtf8("leFeatureName"))
        self.gridLayout_18.addWidget(self.leFeatureName, 0, 1, 1, 1)
        self.lblFeatureName = QtGui.QLabel(self.frFeatureWidgets2)
        self.lblFeatureName.setEnabled(True)
        self.lblFeatureName.setObjectName(_fromUtf8("lblFeatureName"))
        self.gridLayout_18.addWidget(self.lblFeatureName, 0, 0, 1, 1)
        self.lblFeatureDescription = QtGui.QLabel(self.frFeatureWidgets2)
        self.lblFeatureDescription.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFeatureDescription.sizePolicy().hasHeightForWidth())
        self.lblFeatureDescription.setSizePolicy(sizePolicy)
        self.lblFeatureDescription.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblFeatureDescription.setObjectName(_fromUtf8("lblFeatureDescription"))
        self.gridLayout_18.addWidget(self.lblFeatureDescription, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frFeatureWidgets2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.hzlnFeatures = QtGui.QFrame(self.frFeatureEdit)
        self.hzlnFeatures.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnFeatures.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnFeatures.setObjectName(_fromUtf8("hzlnFeatures"))
        self.verticalLayout.addWidget(self.hzlnFeatures)
        self.pbSaveFeature = QtGui.QPushButton(self.frFeatureEdit)
        self.pbSaveFeature.setEnabled(False)
        self.pbSaveFeature.setObjectName(_fromUtf8("pbSaveFeature"))
        self.verticalLayout.addWidget(self.pbSaveFeature)
        self.pbCancelFeature = QtGui.QPushButton(self.frFeatureEdit)
        self.pbCancelFeature.setEnabled(False)
        self.pbCancelFeature.setObjectName(_fromUtf8("pbCancelFeature"))
        self.verticalLayout.addWidget(self.pbCancelFeature)
        self.gridLayout_16.addWidget(self.frFeatureEdit, 0, 2, 1, 1)
        self.frFeatureSelect = QtGui.QFrame(self.tbFeatures)
        self.frFeatureSelect.setFrameShape(QtGui.QFrame.NoFrame)
        self.frFeatureSelect.setFrameShadow(QtGui.QFrame.Plain)
        self.frFeatureSelect.setObjectName(_fromUtf8("frFeatureSelect"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frFeatureSelect)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lblSelectedFeatureSources = QtGui.QLabel(self.frFeatureSelect)
        self.lblSelectedFeatureSources.setObjectName(_fromUtf8("lblSelectedFeatureSources"))
        self.gridLayout_10.addWidget(self.lblSelectedFeatureSources, 0, 2, 1, 1)
        self.lblAvailableFeatureSources = QtGui.QLabel(self.frFeatureSelect)
        self.lblAvailableFeatureSources.setObjectName(_fromUtf8("lblAvailableFeatureSources"))
        self.gridLayout_10.addWidget(self.lblAvailableFeatureSources, 0, 0, 1, 1)
        self.lwAvailableFeatureSources = QtGui.QListWidget(self.frFeatureSelect)
        self.lwAvailableFeatureSources.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwAvailableFeatureSources.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwAvailableFeatureSources.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lwAvailableFeatureSources.setObjectName(_fromUtf8("lwAvailableFeatureSources"))
        self.gridLayout_10.addWidget(self.lwAvailableFeatureSources, 1, 0, 1, 1)
        self.vlAddRemoveFeatures = QtGui.QVBoxLayout()
        self.vlAddRemoveFeatures.setObjectName(_fromUtf8("vlAddRemoveFeatures"))
        self.tbSortByNumber = QtGui.QToolButton(self.frFeatureSelect)
        self.tbSortByNumber.setMinimumSize(QtCore.QSize(30, 0))
        self.tbSortByNumber.setObjectName(_fromUtf8("tbSortByNumber"))
        self.vlAddRemoveFeatures.addWidget(self.tbSortByNumber)
        self.tbSortByName = QtGui.QToolButton(self.frFeatureSelect)
        self.tbSortByName.setMinimumSize(QtCore.QSize(30, 0))
        self.tbSortByName.setObjectName(_fromUtf8("tbSortByName"))
        self.vlAddRemoveFeatures.addWidget(self.tbSortByName)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlAddRemoveFeatures.addItem(spacerItem1)
        self.tbAddFeature = QtGui.QToolButton(self.frFeatureSelect)
        self.tbAddFeature.setEnabled(False)
        self.tbAddFeature.setArrowType(QtCore.Qt.RightArrow)
        self.tbAddFeature.setObjectName(_fromUtf8("tbAddFeature"))
        self.vlAddRemoveFeatures.addWidget(self.tbAddFeature)
        self.tbRemoveFeature = QtGui.QToolButton(self.frFeatureSelect)
        self.tbRemoveFeature.setEnabled(False)
        self.tbRemoveFeature.setArrowType(QtCore.Qt.LeftArrow)
        self.tbRemoveFeature.setObjectName(_fromUtf8("tbRemoveFeature"))
        self.vlAddRemoveFeatures.addWidget(self.tbRemoveFeature)
        self.gridLayout_10.addLayout(self.vlAddRemoveFeatures, 1, 1, 1, 1)
        self.lwSelectedFeatureSources = QtGui.QListWidget(self.frFeatureSelect)
        self.lwSelectedFeatureSources.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSelectedFeatureSources.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwSelectedFeatureSources.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lwSelectedFeatureSources.setObjectName(_fromUtf8("lwSelectedFeatureSources"))
        self.gridLayout_10.addWidget(self.lwSelectedFeatureSources, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbSelectAllAvailableFeatures = QtGui.QPushButton(self.frFeatureSelect)
        self.pbSelectAllAvailableFeatures.setObjectName(_fromUtf8("pbSelectAllAvailableFeatures"))
        self.horizontalLayout_2.addWidget(self.pbSelectAllAvailableFeatures)
        self.pbClearAvailableFeatures = QtGui.QPushButton(self.frFeatureSelect)
        self.pbClearAvailableFeatures.setObjectName(_fromUtf8("pbClearAvailableFeatures"))
        self.horizontalLayout_2.addWidget(self.pbClearAvailableFeatures)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pbSelectAllSelectedFeatures = QtGui.QPushButton(self.frFeatureSelect)
        self.pbSelectAllSelectedFeatures.setObjectName(_fromUtf8("pbSelectAllSelectedFeatures"))
        self.horizontalLayout_3.addWidget(self.pbSelectAllSelectedFeatures)
        self.pbClearSelectedFeatures = QtGui.QPushButton(self.frFeatureSelect)
        self.pbClearSelectedFeatures.setObjectName(_fromUtf8("pbClearSelectedFeatures"))
        self.horizontalLayout_3.addWidget(self.pbClearSelectedFeatures)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.gridLayout_16.addWidget(self.frFeatureSelect, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbFeatures, _fromUtf8(""))
        self.tbCosts = QtGui.QWidget()
        self.tbCosts.setObjectName(_fromUtf8("tbCosts"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tbCosts)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.frCostSelect = QtGui.QFrame(self.tbCosts)
        self.frCostSelect.setFrameShape(QtGui.QFrame.NoFrame)
        self.frCostSelect.setFrameShadow(QtGui.QFrame.Plain)
        self.frCostSelect.setObjectName(_fromUtf8("frCostSelect"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frCostSelect)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lwAvailableCostSources = QtGui.QListWidget(self.frCostSelect)
        self.lwAvailableCostSources.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwAvailableCostSources.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwAvailableCostSources.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lwAvailableCostSources.setObjectName(_fromUtf8("lwAvailableCostSources"))
        self.gridLayout_13.addWidget(self.lwAvailableCostSources, 1, 0, 1, 1)
        self.lblAvailableCostSources = QtGui.QLabel(self.frCostSelect)
        self.lblAvailableCostSources.setObjectName(_fromUtf8("lblAvailableCostSources"))
        self.gridLayout_13.addWidget(self.lblAvailableCostSources, 0, 0, 1, 1)
        self.lwSelectedCostSources = QtGui.QListWidget(self.frCostSelect)
        self.lwSelectedCostSources.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lwSelectedCostSources.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lwSelectedCostSources.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lwSelectedCostSources.setObjectName(_fromUtf8("lwSelectedCostSources"))
        self.gridLayout_13.addWidget(self.lwSelectedCostSources, 1, 2, 1, 1)
        self.lblSelectedCostSources = QtGui.QLabel(self.frCostSelect)
        self.lblSelectedCostSources.setObjectName(_fromUtf8("lblSelectedCostSources"))
        self.gridLayout_13.addWidget(self.lblSelectedCostSources, 0, 2, 1, 1)
        self.vlAddRemoveCosts = QtGui.QVBoxLayout()
        self.vlAddRemoveCosts.setObjectName(_fromUtf8("vlAddRemoveCosts"))
        self.tbAddCost = QtGui.QToolButton(self.frCostSelect)
        self.tbAddCost.setEnabled(False)
        self.tbAddCost.setArrowType(QtCore.Qt.RightArrow)
        self.tbAddCost.setObjectName(_fromUtf8("tbAddCost"))
        self.vlAddRemoveCosts.addWidget(self.tbAddCost)
        self.tbRemoveCost = QtGui.QToolButton(self.frCostSelect)
        self.tbRemoveCost.setEnabled(False)
        self.tbRemoveCost.setArrowType(QtCore.Qt.LeftArrow)
        self.tbRemoveCost.setObjectName(_fromUtf8("tbRemoveCost"))
        self.vlAddRemoveCosts.addWidget(self.tbRemoveCost)
        self.gridLayout_13.addLayout(self.vlAddRemoveCosts, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pbSelectAllAvailableCosts = QtGui.QPushButton(self.frCostSelect)
        self.pbSelectAllAvailableCosts.setObjectName(_fromUtf8("pbSelectAllAvailableCosts"))
        self.horizontalLayout_4.addWidget(self.pbSelectAllAvailableCosts)
        self.pbClearAvailableCosts = QtGui.QPushButton(self.frCostSelect)
        self.pbClearAvailableCosts.setObjectName(_fromUtf8("pbClearAvailableCosts"))
        self.horizontalLayout_4.addWidget(self.pbClearAvailableCosts)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pbSelectAllSelectedCosts = QtGui.QPushButton(self.frCostSelect)
        self.pbSelectAllSelectedCosts.setObjectName(_fromUtf8("pbSelectAllSelectedCosts"))
        self.horizontalLayout_5.addWidget(self.pbSelectAllSelectedCosts)
        self.pbClearSelectedCosts = QtGui.QPushButton(self.frCostSelect)
        self.pbClearSelectedCosts.setObjectName(_fromUtf8("pbClearSelectedCosts"))
        self.horizontalLayout_5.addWidget(self.pbClearSelectedCosts)
        self.gridLayout_13.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.gridLayout_17.addWidget(self.frCostSelect, 0, 0, 1, 1)
        self.frCostEdit = QtGui.QFrame(self.tbCosts)
        self.frCostEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frCostEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frCostEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frCostEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frCostEdit.setObjectName(_fromUtf8("frCostEdit"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frCostEdit)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frCostWidgets = QtGui.QFrame(self.frCostEdit)
        self.frCostWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frCostWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frCostWidgets.setObjectName(_fromUtf8("frCostWidgets"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frCostWidgets)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.leCostName = QtGui.QLineEdit(self.frCostWidgets)
        self.leCostName.setEnabled(True)
        self.leCostName.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leCostName.setObjectName(_fromUtf8("leCostName"))
        self.gridLayout_3.addWidget(self.leCostName, 0, 1, 1, 1)
        self.lblCostName = QtGui.QLabel(self.frCostWidgets)
        self.lblCostName.setEnabled(True)
        self.lblCostName.setObjectName(_fromUtf8("lblCostName"))
        self.gridLayout_3.addWidget(self.lblCostName, 0, 0, 1, 1)
        self.lblCostDescription = QtGui.QLabel(self.frCostWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCostDescription.sizePolicy().hasHeightForWidth())
        self.lblCostDescription.setSizePolicy(sizePolicy)
        self.lblCostDescription.setObjectName(_fromUtf8("lblCostDescription"))
        self.gridLayout_3.addWidget(self.lblCostDescription, 1, 0, 1, 1)
        self.pteCostDescription = QtGui.QPlainTextEdit(self.frCostWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteCostDescription.sizePolicy().hasHeightForWidth())
        self.pteCostDescription.setSizePolicy(sizePolicy)
        self.pteCostDescription.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pteCostDescription.setObjectName(_fromUtf8("pteCostDescription"))
        self.gridLayout_3.addWidget(self.pteCostDescription, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frCostWidgets)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.hzlnCosts = QtGui.QFrame(self.frCostEdit)
        self.hzlnCosts.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnCosts.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnCosts.setObjectName(_fromUtf8("hzlnCosts"))
        self.verticalLayout_5.addWidget(self.hzlnCosts)
        self.pbSaveCost = QtGui.QPushButton(self.frCostEdit)
        self.pbSaveCost.setEnabled(False)
        self.pbSaveCost.setObjectName(_fromUtf8("pbSaveCost"))
        self.verticalLayout_5.addWidget(self.pbSaveCost)
        self.pbCancelCost = QtGui.QPushButton(self.frCostEdit)
        self.pbCancelCost.setEnabled(False)
        self.pbCancelCost.setObjectName(_fromUtf8("pbCancelCost"))
        self.verticalLayout_5.addWidget(self.pbCancelCost)
        self.gridLayout_17.addWidget(self.frCostEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbCosts, _fromUtf8(""))
        self.tbZones = QtGui.QWidget()
        self.tbZones.setObjectName(_fromUtf8("tbZones"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tbZones)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblZones = QtGui.QTableWidget(self.tbZones)
        self.tblZones.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblZones.setTabKeyNavigation(False)
        self.tblZones.setProperty("showDropIndicator", False)
        self.tblZones.setDragDropOverwriteMode(False)
        self.tblZones.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblZones.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblZones.setObjectName(_fromUtf8("tblZones"))
        self.tblZones.setColumnCount(0)
        self.tblZones.setRowCount(0)
        self.gridLayout_9.addWidget(self.tblZones, 0, 0, 1, 1)
        self.frZoneEdit = QtGui.QFrame(self.tbZones)
        self.frZoneEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frZoneEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frZoneEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneEdit.setObjectName(_fromUtf8("frZoneEdit"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frZoneEdit)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frZoneWidgets = QtGui.QFrame(self.frZoneEdit)
        self.frZoneWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneWidgets.setObjectName(_fromUtf8("frZoneWidgets"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frZoneWidgets)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.spbxZoneId = QtGui.QSpinBox(self.frZoneWidgets)
        self.spbxZoneId.setEnabled(True)
        self.spbxZoneId.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spbxZoneId.setMinimum(1)
        self.spbxZoneId.setObjectName(_fromUtf8("spbxZoneId"))
        self.gridLayout_5.addWidget(self.spbxZoneId, 0, 1, 1, 1)
        self.lblZoneId = QtGui.QLabel(self.frZoneWidgets)
        self.lblZoneId.setEnabled(True)
        self.lblZoneId.setObjectName(_fromUtf8("lblZoneId"))
        self.gridLayout_5.addWidget(self.lblZoneId, 0, 0, 1, 1)
        self.lblZoneName = QtGui.QLabel(self.frZoneWidgets)
        self.lblZoneName.setEnabled(True)
        self.lblZoneName.setObjectName(_fromUtf8("lblZoneName"))
        self.gridLayout_5.addWidget(self.lblZoneName, 1, 0, 1, 1)
        self.leZoneName = QtGui.QLineEdit(self.frZoneWidgets)
        self.leZoneName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leZoneName.sizePolicy().hasHeightForWidth())
        self.leZoneName.setSizePolicy(sizePolicy)
        self.leZoneName.setMinimumSize(QtCore.QSize(200, 0))
        self.leZoneName.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leZoneName.setObjectName(_fromUtf8("leZoneName"))
        self.gridLayout_5.addWidget(self.leZoneName, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frZoneWidgets)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.hzlnZones = QtGui.QFrame(self.frZoneEdit)
        self.hzlnZones.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnZones.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnZones.setObjectName(_fromUtf8("hzlnZones"))
        self.verticalLayout_2.addWidget(self.hzlnZones)
        self.pbNewZone = QtGui.QPushButton(self.frZoneEdit)
        self.pbNewZone.setObjectName(_fromUtf8("pbNewZone"))
        self.verticalLayout_2.addWidget(self.pbNewZone)
        self.pbSaveZone = QtGui.QPushButton(self.frZoneEdit)
        self.pbSaveZone.setEnabled(False)
        self.pbSaveZone.setObjectName(_fromUtf8("pbSaveZone"))
        self.verticalLayout_2.addWidget(self.pbSaveZone)
        self.pbCancelZone = QtGui.QPushButton(self.frZoneEdit)
        self.pbCancelZone.setEnabled(False)
        self.pbCancelZone.setObjectName(_fromUtf8("pbCancelZone"))
        self.verticalLayout_2.addWidget(self.pbCancelZone)
        self.pbDeleteZone = QtGui.QPushButton(self.frZoneEdit)
        self.pbDeleteZone.setEnabled(False)
        self.pbDeleteZone.setObjectName(_fromUtf8("pbDeleteZone"))
        self.verticalLayout_2.addWidget(self.pbDeleteZone)
        self.gridLayout_9.addWidget(self.frZoneEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbZones, _fromUtf8(""))
        self.tbZoneCosts = QtGui.QWidget()
        self.tbZoneCosts.setObjectName(_fromUtf8("tbZoneCosts"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tbZoneCosts)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.tblZoneCosts = QtGui.QTableWidget(self.tbZoneCosts)
        self.tblZoneCosts.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblZoneCosts.setTabKeyNavigation(False)
        self.tblZoneCosts.setProperty("showDropIndicator", False)
        self.tblZoneCosts.setDragDropOverwriteMode(False)
        self.tblZoneCosts.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblZoneCosts.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblZoneCosts.setObjectName(_fromUtf8("tblZoneCosts"))
        self.tblZoneCosts.setColumnCount(0)
        self.tblZoneCosts.setRowCount(0)
        self.gridLayout_15.addWidget(self.tblZoneCosts, 0, 0, 1, 1)
        self.frZoneCostEdit = QtGui.QFrame(self.tbZoneCosts)
        self.frZoneCostEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frZoneCostEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frZoneCostEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneCostEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneCostEdit.setObjectName(_fromUtf8("frZoneCostEdit"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frZoneCostEdit)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frZoneCostWidgets = QtGui.QFrame(self.frZoneCostEdit)
        self.frZoneCostWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneCostWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneCostWidgets.setObjectName(_fromUtf8("frZoneCostWidgets"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frZoneCostWidgets)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbZoneCostCost = QtGui.QComboBox(self.frZoneCostWidgets)
        self.cbZoneCostCost.setEnabled(True)
        self.cbZoneCostCost.setObjectName(_fromUtf8("cbZoneCostCost"))
        self.gridLayout_2.addWidget(self.cbZoneCostCost, 1, 1, 1, 1)
        self.cbZoneCostZone = QtGui.QComboBox(self.frZoneCostWidgets)
        self.cbZoneCostZone.setEnabled(True)
        self.cbZoneCostZone.setMinimumSize(QtCore.QSize(225, 0))
        self.cbZoneCostZone.setObjectName(_fromUtf8("cbZoneCostZone"))
        self.gridLayout_2.addWidget(self.cbZoneCostZone, 0, 1, 1, 1)
        self.lblZoneCostZone = QtGui.QLabel(self.frZoneCostWidgets)
        self.lblZoneCostZone.setEnabled(True)
        self.lblZoneCostZone.setObjectName(_fromUtf8("lblZoneCostZone"))
        self.gridLayout_2.addWidget(self.lblZoneCostZone, 0, 0, 1, 1)
        self.lblZoneCostCost = QtGui.QLabel(self.frZoneCostWidgets)
        self.lblZoneCostCost.setEnabled(True)
        self.lblZoneCostCost.setObjectName(_fromUtf8("lblZoneCostCost"))
        self.gridLayout_2.addWidget(self.lblZoneCostCost, 1, 0, 1, 1)
        self.lblZoneCostMultiplier = QtGui.QLabel(self.frZoneCostWidgets)
        self.lblZoneCostMultiplier.setEnabled(True)
        self.lblZoneCostMultiplier.setObjectName(_fromUtf8("lblZoneCostMultiplier"))
        self.gridLayout_2.addWidget(self.lblZoneCostMultiplier, 2, 0, 1, 1)
        self.spbxZoneCostMultiplier = QtGui.QDoubleSpinBox(self.frZoneCostWidgets)
        self.spbxZoneCostMultiplier.setEnabled(True)
        self.spbxZoneCostMultiplier.setMaximum(10.0)
        self.spbxZoneCostMultiplier.setSingleStep(0.05)
        self.spbxZoneCostMultiplier.setObjectName(_fromUtf8("spbxZoneCostMultiplier"))
        self.gridLayout_2.addWidget(self.spbxZoneCostMultiplier, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frZoneCostWidgets)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.hlZC = QtGui.QFrame(self.frZoneCostEdit)
        self.hlZC.setFrameShape(QtGui.QFrame.HLine)
        self.hlZC.setFrameShadow(QtGui.QFrame.Sunken)
        self.hlZC.setObjectName(_fromUtf8("hlZC"))
        self.verticalLayout_7.addWidget(self.hlZC)
        self.pbNewZoneCost = QtGui.QPushButton(self.frZoneCostEdit)
        self.pbNewZoneCost.setObjectName(_fromUtf8("pbNewZoneCost"))
        self.verticalLayout_7.addWidget(self.pbNewZoneCost)
        self.pbSaveZoneCost = QtGui.QPushButton(self.frZoneCostEdit)
        self.pbSaveZoneCost.setEnabled(False)
        self.pbSaveZoneCost.setObjectName(_fromUtf8("pbSaveZoneCost"))
        self.verticalLayout_7.addWidget(self.pbSaveZoneCost)
        self.pbCancelZoneCost = QtGui.QPushButton(self.frZoneCostEdit)
        self.pbCancelZoneCost.setEnabled(False)
        self.pbCancelZoneCost.setObjectName(_fromUtf8("pbCancelZoneCost"))
        self.verticalLayout_7.addWidget(self.pbCancelZoneCost)
        self.pbDeleteZoneCost = QtGui.QPushButton(self.frZoneCostEdit)
        self.pbDeleteZoneCost.setEnabled(False)
        self.pbDeleteZoneCost.setObjectName(_fromUtf8("pbDeleteZoneCost"))
        self.verticalLayout_7.addWidget(self.pbDeleteZoneCost)
        self.gridLayout_15.addWidget(self.frZoneCostEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbZoneCosts, _fromUtf8(""))
        self.tbZoneTargets = QtGui.QWidget()
        self.tbZoneTargets.setObjectName(_fromUtf8("tbZoneTargets"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tbZoneTargets)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblZoneTargs = QtGui.QTableWidget(self.tbZoneTargets)
        self.tblZoneTargs.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblZoneTargs.setTabKeyNavigation(False)
        self.tblZoneTargs.setProperty("showDropIndicator", False)
        self.tblZoneTargs.setDragDropOverwriteMode(False)
        self.tblZoneTargs.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblZoneTargs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblZoneTargs.setObjectName(_fromUtf8("tblZoneTargs"))
        self.tblZoneTargs.setColumnCount(0)
        self.tblZoneTargs.setRowCount(0)
        self.gridLayout_11.addWidget(self.tblZoneTargs, 0, 0, 1, 1)
        self.frZoneTargEdit = QtGui.QFrame(self.tbZoneTargets)
        self.frZoneTargEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frZoneTargEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frZoneTargEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneTargEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneTargEdit.setObjectName(_fromUtf8("frZoneTargEdit"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frZoneTargEdit)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frZoneTargWidgets = QtGui.QFrame(self.frZoneTargEdit)
        self.frZoneTargWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneTargWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneTargWidgets.setObjectName(_fromUtf8("frZoneTargWidgets"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frZoneTargWidgets)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbZoneTargFeature = QtGui.QComboBox(self.frZoneTargWidgets)
        self.cbZoneTargFeature.setEnabled(True)
        self.cbZoneTargFeature.setObjectName(_fromUtf8("cbZoneTargFeature"))
        self.gridLayout_6.addWidget(self.cbZoneTargFeature, 1, 1, 1, 1)
        self.cbZoneTargType = QtGui.QComboBox(self.frZoneTargWidgets)
        self.cbZoneTargType.setEnabled(True)
        self.cbZoneTargType.setObjectName(_fromUtf8("cbZoneTargType"))
        self.cbZoneTargType.addItem(_fromUtf8(""))
        self.cbZoneTargType.addItem(_fromUtf8(""))
        self.cbZoneTargType.addItem(_fromUtf8(""))
        self.cbZoneTargType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbZoneTargType, 3, 1, 1, 1)
        self.lblZoneTargZone = QtGui.QLabel(self.frZoneTargWidgets)
        self.lblZoneTargZone.setEnabled(True)
        self.lblZoneTargZone.setObjectName(_fromUtf8("lblZoneTargZone"))
        self.gridLayout_6.addWidget(self.lblZoneTargZone, 0, 0, 1, 1)
        self.spbxZoneTargTarget = QtGui.QDoubleSpinBox(self.frZoneTargWidgets)
        self.spbxZoneTargTarget.setEnabled(True)
        self.spbxZoneTargTarget.setMaximum(10.0)
        self.spbxZoneTargTarget.setSingleStep(0.05)
        self.spbxZoneTargTarget.setObjectName(_fromUtf8("spbxZoneTargTarget"))
        self.gridLayout_6.addWidget(self.spbxZoneTargTarget, 2, 1, 1, 1)
        self.cbZoneTargZone = QtGui.QComboBox(self.frZoneTargWidgets)
        self.cbZoneTargZone.setEnabled(True)
        self.cbZoneTargZone.setMinimumSize(QtCore.QSize(200, 0))
        self.cbZoneTargZone.setObjectName(_fromUtf8("cbZoneTargZone"))
        self.gridLayout_6.addWidget(self.cbZoneTargZone, 0, 1, 1, 1)
        self.lblZoneTargFeature = QtGui.QLabel(self.frZoneTargWidgets)
        self.lblZoneTargFeature.setEnabled(True)
        self.lblZoneTargFeature.setObjectName(_fromUtf8("lblZoneTargFeature"))
        self.gridLayout_6.addWidget(self.lblZoneTargFeature, 1, 0, 1, 1)
        self.lblZoneTargTarget = QtGui.QLabel(self.frZoneTargWidgets)
        self.lblZoneTargTarget.setEnabled(True)
        self.lblZoneTargTarget.setObjectName(_fromUtf8("lblZoneTargTarget"))
        self.gridLayout_6.addWidget(self.lblZoneTargTarget, 2, 0, 1, 1)
        self.lblZoneTargType = QtGui.QLabel(self.frZoneTargWidgets)
        self.lblZoneTargType.setEnabled(True)
        self.lblZoneTargType.setObjectName(_fromUtf8("lblZoneTargType"))
        self.gridLayout_6.addWidget(self.lblZoneTargType, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frZoneTargWidgets)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.hzlnZoneTarg = QtGui.QFrame(self.frZoneTargEdit)
        self.hzlnZoneTarg.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnZoneTarg.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnZoneTarg.setObjectName(_fromUtf8("hzlnZoneTarg"))
        self.verticalLayout_3.addWidget(self.hzlnZoneTarg)
        self.pbNewZoneTarg = QtGui.QPushButton(self.frZoneTargEdit)
        self.pbNewZoneTarg.setObjectName(_fromUtf8("pbNewZoneTarg"))
        self.verticalLayout_3.addWidget(self.pbNewZoneTarg)
        self.pbSaveZoneTarg = QtGui.QPushButton(self.frZoneTargEdit)
        self.pbSaveZoneTarg.setEnabled(False)
        self.pbSaveZoneTarg.setObjectName(_fromUtf8("pbSaveZoneTarg"))
        self.verticalLayout_3.addWidget(self.pbSaveZoneTarg)
        self.pbCancelZoneTarg = QtGui.QPushButton(self.frZoneTargEdit)
        self.pbCancelZoneTarg.setEnabled(False)
        self.pbCancelZoneTarg.setObjectName(_fromUtf8("pbCancelZoneTarg"))
        self.verticalLayout_3.addWidget(self.pbCancelZoneTarg)
        self.pbDeleteZoneTarg = QtGui.QPushButton(self.frZoneTargEdit)
        self.pbDeleteZoneTarg.setEnabled(False)
        self.pbDeleteZoneTarg.setObjectName(_fromUtf8("pbDeleteZoneTarg"))
        self.verticalLayout_3.addWidget(self.pbDeleteZoneTarg)
        self.gridLayout_11.addWidget(self.frZoneTargEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbZoneTargets, _fromUtf8(""))
        self.tbZoneContributions = QtGui.QWidget()
        self.tbZoneContributions.setObjectName(_fromUtf8("tbZoneContributions"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tbZoneContributions)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tblZoneConts = QtGui.QTableWidget(self.tbZoneContributions)
        self.tblZoneConts.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblZoneConts.setTabKeyNavigation(False)
        self.tblZoneConts.setProperty("showDropIndicator", False)
        self.tblZoneConts.setDragDropOverwriteMode(False)
        self.tblZoneConts.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblZoneConts.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblZoneConts.setObjectName(_fromUtf8("tblZoneConts"))
        self.tblZoneConts.setColumnCount(0)
        self.tblZoneConts.setRowCount(0)
        self.gridLayout_12.addWidget(self.tblZoneConts, 0, 0, 1, 1)
        self.frZoneContEdit = QtGui.QFrame(self.tbZoneContributions)
        self.frZoneContEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frZoneContEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frZoneContEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneContEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneContEdit.setObjectName(_fromUtf8("frZoneContEdit"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frZoneContEdit)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frZoneContWidgets = QtGui.QFrame(self.frZoneContEdit)
        self.frZoneContWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneContWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneContWidgets.setObjectName(_fromUtf8("frZoneContWidgets"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frZoneContWidgets)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblZoneContFeature = QtGui.QLabel(self.frZoneContWidgets)
        self.lblZoneContFeature.setEnabled(True)
        self.lblZoneContFeature.setObjectName(_fromUtf8("lblZoneContFeature"))
        self.gridLayout_7.addWidget(self.lblZoneContFeature, 1, 0, 1, 1)
        self.cbZoneContFeature = QtGui.QComboBox(self.frZoneContWidgets)
        self.cbZoneContFeature.setEnabled(True)
        self.cbZoneContFeature.setMinimumSize(QtCore.QSize(0, 0))
        self.cbZoneContFeature.setMaximumSize(QtCore.QSize(500, 16777215))
        self.cbZoneContFeature.setObjectName(_fromUtf8("cbZoneContFeature"))
        self.gridLayout_7.addWidget(self.cbZoneContFeature, 1, 1, 1, 1)
        self.cbZoneContZone = QtGui.QComboBox(self.frZoneContWidgets)
        self.cbZoneContZone.setEnabled(True)
        self.cbZoneContZone.setMinimumSize(QtCore.QSize(225, 0))
        self.cbZoneContZone.setObjectName(_fromUtf8("cbZoneContZone"))
        self.gridLayout_7.addWidget(self.cbZoneContZone, 0, 1, 1, 1)
        self.lblZoneContZone = QtGui.QLabel(self.frZoneContWidgets)
        self.lblZoneContZone.setEnabled(True)
        self.lblZoneContZone.setObjectName(_fromUtf8("lblZoneContZone"))
        self.gridLayout_7.addWidget(self.lblZoneContZone, 0, 0, 1, 1)
        self.lblZoneContFraction = QtGui.QLabel(self.frZoneContWidgets)
        self.lblZoneContFraction.setEnabled(True)
        self.lblZoneContFraction.setObjectName(_fromUtf8("lblZoneContFraction"))
        self.gridLayout_7.addWidget(self.lblZoneContFraction, 2, 0, 1, 1)
        self.spbxZoneContFraction = QtGui.QDoubleSpinBox(self.frZoneContWidgets)
        self.spbxZoneContFraction.setEnabled(True)
        self.spbxZoneContFraction.setMaximum(1.0)
        self.spbxZoneContFraction.setSingleStep(0.05)
        self.spbxZoneContFraction.setObjectName(_fromUtf8("spbxZoneContFraction"))
        self.gridLayout_7.addWidget(self.spbxZoneContFraction, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frZoneContWidgets)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.hzlnZCont = QtGui.QFrame(self.frZoneContEdit)
        self.hzlnZCont.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnZCont.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnZCont.setObjectName(_fromUtf8("hzlnZCont"))
        self.verticalLayout_4.addWidget(self.hzlnZCont)
        self.pbNewZoneCont = QtGui.QPushButton(self.frZoneContEdit)
        self.pbNewZoneCont.setObjectName(_fromUtf8("pbNewZoneCont"))
        self.verticalLayout_4.addWidget(self.pbNewZoneCont)
        self.pbSaveZoneCont = QtGui.QPushButton(self.frZoneContEdit)
        self.pbSaveZoneCont.setEnabled(False)
        self.pbSaveZoneCont.setObjectName(_fromUtf8("pbSaveZoneCont"))
        self.verticalLayout_4.addWidget(self.pbSaveZoneCont)
        self.pbCancelZoneCont = QtGui.QPushButton(self.frZoneContEdit)
        self.pbCancelZoneCont.setEnabled(False)
        self.pbCancelZoneCont.setObjectName(_fromUtf8("pbCancelZoneCont"))
        self.verticalLayout_4.addWidget(self.pbCancelZoneCont)
        self.pbDeleteZoneCont = QtGui.QPushButton(self.frZoneContEdit)
        self.pbDeleteZoneCont.setEnabled(False)
        self.pbDeleteZoneCont.setObjectName(_fromUtf8("pbDeleteZoneCont"))
        self.verticalLayout_4.addWidget(self.pbDeleteZoneCont)
        self.gridLayout_12.addWidget(self.frZoneContEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbZoneContributions, _fromUtf8(""))
        self.tbZoneBoundaryCosts = QtGui.QWidget()
        self.tbZoneBoundaryCosts.setObjectName(_fromUtf8("tbZoneBoundaryCosts"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tbZoneBoundaryCosts)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tblZoneBounCosts = QtGui.QTableWidget(self.tbZoneBoundaryCosts)
        self.tblZoneBounCosts.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblZoneBounCosts.setTabKeyNavigation(False)
        self.tblZoneBounCosts.setProperty("showDropIndicator", False)
        self.tblZoneBounCosts.setDragDropOverwriteMode(False)
        self.tblZoneBounCosts.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblZoneBounCosts.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblZoneBounCosts.setObjectName(_fromUtf8("tblZoneBounCosts"))
        self.tblZoneBounCosts.setColumnCount(0)
        self.tblZoneBounCosts.setRowCount(0)
        self.gridLayout_14.addWidget(self.tblZoneBounCosts, 0, 0, 1, 1)
        self.frZoneBounCostEdit = QtGui.QFrame(self.tbZoneBoundaryCosts)
        self.frZoneBounCostEdit.setMinimumSize(QtCore.QSize(325, 0))
        self.frZoneBounCostEdit.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frZoneBounCostEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneBounCostEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneBounCostEdit.setObjectName(_fromUtf8("frZoneBounCostEdit"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frZoneBounCostEdit)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frZoneBounCostWidgets = QtGui.QFrame(self.frZoneBounCostEdit)
        self.frZoneBounCostWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frZoneBounCostWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frZoneBounCostWidgets.setObjectName(_fromUtf8("frZoneBounCostWidgets"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frZoneBounCostWidgets)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblZoneBounZone1 = QtGui.QLabel(self.frZoneBounCostWidgets)
        self.lblZoneBounZone1.setEnabled(True)
        self.lblZoneBounZone1.setObjectName(_fromUtf8("lblZoneBounZone1"))
        self.gridLayout_4.addWidget(self.lblZoneBounZone1, 0, 0, 1, 1)
        self.lblZoneBounZone2 = QtGui.QLabel(self.frZoneBounCostWidgets)
        self.lblZoneBounZone2.setEnabled(True)
        self.lblZoneBounZone2.setObjectName(_fromUtf8("lblZoneBounZone2"))
        self.gridLayout_4.addWidget(self.lblZoneBounZone2, 1, 0, 1, 1)
        self.cbZoneBounCostZone1 = QtGui.QComboBox(self.frZoneBounCostWidgets)
        self.cbZoneBounCostZone1.setEnabled(True)
        self.cbZoneBounCostZone1.setMinimumSize(QtCore.QSize(210, 0))
        self.cbZoneBounCostZone1.setObjectName(_fromUtf8("cbZoneBounCostZone1"))
        self.gridLayout_4.addWidget(self.cbZoneBounCostZone1, 0, 1, 1, 1)
        self.cbZoneBounCostZone2 = QtGui.QComboBox(self.frZoneBounCostWidgets)
        self.cbZoneBounCostZone2.setEnabled(True)
        self.cbZoneBounCostZone2.setObjectName(_fromUtf8("cbZoneBounCostZone2"))
        self.gridLayout_4.addWidget(self.cbZoneBounCostZone2, 1, 1, 1, 1)
        self.lblZoneBounCost = QtGui.QLabel(self.frZoneBounCostWidgets)
        self.lblZoneBounCost.setEnabled(True)
        self.lblZoneBounCost.setObjectName(_fromUtf8("lblZoneBounCost"))
        self.gridLayout_4.addWidget(self.lblZoneBounCost, 2, 0, 1, 1)
        self.spbxBoundaryCost = QtGui.QDoubleSpinBox(self.frZoneBounCostWidgets)
        self.spbxBoundaryCost.setEnabled(True)
        self.spbxBoundaryCost.setMaximum(10.0)
        self.spbxBoundaryCost.setSingleStep(0.05)
        self.spbxBoundaryCost.setObjectName(_fromUtf8("spbxBoundaryCost"))
        self.gridLayout_4.addWidget(self.spbxBoundaryCost, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frZoneBounCostWidgets)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.hzlnZoneBounCosts = QtGui.QFrame(self.frZoneBounCostEdit)
        self.hzlnZoneBounCosts.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnZoneBounCosts.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnZoneBounCosts.setObjectName(_fromUtf8("hzlnZoneBounCosts"))
        self.verticalLayout_6.addWidget(self.hzlnZoneBounCosts)
        self.pbNewZoneBounCost = QtGui.QPushButton(self.frZoneBounCostEdit)
        self.pbNewZoneBounCost.setObjectName(_fromUtf8("pbNewZoneBounCost"))
        self.verticalLayout_6.addWidget(self.pbNewZoneBounCost)
        self.pbSaveZoneBounCost = QtGui.QPushButton(self.frZoneBounCostEdit)
        self.pbSaveZoneBounCost.setEnabled(False)
        self.pbSaveZoneBounCost.setObjectName(_fromUtf8("pbSaveZoneBounCost"))
        self.verticalLayout_6.addWidget(self.pbSaveZoneBounCost)
        self.pbCancelZoneBounCost = QtGui.QPushButton(self.frZoneBounCostEdit)
        self.pbCancelZoneBounCost.setEnabled(False)
        self.pbCancelZoneBounCost.setObjectName(_fromUtf8("pbCancelZoneBounCost"))
        self.verticalLayout_6.addWidget(self.pbCancelZoneBounCost)
        self.pbDeleteZoneBounCost = QtGui.QPushButton(self.frZoneBounCostEdit)
        self.pbDeleteZoneBounCost.setEnabled(False)
        self.pbDeleteZoneBounCost.setObjectName(_fromUtf8("pbDeleteZoneBounCost"))
        self.verticalLayout_6.addWidget(self.pbDeleteZoneBounCost)
        self.gridLayout_14.addWidget(self.frZoneBounCostEdit, 0, 1, 1, 1)
        self.twProblemDefinition.addTab(self.tbZoneBoundaryCosts, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.twProblemDefinition, 1, 0, 1, 2)
        self.hzSettingsGISButtons = QtGui.QHBoxLayout()
        self.hzSettingsGISButtons.setObjectName(_fromUtf8("hzSettingsGISButtons"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hzSettingsGISButtons.addItem(spacerItem8)
        self.pbClose = QtGui.QPushButton(dlgProblemDefinition)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hzSettingsGISButtons.addWidget(self.pbClose)
        self.gridLayout_8.addLayout(self.hzSettingsGISButtons, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblWorkingProject = QtGui.QLabel(dlgProblemDefinition)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWorkingProject.sizePolicy().hasHeightForWidth())
        self.lblWorkingProject.setSizePolicy(sizePolicy)
        self.lblWorkingProject.setMaximumSize(QtCore.QSize(250, 100))
        self.lblWorkingProject.setObjectName(_fromUtf8("lblWorkingProject"))
        self.horizontalLayout.addWidget(self.lblWorkingProject)
        self.cbWorkingProject = QtGui.QComboBox(dlgProblemDefinition)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbWorkingProject.sizePolicy().hasHeightForWidth())
        self.cbWorkingProject.setSizePolicy(sizePolicy)
        self.cbWorkingProject.setObjectName(_fromUtf8("cbWorkingProject"))
        self.horizontalLayout.addWidget(self.cbWorkingProject)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(dlgProblemDefinition)
        self.twProblemDefinition.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgProblemDefinition)

    def retranslateUi(self, dlgProblemDefinition):
        dlgProblemDefinition.setWindowTitle(QtGui.QApplication.translate("dlgProblemDefinition", "QMZ Problem Definition. Current Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTarget.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTargetType.setItemText(0, QtGui.QApplication.translate("dlgProblemDefinition", "Target Value", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTargetType.setItemText(1, QtGui.QApplication.translate("dlgProblemDefinition", "Proportion", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTargetType.setItemText(2, QtGui.QApplication.translate("dlgProblemDefinition", "Target Occurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTargetType.setItemText(3, QtGui.QApplication.translate("dlgProblemDefinition", "Proportional Occurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPenatly.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTargetType.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Target Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFeatureName.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Feature Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFeatureDescription.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectedFeatureSources.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Selected as Features", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAvailableFeatureSources.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Available Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.lwAvailableFeatureSources.setSortingEnabled(False)
        self.tbSortByNumber.setToolTip(QtGui.QApplication.translate("dlgProblemDefinition", "Sort By Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSortByNumber.setText(QtGui.QApplication.translate("dlgProblemDefinition", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSortByName.setToolTip(QtGui.QApplication.translate("dlgProblemDefinition", "Sort By Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSortByName.setText(QtGui.QApplication.translate("dlgProblemDefinition", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRemoveFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lwSelectedFeatureSources.setSortingEnabled(False)
        self.pbSelectAllAvailableFeatures.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClearAvailableFeatures.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectAllSelectedFeatures.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClearSelectedFeatures.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbFeatures), QtGui.QApplication.translate("dlgProblemDefinition", "Features (R)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAvailableCostSources.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Available Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectedCostSources.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Selected as Costs", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAddCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRemoveCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectAllAvailableCosts.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClearAvailableCosts.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSelectAllSelectedCosts.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClearSelectedCosts.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCostName.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cost Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCostDescription.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbCosts), QtGui.QApplication.translate("dlgProblemDefinition", "Costs (R)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneId.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneName.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbZones), QtGui.QApplication.translate("dlgProblemDefinition", "Zones (R)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneCostZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneCostCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cost:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneCostMultiplier.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Multiplier:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewZoneCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveZoneCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelZoneCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteZoneCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbZoneCosts), QtGui.QApplication.translate("dlgProblemDefinition", "Zone Costs (R)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbZoneTargType.setItemText(0, QtGui.QApplication.translate("dlgProblemDefinition", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.cbZoneTargType.setItemText(1, QtGui.QApplication.translate("dlgProblemDefinition", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.cbZoneTargType.setItemText(2, QtGui.QApplication.translate("dlgProblemDefinition", "Occurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.cbZoneTargType.setItemText(3, QtGui.QApplication.translate("dlgProblemDefinition", "Percent Occurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneTargZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneTargFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Feature:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneTargTarget.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneTargType.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Target Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewZoneTarg.setText(QtGui.QApplication.translate("dlgProblemDefinition", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveZoneTarg.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelZoneTarg.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteZoneTarg.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbZoneTargets), QtGui.QApplication.translate("dlgProblemDefinition", "Zone Targets (O)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneContFeature.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Feature:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneContZone.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneContFraction.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Fraction:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewZoneCont.setText(QtGui.QApplication.translate("dlgProblemDefinition", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveZoneCont.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelZoneCont.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteZoneCont.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbZoneContributions), QtGui.QApplication.translate("dlgProblemDefinition", "Zone Contributions (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneBounZone1.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneBounZone2.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Zone 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZoneBounCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Boundary Cost:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewZoneBounCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveZoneBounCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelZoneBounCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteZoneBounCost.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.twProblemDefinition.setTabText(self.twProblemDefinition.indexOf(self.tbZoneBoundaryCosts), QtGui.QApplication.translate("dlgProblemDefinition", "Zone Boundary Costs (O)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWorkingProject.setText(QtGui.QApplication.translate("dlgProblemDefinition", "Current Working Project:", None, QtGui.QApplication.UnicodeUTF8))

