# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings_gis.ui'
#
# Created: Sun Feb  1 13:22:29 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgSettingsGIS(object):
    def setupUi(self, dlgSettingsGIS):
        dlgSettingsGIS.setObjectName(_fromUtf8("dlgSettingsGIS"))
        dlgSettingsGIS.resize(818, 596)
        self.gridLayout = QtGui.QGridLayout(dlgSettingsGIS)
        self.gridLayout.setContentsMargins(0, 9, 0, 9)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hzSettingsGISButtons = QtGui.QHBoxLayout()
        self.hzSettingsGISButtons.setObjectName(_fromUtf8("hzSettingsGISButtons"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hzSettingsGISButtons.addItem(spacerItem)
        self.pbClose = QtGui.QPushButton(dlgSettingsGIS)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.hzSettingsGISButtons.addWidget(self.pbClose)
        self.gridLayout.addLayout(self.hzSettingsGISButtons, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblWorkingProject = QtGui.QLabel(dlgSettingsGIS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWorkingProject.sizePolicy().hasHeightForWidth())
        self.lblWorkingProject.setSizePolicy(sizePolicy)
        self.lblWorkingProject.setMaximumSize(QtCore.QSize(250, 100))
        self.lblWorkingProject.setObjectName(_fromUtf8("lblWorkingProject"))
        self.horizontalLayout.addWidget(self.lblWorkingProject)
        self.cbWorkingProject = QtGui.QComboBox(dlgSettingsGIS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbWorkingProject.sizePolicy().hasHeightForWidth())
        self.cbWorkingProject.setSizePolicy(sizePolicy)
        self.cbWorkingProject.setObjectName(_fromUtf8("cbWorkingProject"))
        self.horizontalLayout.addWidget(self.cbWorkingProject)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.twSettingsGIS = QtGui.QTabWidget(dlgSettingsGIS)
        self.twSettingsGIS.setMinimumSize(QtCore.QSize(800, 500))
        self.twSettingsGIS.setObjectName(_fromUtf8("twSettingsGIS"))
        self.tbSettings = QtGui.QWidget()
        self.tbSettings.setObjectName(_fromUtf8("tbSettings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tbSettings)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.hzSettingsButtons = QtGui.QHBoxLayout()
        self.hzSettingsButtons.setObjectName(_fromUtf8("hzSettingsButtons"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hzSettingsButtons.addItem(spacerItem1)
        self.pbSaveQMZSettings = QtGui.QPushButton(self.tbSettings)
        self.pbSaveQMZSettings.setEnabled(False)
        self.pbSaveQMZSettings.setObjectName(_fromUtf8("pbSaveQMZSettings"))
        self.hzSettingsButtons.addWidget(self.pbSaveQMZSettings)
        self.pbCancelQMZSettings = QtGui.QPushButton(self.tbSettings)
        self.pbCancelQMZSettings.setEnabled(False)
        self.pbCancelQMZSettings.setObjectName(_fromUtf8("pbCancelQMZSettings"))
        self.hzSettingsButtons.addWidget(self.pbCancelQMZSettings)
        self.gridLayout_2.addLayout(self.hzSettingsButtons, 2, 0, 1, 1)
        self.flQMarxanZSettings = QtGui.QFormLayout()
        self.flQMarxanZSettings.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.flQMarxanZSettings.setObjectName(_fromUtf8("flQMarxanZSettings"))
        self.lblMarxanZonesPath = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblMarxanZonesPath.setFont(font)
        self.lblMarxanZonesPath.setObjectName(_fromUtf8("lblMarxanZonesPath"))
        self.flQMarxanZSettings.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblMarxanZonesPath)
        self.hlMarxanZonesPath = QtGui.QHBoxLayout()
        self.hlMarxanZonesPath.setObjectName(_fromUtf8("hlMarxanZonesPath"))
        self.leMarxanZonesPath = QtGui.QLineEdit(self.tbSettings)
        self.leMarxanZonesPath.setObjectName(_fromUtf8("leMarxanZonesPath"))
        self.hlMarxanZonesPath.addWidget(self.leMarxanZonesPath)
        self.tbMarxanZonesPath = QtGui.QToolButton(self.tbSettings)
        self.tbMarxanZonesPath.setObjectName(_fromUtf8("tbMarxanZonesPath"))
        self.hlMarxanZonesPath.addWidget(self.tbMarxanZonesPath)
        self.flQMarxanZSettings.setLayout(1, QtGui.QFormLayout.FieldRole, self.hlMarxanZonesPath)
        self.lblMarxanPath = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblMarxanPath.setFont(font)
        self.lblMarxanPath.setObjectName(_fromUtf8("lblMarxanPath"))
        self.flQMarxanZSettings.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblMarxanPath)
        self.lblRPath = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblRPath.setFont(font)
        self.lblRPath.setObjectName(_fromUtf8("lblRPath"))
        self.flQMarxanZSettings.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblRPath)
        self.lblQMZDir = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblQMZDir.setFont(font)
        self.lblQMZDir.setObjectName(_fromUtf8("lblQMZDir"))
        self.flQMarxanZSettings.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblQMZDir)
        self.lblDefaultProject = QtGui.QLabel(self.tbSettings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblDefaultProject.setFont(font)
        self.lblDefaultProject.setObjectName(_fromUtf8("lblDefaultProject"))
        self.flQMarxanZSettings.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblDefaultProject)
        self.hlMarxanPath = QtGui.QHBoxLayout()
        self.hlMarxanPath.setObjectName(_fromUtf8("hlMarxanPath"))
        self.leMarxanPath = QtGui.QLineEdit(self.tbSettings)
        self.leMarxanPath.setObjectName(_fromUtf8("leMarxanPath"))
        self.hlMarxanPath.addWidget(self.leMarxanPath)
        self.tbMarxanPath = QtGui.QToolButton(self.tbSettings)
        self.tbMarxanPath.setObjectName(_fromUtf8("tbMarxanPath"))
        self.hlMarxanPath.addWidget(self.tbMarxanPath)
        self.flQMarxanZSettings.setLayout(0, QtGui.QFormLayout.FieldRole, self.hlMarxanPath)
        self.hlRPath = QtGui.QHBoxLayout()
        self.hlRPath.setObjectName(_fromUtf8("hlRPath"))
        self.leRPath = QtGui.QLineEdit(self.tbSettings)
        self.leRPath.setObjectName(_fromUtf8("leRPath"))
        self.hlRPath.addWidget(self.leRPath)
        self.tbRPath = QtGui.QToolButton(self.tbSettings)
        self.tbRPath.setObjectName(_fromUtf8("tbRPath"))
        self.hlRPath.addWidget(self.tbRPath)
        self.flQMarxanZSettings.setLayout(2, QtGui.QFormLayout.FieldRole, self.hlRPath)
        self.hlQMZDir = QtGui.QHBoxLayout()
        self.hlQMZDir.setObjectName(_fromUtf8("hlQMZDir"))
        self.leQMZDir = QtGui.QLineEdit(self.tbSettings)
        self.leQMZDir.setObjectName(_fromUtf8("leQMZDir"))
        self.hlQMZDir.addWidget(self.leQMZDir)
        self.tbQMZDir = QtGui.QToolButton(self.tbSettings)
        self.tbQMZDir.setObjectName(_fromUtf8("tbQMZDir"))
        self.hlQMZDir.addWidget(self.tbQMZDir)
        self.flQMarxanZSettings.setLayout(3, QtGui.QFormLayout.FieldRole, self.hlQMZDir)
        self.leDefaultProject = QtGui.QLineEdit(self.tbSettings)
        self.leDefaultProject.setEnabled(False)
        self.leDefaultProject.setObjectName(_fromUtf8("leDefaultProject"))
        self.flQMarxanZSettings.setWidget(4, QtGui.QFormLayout.FieldRole, self.leDefaultProject)
        self.gridLayout_2.addLayout(self.flQMarxanZSettings, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.twSettingsGIS.addTab(self.tbSettings, _fromUtf8(""))
        self.tbProjectsScenarios = QtGui.QWidget()
        self.tbProjectsScenarios.setObjectName(_fromUtf8("tbProjectsScenarios"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tbProjectsScenarios)
        self.gridLayout_7.setMargin(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.vlProjectControlsRight = QtGui.QVBoxLayout()
        self.vlProjectControlsRight.setSpacing(6)
        self.vlProjectControlsRight.setObjectName(_fromUtf8("vlProjectControlsRight"))
        self.frProjectControls1 = QtGui.QFrame(self.tbProjectsScenarios)
        self.frProjectControls1.setEnabled(True)
        self.frProjectControls1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frProjectControls1.setFrameShadow(QtGui.QFrame.Plain)
        self.frProjectControls1.setObjectName(_fromUtf8("frProjectControls1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frProjectControls1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblProjectDir = QtGui.QLabel(self.frProjectControls1)
        self.lblProjectDir.setEnabled(True)
        self.lblProjectDir.setObjectName(_fromUtf8("lblProjectDir"))
        self.gridLayout_3.addWidget(self.lblProjectDir, 0, 0, 1, 1)
        self.cbProjectType = QtGui.QComboBox(self.frProjectControls1)
        self.cbProjectType.setEnabled(True)
        self.cbProjectType.setObjectName(_fromUtf8("cbProjectType"))
        self.cbProjectType.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbProjectType, 5, 0, 1, 1)
        self.lbProjectIsDefault = QtGui.QLabel(self.frProjectControls1)
        self.lbProjectIsDefault.setEnabled(True)
        self.lbProjectIsDefault.setObjectName(_fromUtf8("lbProjectIsDefault"))
        self.gridLayout_3.addWidget(self.lbProjectIsDefault, 8, 0, 1, 1)
        self.lblProjectType = QtGui.QLabel(self.frProjectControls1)
        self.lblProjectType.setEnabled(True)
        self.lblProjectType.setObjectName(_fromUtf8("lblProjectType"))
        self.gridLayout_3.addWidget(self.lblProjectType, 4, 0, 1, 1)
        self.lblProjectName = QtGui.QLabel(self.frProjectControls1)
        self.lblProjectName.setEnabled(True)
        self.lblProjectName.setObjectName(_fromUtf8("lblProjectName"))
        self.gridLayout_3.addWidget(self.lblProjectName, 2, 0, 1, 1)
        self.leProjectName = QtGui.QLineEdit(self.frProjectControls1)
        self.leProjectName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectName.sizePolicy().hasHeightForWidth())
        self.leProjectName.setSizePolicy(sizePolicy)
        self.leProjectName.setMinimumSize(QtCore.QSize(250, 0))
        self.leProjectName.setObjectName(_fromUtf8("leProjectName"))
        self.gridLayout_3.addWidget(self.leProjectName, 3, 0, 1, 1)
        self.cbProjectIsDefault = QtGui.QComboBox(self.frProjectControls1)
        self.cbProjectIsDefault.setEnabled(True)
        self.cbProjectIsDefault.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cbProjectIsDefault.setObjectName(_fromUtf8("cbProjectIsDefault"))
        self.cbProjectIsDefault.addItem(_fromUtf8(""))
        self.cbProjectIsDefault.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbProjectIsDefault, 9, 0, 1, 1)
        self.leProjectDir = QtGui.QLineEdit(self.frProjectControls1)
        self.leProjectDir.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leProjectDir.sizePolicy().hasHeightForWidth())
        self.leProjectDir.setSizePolicy(sizePolicy)
        self.leProjectDir.setMinimumSize(QtCore.QSize(250, 0))
        self.leProjectDir.setReadOnly(True)
        self.leProjectDir.setObjectName(_fromUtf8("leProjectDir"))
        self.gridLayout_3.addWidget(self.leProjectDir, 1, 0, 1, 1)
        self.vlProjectControlsRight.addWidget(self.frProjectControls1)
        self.hzlnProjects = QtGui.QFrame(self.tbProjectsScenarios)
        self.hzlnProjects.setMinimumSize(QtCore.QSize(0, 10))
        self.hzlnProjects.setFrameShape(QtGui.QFrame.HLine)
        self.hzlnProjects.setFrameShadow(QtGui.QFrame.Sunken)
        self.hzlnProjects.setObjectName(_fromUtf8("hzlnProjects"))
        self.vlProjectControlsRight.addWidget(self.hzlnProjects)
        self.pbNewProject = QtGui.QPushButton(self.tbProjectsScenarios)
        self.pbNewProject.setObjectName(_fromUtf8("pbNewProject"))
        self.vlProjectControlsRight.addWidget(self.pbNewProject)
        self.pbSaveProject = QtGui.QPushButton(self.tbProjectsScenarios)
        self.pbSaveProject.setEnabled(False)
        self.pbSaveProject.setObjectName(_fromUtf8("pbSaveProject"))
        self.vlProjectControlsRight.addWidget(self.pbSaveProject)
        self.pbCancelProject = QtGui.QPushButton(self.tbProjectsScenarios)
        self.pbCancelProject.setEnabled(False)
        self.pbCancelProject.setObjectName(_fromUtf8("pbCancelProject"))
        self.vlProjectControlsRight.addWidget(self.pbCancelProject)
        self.pbDuplicateProject = QtGui.QPushButton(self.tbProjectsScenarios)
        self.pbDuplicateProject.setEnabled(False)
        self.pbDuplicateProject.setObjectName(_fromUtf8("pbDuplicateProject"))
        self.vlProjectControlsRight.addWidget(self.pbDuplicateProject)
        self.gridLayout_7.addLayout(self.vlProjectControlsRight, 0, 1, 1, 1)
        self.frProjectControls2 = QtGui.QFrame(self.tbProjectsScenarios)
        self.frProjectControls2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frProjectControls2.sizePolicy().hasHeightForWidth())
        self.frProjectControls2.setSizePolicy(sizePolicy)
        self.frProjectControls2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frProjectControls2.setFrameShadow(QtGui.QFrame.Plain)
        self.frProjectControls2.setObjectName(_fromUtf8("frProjectControls2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frProjectControls2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblPUField = QtGui.QLabel(self.frProjectControls2)
        self.lblPUField.setObjectName(_fromUtf8("lblPUField"))
        self.gridLayout_6.addWidget(self.lblPUField, 12, 0, 1, 1)
        self.lblProjectDescription = QtGui.QLabel(self.frProjectControls2)
        self.lblProjectDescription.setEnabled(True)
        self.lblProjectDescription.setObjectName(_fromUtf8("lblProjectDescription"))
        self.gridLayout_6.addWidget(self.lblProjectDescription, 2, 0, 1, 1)
        self.lblStudyAreaLayer = QtGui.QLabel(self.frProjectControls2)
        self.lblStudyAreaLayer.setEnabled(True)
        self.lblStudyAreaLayer.setObjectName(_fromUtf8("lblStudyAreaLayer"))
        self.gridLayout_6.addWidget(self.lblStudyAreaLayer, 8, 0, 1, 1)
        self.lblPlanningLayer = QtGui.QLabel(self.frProjectControls2)
        self.lblPlanningLayer.setEnabled(True)
        self.lblPlanningLayer.setObjectName(_fromUtf8("lblPlanningLayer"))
        self.gridLayout_6.addWidget(self.lblPlanningLayer, 10, 0, 1, 1)
        self.cbPlanningLayer = QtGui.QComboBox(self.frProjectControls2)
        self.cbPlanningLayer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPlanningLayer.sizePolicy().hasHeightForWidth())
        self.cbPlanningLayer.setSizePolicy(sizePolicy)
        self.cbPlanningLayer.setMinimumSize(QtCore.QSize(250, 0))
        self.cbPlanningLayer.setObjectName(_fromUtf8("cbPlanningLayer"))
        self.gridLayout_6.addWidget(self.cbPlanningLayer, 11, 0, 1, 1)
        self.pteProjectDescription = QtGui.QPlainTextEdit(self.frProjectControls2)
        self.pteProjectDescription.setEnabled(True)
        self.pteProjectDescription.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pteProjectDescription.setObjectName(_fromUtf8("pteProjectDescription"))
        self.gridLayout_6.addWidget(self.pteProjectDescription, 3, 0, 1, 1)
        self.cbStudyAreaLayer = QtGui.QComboBox(self.frProjectControls2)
        self.cbStudyAreaLayer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbStudyAreaLayer.sizePolicy().hasHeightForWidth())
        self.cbStudyAreaLayer.setSizePolicy(sizePolicy)
        self.cbStudyAreaLayer.setMinimumSize(QtCore.QSize(250, 0))
        self.cbStudyAreaLayer.setObjectName(_fromUtf8("cbStudyAreaLayer"))
        self.gridLayout_6.addWidget(self.cbStudyAreaLayer, 9, 0, 1, 1)
        self.lblQGISProject = QtGui.QLabel(self.frProjectControls2)
        self.lblQGISProject.setEnabled(True)
        self.lblQGISProject.setLineWidth(1)
        self.lblQGISProject.setObjectName(_fromUtf8("lblQGISProject"))
        self.gridLayout_6.addWidget(self.lblQGISProject, 4, 0, 1, 1)
        self.hlQGISProjectSelector = QtGui.QHBoxLayout()
        self.hlQGISProjectSelector.setSpacing(6)
        self.hlQGISProjectSelector.setObjectName(_fromUtf8("hlQGISProjectSelector"))
        self.leQGISProject = QtGui.QLineEdit(self.frProjectControls2)
        self.leQGISProject.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leQGISProject.sizePolicy().hasHeightForWidth())
        self.leQGISProject.setSizePolicy(sizePolicy)
        self.leQGISProject.setMinimumSize(QtCore.QSize(200, 0))
        self.leQGISProject.setMaximumSize(QtCore.QSize(200, 100))
        self.leQGISProject.setObjectName(_fromUtf8("leQGISProject"))
        self.hlQGISProjectSelector.addWidget(self.leQGISProject)
        self.tbQGISProject = QtGui.QToolButton(self.frProjectControls2)
        self.tbQGISProject.setEnabled(True)
        self.tbQGISProject.setObjectName(_fromUtf8("tbQGISProject"))
        self.hlQGISProjectSelector.addWidget(self.tbQGISProject)
        self.gridLayout_6.addLayout(self.hlQGISProjectSelector, 5, 0, 1, 1)
        self.cbPUField = QtGui.QComboBox(self.frProjectControls2)
        self.cbPUField.setObjectName(_fromUtf8("cbPUField"))
        self.gridLayout_6.addWidget(self.cbPUField, 13, 0, 1, 1)
        self.lblResultsLayer = QtGui.QLabel(self.frProjectControls2)
        self.lblResultsLayer.setObjectName(_fromUtf8("lblResultsLayer"))
        self.gridLayout_6.addWidget(self.lblResultsLayer, 14, 0, 1, 1)
        self.cbResultsLayer = QtGui.QComboBox(self.frProjectControls2)
        self.cbResultsLayer.setObjectName(_fromUtf8("cbResultsLayer"))
        self.gridLayout_6.addWidget(self.cbResultsLayer, 15, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frProjectControls2, 0, 2, 1, 1)
        self.tblProjectList = QtGui.QTableWidget(self.tbProjectsScenarios)
        self.tblProjectList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblProjectList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblProjectList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblProjectList.setObjectName(_fromUtf8("tblProjectList"))
        self.tblProjectList.setColumnCount(0)
        self.tblProjectList.setRowCount(0)
        self.gridLayout_7.addWidget(self.tblProjectList, 0, 0, 1, 1)
        self.twSettingsGIS.addTab(self.tbProjectsScenarios, _fromUtf8(""))
        self.tbGISSources = QtGui.QWidget()
        self.tbGISSources.setObjectName(_fromUtf8("tbGISSources"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tbGISSources)
        self.gridLayout_9.setMargin(6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblGIS = QtGui.QTableWidget(self.tbGISSources)
        self.tblGIS.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblGIS.setTabKeyNavigation(False)
        self.tblGIS.setProperty("showDropIndicator", False)
        self.tblGIS.setDragDropOverwriteMode(False)
        self.tblGIS.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblGIS.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblGIS.setObjectName(_fromUtf8("tblGIS"))
        self.tblGIS.setColumnCount(0)
        self.tblGIS.setRowCount(0)
        self.gridLayout_9.addWidget(self.tblGIS, 0, 0, 1, 1)
        self.vlGISControls = QtGui.QVBoxLayout()
        self.vlGISControls.setObjectName(_fromUtf8("vlGISControls"))
        self.frGISControls4 = QtGui.QFrame(self.tbGISSources)
        self.frGISControls4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frGISControls4.setFrameShadow(QtGui.QFrame.Raised)
        self.frGISControls4.setObjectName(_fromUtf8("frGISControls4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frGISControls4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hlGISName = QtGui.QHBoxLayout()
        self.hlGISName.setSpacing(6)
        self.hlGISName.setObjectName(_fromUtf8("hlGISName"))
        self.lblGISName = QtGui.QLabel(self.frGISControls4)
        self.lblGISName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGISName.sizePolicy().hasHeightForWidth())
        self.lblGISName.setSizePolicy(sizePolicy)
        self.lblGISName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblGISName.setObjectName(_fromUtf8("lblGISName"))
        self.hlGISName.addWidget(self.lblGISName)
        self.leGISName = QtGui.QLineEdit(self.frGISControls4)
        self.leGISName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGISName.sizePolicy().hasHeightForWidth())
        self.leGISName.setSizePolicy(sizePolicy)
        self.leGISName.setMinimumSize(QtCore.QSize(150, 0))
        self.leGISName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leGISName.setObjectName(_fromUtf8("leGISName"))
        self.hlGISName.addWidget(self.leGISName)
        self.verticalLayout.addLayout(self.hlGISName)
        self.hlGISDescription = QtGui.QHBoxLayout()
        self.hlGISDescription.setSpacing(6)
        self.hlGISDescription.setObjectName(_fromUtf8("hlGISDescription"))
        self.lblGISDescription = QtGui.QLabel(self.frGISControls4)
        self.lblGISDescription.setEnabled(True)
        self.lblGISDescription.setMinimumSize(QtCore.QSize(100, 0))
        self.lblGISDescription.setObjectName(_fromUtf8("lblGISDescription"))
        self.hlGISDescription.addWidget(self.lblGISDescription)
        self.pteGISDescription = QtGui.QPlainTextEdit(self.frGISControls4)
        self.pteGISDescription.setEnabled(True)
        self.pteGISDescription.setMaximumSize(QtCore.QSize(16777215, 70))
        self.pteGISDescription.setFrameShape(QtGui.QFrame.WinPanel)
        self.pteGISDescription.setFrameShadow(QtGui.QFrame.Sunken)
        self.pteGISDescription.setObjectName(_fromUtf8("pteGISDescription"))
        self.hlGISDescription.addWidget(self.pteGISDescription)
        self.verticalLayout.addLayout(self.hlGISDescription)
        self.hlGISProvider = QtGui.QHBoxLayout()
        self.hlGISProvider.setSpacing(6)
        self.hlGISProvider.setObjectName(_fromUtf8("hlGISProvider"))
        self.lblGISDataProvider = QtGui.QLabel(self.frGISControls4)
        self.lblGISDataProvider.setEnabled(True)
        self.lblGISDataProvider.setMinimumSize(QtCore.QSize(100, 0))
        self.lblGISDataProvider.setObjectName(_fromUtf8("lblGISDataProvider"))
        self.hlGISProvider.addWidget(self.lblGISDataProvider)
        self.leGISDataProvider = QtGui.QLineEdit(self.frGISControls4)
        self.leGISDataProvider.setEnabled(True)
        self.leGISDataProvider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leGISDataProvider.setObjectName(_fromUtf8("leGISDataProvider"))
        self.hlGISProvider.addWidget(self.leGISDataProvider)
        self.verticalLayout.addLayout(self.hlGISProvider)
        self.vlGISControls.addWidget(self.frGISControls4)
        self.frGISControls1 = QtGui.QFrame(self.tbGISSources)
        self.frGISControls1.setEnabled(True)
        self.frGISControls1.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frGISControls1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frGISControls1.setFrameShadow(QtGui.QFrame.Plain)
        self.frGISControls1.setObjectName(_fromUtf8("frGISControls1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frGISControls1)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblGISId = QtGui.QLabel(self.frGISControls1)
        self.lblGISId.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGISId.sizePolicy().hasHeightForWidth())
        self.lblGISId.setSizePolicy(sizePolicy)
        self.lblGISId.setObjectName(_fromUtf8("lblGISId"))
        self.gridLayout_8.addWidget(self.lblGISId, 1, 0, 1, 1)
        self.spbxGISId = QtGui.QSpinBox(self.frGISControls1)
        self.spbxGISId.setEnabled(True)
        self.spbxGISId.setMaximumSize(QtCore.QSize(150, 16777215))
        self.spbxGISId.setReadOnly(True)
        self.spbxGISId.setMinimum(1)
        self.spbxGISId.setMaximum(1000000)
        self.spbxGISId.setObjectName(_fromUtf8("spbxGISId"))
        self.gridLayout_8.addWidget(self.spbxGISId, 1, 1, 1, 1)
        self.lblGISStatus = QtGui.QLabel(self.frGISControls1)
        self.lblGISStatus.setEnabled(True)
        self.lblGISStatus.setObjectName(_fromUtf8("lblGISStatus"))
        self.gridLayout_8.addWidget(self.lblGISStatus, 1, 2, 1, 1)
        self.cbGISStatus = QtGui.QComboBox(self.frGISControls1)
        self.cbGISStatus.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbGISStatus.sizePolicy().hasHeightForWidth())
        self.cbGISStatus.setSizePolicy(sizePolicy)
        self.cbGISStatus.setMinimumSize(QtCore.QSize(100, 0))
        self.cbGISStatus.setObjectName(_fromUtf8("cbGISStatus"))
        self.cbGISStatus.addItem(_fromUtf8(""))
        self.cbGISStatus.addItem(_fromUtf8(""))
        self.cbGISStatus.addItem(_fromUtf8(""))
        self.cbGISStatus.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cbGISStatus, 1, 3, 1, 1)
        self.vlGISControls.addWidget(self.frGISControls1)
        self.frGISControls3 = QtGui.QFrame(self.tbGISSources)
        self.frGISControls3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frGISControls3.setFrameShadow(QtGui.QFrame.Plain)
        self.frGISControls3.setObjectName(_fromUtf8("frGISControls3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frGISControls3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.hlGISLayerType = QtGui.QHBoxLayout()
        self.hlGISLayerType.setObjectName(_fromUtf8("hlGISLayerType"))
        self.lblGISLayerType = QtGui.QLabel(self.frGISControls3)
        self.lblGISLayerType.setEnabled(True)
        self.lblGISLayerType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblGISLayerType.setObjectName(_fromUtf8("lblGISLayerType"))
        self.hlGISLayerType.addWidget(self.lblGISLayerType)
        self.cbGISLayerType = QtGui.QComboBox(self.frGISControls3)
        self.cbGISLayerType.setEnabled(True)
        self.cbGISLayerType.setObjectName(_fromUtf8("cbGISLayerType"))
        self.cbGISLayerType.addItem(_fromUtf8(""))
        self.cbGISLayerType.addItem(_fromUtf8(""))
        self.cbGISLayerType.addItem(_fromUtf8(""))
        self.cbGISLayerType.addItem(_fromUtf8(""))
        self.hlGISLayerType.addWidget(self.cbGISLayerType)
        self.verticalLayout_2.addLayout(self.hlGISLayerType)
        self.hlGISLayer = QtGui.QHBoxLayout()
        self.hlGISLayer.setObjectName(_fromUtf8("hlGISLayer"))
        self.lblGISLayer = QtGui.QLabel(self.frGISControls3)
        self.lblGISLayer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGISLayer.sizePolicy().hasHeightForWidth())
        self.lblGISLayer.setSizePolicy(sizePolicy)
        self.lblGISLayer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblGISLayer.setObjectName(_fromUtf8("lblGISLayer"))
        self.hlGISLayer.addWidget(self.lblGISLayer)
        self.cbGISLayer = QtGui.QComboBox(self.frGISControls3)
        self.cbGISLayer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbGISLayer.sizePolicy().hasHeightForWidth())
        self.cbGISLayer.setSizePolicy(sizePolicy)
        self.cbGISLayer.setObjectName(_fromUtf8("cbGISLayer"))
        self.cbGISLayer.addItem(_fromUtf8(""))
        self.hlGISLayer.addWidget(self.cbGISLayer)
        self.verticalLayout_2.addLayout(self.hlGISLayer)
        self.vlGISControls.addWidget(self.frGISControls3)
        self.frGISControls2 = QtGui.QFrame(self.tbGISSources)
        self.frGISControls2.setEnabled(True)
        self.frGISControls2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frGISControls2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frGISControls2.setFrameShadow(QtGui.QFrame.Plain)
        self.frGISControls2.setObjectName(_fromUtf8("frGISControls2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frGISControls2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblGISSingleMulti = QtGui.QLabel(self.frGISControls2)
        self.lblGISSingleMulti.setEnabled(True)
        self.lblGISSingleMulti.setObjectName(_fromUtf8("lblGISSingleMulti"))
        self.gridLayout_4.addWidget(self.lblGISSingleMulti, 2, 0, 1, 1)
        self.cbGISCalcField = QtGui.QComboBox(self.frGISControls2)
        self.cbGISCalcField.setEnabled(True)
        self.cbGISCalcField.setObjectName(_fromUtf8("cbGISCalcField"))
        self.cbGISCalcField.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbGISCalcField, 4, 1, 1, 1)
        self.cbGISSingleMulti = QtGui.QComboBox(self.frGISControls2)
        self.cbGISSingleMulti.setEnabled(True)
        self.cbGISSingleMulti.setObjectName(_fromUtf8("cbGISSingleMulti"))
        self.cbGISSingleMulti.addItem(_fromUtf8(""))
        self.cbGISSingleMulti.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbGISSingleMulti, 2, 1, 1, 1)
        self.cbGISCalcMethod = QtGui.QComboBox(self.frGISControls2)
        self.cbGISCalcMethod.setEnabled(True)
        self.cbGISCalcMethod.setObjectName(_fromUtf8("cbGISCalcMethod"))
        self.cbGISCalcMethod.addItem(_fromUtf8(""))
        self.cbGISCalcMethod.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbGISCalcMethod, 6, 1, 1, 1)
        self.lblGISCalcField = QtGui.QLabel(self.frGISControls2)
        self.lblGISCalcField.setEnabled(True)
        self.lblGISCalcField.setObjectName(_fromUtf8("lblGISCalcField"))
        self.gridLayout_4.addWidget(self.lblGISCalcField, 4, 0, 1, 1)
        self.lblGISCalcMethod = QtGui.QLabel(self.frGISControls2)
        self.lblGISCalcMethod.setEnabled(True)
        self.lblGISCalcMethod.setObjectName(_fromUtf8("lblGISCalcMethod"))
        self.gridLayout_4.addWidget(self.lblGISCalcMethod, 6, 0, 1, 1)
        self.lblGISMeasureType = QtGui.QLabel(self.frGISControls2)
        self.lblGISMeasureType.setEnabled(True)
        self.lblGISMeasureType.setObjectName(_fromUtf8("lblGISMeasureType"))
        self.gridLayout_4.addWidget(self.lblGISMeasureType, 2, 2, 1, 1)
        self.cbGISMeasureType = QtGui.QComboBox(self.frGISControls2)
        self.cbGISMeasureType.setEnabled(True)
        self.cbGISMeasureType.setObjectName(_fromUtf8("cbGISMeasureType"))
        self.cbGISMeasureType.addItem(_fromUtf8(""))
        self.cbGISMeasureType.addItem(_fromUtf8(""))
        self.cbGISMeasureType.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbGISMeasureType, 2, 3, 1, 1)
        self.lblGISIntAction = QtGui.QLabel(self.frGISControls2)
        self.lblGISIntAction.setEnabled(True)
        self.lblGISIntAction.setObjectName(_fromUtf8("lblGISIntAction"))
        self.gridLayout_4.addWidget(self.lblGISIntAction, 4, 2, 1, 1)
        self.cbGISIntAction = QtGui.QComboBox(self.frGISControls2)
        self.cbGISIntAction.setEnabled(True)
        self.cbGISIntAction.setObjectName(_fromUtf8("cbGISIntAction"))
        self.cbGISIntAction.addItem(_fromUtf8(""))
        self.cbGISIntAction.addItem(_fromUtf8(""))
        self.cbGISIntAction.addItem(_fromUtf8(""))
        self.cbGISIntAction.addItem(_fromUtf8(""))
        self.cbGISIntAction.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cbGISIntAction, 4, 3, 1, 1)
        self.lblGISPixelSize = QtGui.QLabel(self.frGISControls2)
        self.lblGISPixelSize.setEnabled(True)
        self.lblGISPixelSize.setObjectName(_fromUtf8("lblGISPixelSize"))
        self.gridLayout_4.addWidget(self.lblGISPixelSize, 6, 2, 1, 1)
        self.spbxGISPixelSize = QtGui.QSpinBox(self.frGISControls2)
        self.spbxGISPixelSize.setEnabled(True)
        self.spbxGISPixelSize.setMinimum(1)
        self.spbxGISPixelSize.setMaximum(1000000)
        self.spbxGISPixelSize.setSingleStep(10)
        self.spbxGISPixelSize.setProperty("value", 100)
        self.spbxGISPixelSize.setObjectName(_fromUtf8("spbxGISPixelSize"))
        self.gridLayout_4.addWidget(self.spbxGISPixelSize, 6, 3, 1, 1)
        self.vlGISControls.addWidget(self.frGISControls2)
        self.glGISControls = QtGui.QGridLayout()
        self.glGISControls.setObjectName(_fromUtf8("glGISControls"))
        self.line = QtGui.QFrame(self.tbGISSources)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.glGISControls.addWidget(self.line, 0, 0, 1, 1)
        self.pbSaveGISSource = QtGui.QPushButton(self.tbGISSources)
        self.pbSaveGISSource.setEnabled(False)
        self.pbSaveGISSource.setObjectName(_fromUtf8("pbSaveGISSource"))
        self.glGISControls.addWidget(self.pbSaveGISSource, 1, 0, 1, 1)
        self.pbDeleteGISSource = QtGui.QPushButton(self.tbGISSources)
        self.pbDeleteGISSource.setEnabled(False)
        self.pbDeleteGISSource.setObjectName(_fromUtf8("pbDeleteGISSource"))
        self.glGISControls.addWidget(self.pbDeleteGISSource, 2, 1, 1, 1)
        self.pbCancelGISSource = QtGui.QPushButton(self.tbGISSources)
        self.pbCancelGISSource.setEnabled(False)
        self.pbCancelGISSource.setObjectName(_fromUtf8("pbCancelGISSource"))
        self.glGISControls.addWidget(self.pbCancelGISSource, 2, 0, 1, 1)
        self.pbNewGISSource = QtGui.QPushButton(self.tbGISSources)
        self.pbNewGISSource.setObjectName(_fromUtf8("pbNewGISSource"))
        self.glGISControls.addWidget(self.pbNewGISSource, 1, 1, 1, 1)
        self.vlGISControls.addLayout(self.glGISControls)
        self.gridLayout_9.addLayout(self.vlGISControls, 0, 1, 1, 1)
        self.twSettingsGIS.addTab(self.tbGISSources, _fromUtf8(""))
        self.tbCalculation = QtGui.QWidget()
        self.tbCalculation.setObjectName(_fromUtf8("tbCalculation"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tbCalculation)
        self.gridLayout_5.setMargin(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.vlOperation = QtGui.QVBoxLayout()
        self.vlOperation.setSpacing(6)
        self.vlOperation.setObjectName(_fromUtf8("vlOperation"))
        self.lblActionsReport = QtGui.QLabel(self.tbCalculation)
        self.lblActionsReport.setObjectName(_fromUtf8("lblActionsReport"))
        self.vlOperation.addWidget(self.lblActionsReport)
        self.pteActionsReport = QtGui.QPlainTextEdit(self.tbCalculation)
        self.pteActionsReport.setReadOnly(True)
        self.pteActionsReport.setObjectName(_fromUtf8("pteActionsReport"))
        self.vlOperation.addWidget(self.pteActionsReport)
        self.hlActions = QtGui.QHBoxLayout()
        self.hlActions.setObjectName(_fromUtf8("hlActions"))
        self.lblActions = QtGui.QLabel(self.tbCalculation)
        self.lblActions.setMinimumSize(QtCore.QSize(200, 0))
        self.lblActions.setObjectName(_fromUtf8("lblActions"))
        self.hlActions.addWidget(self.lblActions)
        self.cbActions = QtGui.QComboBox(self.tbCalculation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbActions.sizePolicy().hasHeightForWidth())
        self.cbActions.setSizePolicy(sizePolicy)
        self.cbActions.setObjectName(_fromUtf8("cbActions"))
        self.hlActions.addWidget(self.cbActions)
        self.vlOperation.addLayout(self.hlActions)
        self.lblAllProgress = QtGui.QLabel(self.tbCalculation)
        self.lblAllProgress.setObjectName(_fromUtf8("lblAllProgress"))
        self.vlOperation.addWidget(self.lblAllProgress)
        self.pbAllProgress = QtGui.QProgressBar(self.tbCalculation)
        self.pbAllProgress.setProperty("value", 0)
        self.pbAllProgress.setObjectName(_fromUtf8("pbAllProgress"))
        self.vlOperation.addWidget(self.pbAllProgress)
        self.lblCurrentProgress = QtGui.QLabel(self.tbCalculation)
        self.lblCurrentProgress.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lblCurrentProgress.setObjectName(_fromUtf8("lblCurrentProgress"))
        self.vlOperation.addWidget(self.lblCurrentProgress)
        self.pbCurrentProgress = QtGui.QProgressBar(self.tbCalculation)
        self.pbCurrentProgress.setProperty("value", 0)
        self.pbCurrentProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbCurrentProgress.setTextVisible(True)
        self.pbCurrentProgress.setObjectName(_fromUtf8("pbCurrentProgress"))
        self.vlOperation.addWidget(self.pbCurrentProgress)
        self.lblStepProgress = QtGui.QLabel(self.tbCalculation)
        self.lblStepProgress.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lblStepProgress.setObjectName(_fromUtf8("lblStepProgress"))
        self.vlOperation.addWidget(self.lblStepProgress)
        self.pbStepProgress = QtGui.QProgressBar(self.tbCalculation)
        self.pbStepProgress.setProperty("value", 0)
        self.pbStepProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStepProgress.setTextVisible(True)
        self.pbStepProgress.setObjectName(_fromUtf8("pbStepProgress"))
        self.vlOperation.addWidget(self.pbStepProgress)
        self.hlCalculationButtons = QtGui.QHBoxLayout()
        self.hlCalculationButtons.setObjectName(_fromUtf8("hlCalculationButtons"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlCalculationButtons.addItem(spacerItem3)
        self.pbReport = QtGui.QPushButton(self.tbCalculation)
        self.pbReport.setObjectName(_fromUtf8("pbReport"))
        self.hlCalculationButtons.addWidget(self.pbReport)
        self.pbCalculate = QtGui.QPushButton(self.tbCalculation)
        self.pbCalculate.setEnabled(False)
        self.pbCalculate.setObjectName(_fromUtf8("pbCalculate"))
        self.hlCalculationButtons.addWidget(self.pbCalculate)
        self.pbCancel = QtGui.QPushButton(self.tbCalculation)
        self.pbCancel.setEnabled(False)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.hlCalculationButtons.addWidget(self.pbCancel)
        self.vlOperation.addLayout(self.hlCalculationButtons)
        self.gridLayout_5.addLayout(self.vlOperation, 0, 0, 1, 1)
        self.twSettingsGIS.addTab(self.tbCalculation, _fromUtf8(""))
        self.gridLayout.addWidget(self.twSettingsGIS, 1, 0, 1, 2)

        self.retranslateUi(dlgSettingsGIS)
        self.twSettingsGIS.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dlgSettingsGIS)

    def retranslateUi(self, dlgSettingsGIS):
        dlgSettingsGIS.setWindowTitle(QtGui.QApplication.translate("dlgSettingsGIS", "QMZ Settings, GIS and Calculation. Default Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClose.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWorkingProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Current Working Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveQMZSettings.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelQMZSettings.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMarxanZonesPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Marxan with Zones Executable Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMarxanZonesPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMarxanPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Marxan Executable Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "R Executable Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQMZDir.setText(QtGui.QApplication.translate("dlgSettingsGIS", "QMZ Projects Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDefaultProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Default Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMarxanPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRPath.setText(QtGui.QApplication.translate("dlgSettingsGIS", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbQMZDir.setText(QtGui.QApplication.translate("dlgSettingsGIS", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.twSettingsGIS.setTabText(self.twSettingsGIS.indexOf(self.tbSettings), QtGui.QApplication.translate("dlgSettingsGIS", "QMZ Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectDir.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Project Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.cbProjectType.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Marxan", None, QtGui.QApplication.UnicodeUTF8))
        self.lbProjectIsDefault.setText(QtGui.QApplication.translate("dlgSettingsGIS", "QMZ Default Project", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectType.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Project Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectName.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Project Title", None, QtGui.QApplication.UnicodeUTF8))
        self.cbProjectIsDefault.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.cbProjectIsDefault.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDuplicateProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPUField.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Source Planning Unit ID Field", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectDescription.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Project Description", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStudyAreaLayer.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Study Area Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPlanningLayer.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Source Planning Unit Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQGISProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "QGIS Project", None, QtGui.QApplication.UnicodeUTF8))
        self.tbQGISProject.setText(QtGui.QApplication.translate("dlgSettingsGIS", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblResultsLayer.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Results Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.twSettingsGIS.setTabText(self.twSettingsGIS.indexOf(self.tbProjectsScenarios), QtGui.QApplication.translate("dlgSettingsGIS", "Projects and Scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISName.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISDescription.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISDataProvider.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Data Provider:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISId.setText(QtGui.QApplication.translate("dlgSettingsGIS", "QMZ Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISStatus.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISStatus.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "No Data", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISStatus.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISStatus.setItemText(2, QtGui.QApplication.translate("dlgSettingsGIS", "PU Field", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISStatus.setItemText(3, QtGui.QApplication.translate("dlgSettingsGIS", "GIS Source", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISLayerType.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Layer Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISLayerType.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISLayerType.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISLayerType.setItemText(2, QtGui.QApplication.translate("dlgSettingsGIS", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISLayerType.setItemText(3, QtGui.QApplication.translate("dlgSettingsGIS", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISLayer.setText(QtGui.QApplication.translate("dlgSettingsGIS", "GIS Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISLayer.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Not Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISSingleMulti.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Assign to:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISCalcField.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Not Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISSingleMulti.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Single Field", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISSingleMulti.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Multiple Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISCalcMethod.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Vector Overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISCalcMethod.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Raster Estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISCalcField.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Calc Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISCalcMethod.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISMeasureType.setText(QtGui.QApplication.translate("dlgSettingsGIS", "On Intersection:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISMeasureType.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISMeasureType.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Measure x Field", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISMeasureType.setItemText(2, QtGui.QApplication.translate("dlgSettingsGIS", "Presence", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISIntAction.setText(QtGui.QApplication.translate("dlgSettingsGIS", "PU Intersection\n"
"Action", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISIntAction.setItemText(0, QtGui.QApplication.translate("dlgSettingsGIS", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISIntAction.setItemText(1, QtGui.QApplication.translate("dlgSettingsGIS", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISIntAction.setItemText(2, QtGui.QApplication.translate("dlgSettingsGIS", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISIntAction.setItemText(3, QtGui.QApplication.translate("dlgSettingsGIS", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGISIntAction.setItemText(4, QtGui.QApplication.translate("dlgSettingsGIS", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGISPixelSize.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Pixel Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveGISSource.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDeleteGISSource.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancelGISSource.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewGISSource.setText(QtGui.QApplication.translate("dlgSettingsGIS", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.twSettingsGIS.setTabText(self.twSettingsGIS.indexOf(self.tbGISSources), QtGui.QApplication.translate("dlgSettingsGIS", "GIS Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActionsReport.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Required and Possible Calculations:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActions.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Select Action:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAllProgress.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Overall Progress:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentProgress.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Current Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStepProgress.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Current Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbReport.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCalculate.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("dlgSettingsGIS", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.twSettingsGIS.setTabText(self.twSettingsGIS.indexOf(self.tbCalculation), QtGui.QApplication.translate("dlgSettingsGIS", "GIS Calculation and Reporting", None, QtGui.QApplication.UnicodeUTF8))

